insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290S',1,-1,null,null,0,1,null,-1,'N',null,-1,'needinvoicenum',0,'N',1,'N','Y',null,0,'needinvoicenum','so.execinfo.needinvoicenum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010096',null,'N',1,11,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290T',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','Y',null,0,'cmaterialid','so.execinfo.cmaterialid',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,null,null,'N',1,1,'cmaterialid','物料编码',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290U',1,-1,null,null,0,1,null,-1,'N',null,-1,'needpaymoney',0,'N',1,'N','Y',null,0,'needpaymoney','so.execinfo.needpaymoney',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010090',null,'N',1,13,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290V',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalsendnum',0,'N',1,'N','Y',null,0,'ntotalsendnum','so.execinfo.ntotalsendnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010077',null,'N',1,5,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290W',1,-1,null,null,0,1,null,-1,'N',null,-1,'needoutnum',0,'N',1,'N','Y','needoutnum->nnum-ntotaloutnum',0,'needoutnum','so.execinfo.needoutnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010091',null,'N',1,8,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290X',1,-1,null,null,0,1,null,-1,'N',null,-1,'totalpaymoney',0,'N',1,'N','Y',null,0,'totalpaymoney','so.execinfo.totalpaymoney',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010057',null,'N',1,12,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'shouldsendnum',0,'N',1,'N','Y',null,0,'shouldsendnum','so.execinfo.shouldsendnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010058',null,'N',1,9,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000290Z',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,null,null,'N',1,2,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002910',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotaloutnum',0,'N',1,'N','Y',null,0,'ntotaloutnum','so.execinfo.ntotaloutnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010078',null,'N',1,7,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002911',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalinvoicenum',0,'N',1,'N','Y','needinvoicenum->nnum-ntotalinvoicenum',0,'ntotalinvoicenum','so.execinfo.ntotalinvoicenum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010092',null,'N',1,10,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002912',1,-1,null,null,0,1,null,-1,'N',null,-1,'needsendnum',0,'N',1,'N','Y','needsendnum->nnum-ntotalsendnum',0,'needsendnum','so.execinfo.needsendnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010128',null,'N',1,6,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002913',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.execinfo.nnum',null,'N',0,null,'1001Z81000000000290R','@@@@',1,null,'1400603010027',null,'N',1,4,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002914',1,-1,null,null,0,1,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','so.execinfo.cunitid',null,'N',0,null,'1001Z81000000000290R','@@@@',1,'计量单位,code=N',null,null,'N',1,3,'cmaterialid','cmaterialid',0,'2011-09-02 14:34:31','N',null,null,null,1,1,'N',1,null,100,null)
go

