insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000046GR',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigarmny',0,'N',1,'N','Y',null,0,'norigarmny','so.so_balance_b.norigarmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,26,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000046GS',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigotherbalmny',0,'N',1,'N','Y',null,0,'norigotherbalmny','so.so_balance_b.norigotherbalmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,30,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_balance.pk_org',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'销售组织,code=N',null,null,'N',1,3,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EML',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','so.so_balance.pk_org_v',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'销售组织版本,code=N',null,null,'N',1,4,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMM',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigordbalmny',0,'N',1,'N','Y',null,0,'norigordbalmny','so.so_balance_b.norigordbalmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,29,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMN',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.so_balance.corigcurrencyid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'币种档案,code=N',null,null,'N',1,9,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMO',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaybillid',0,'N',1,'N','N',null,0,'cpaybillid','so.so_balance_b.cpaybillid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,21,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMP',1,-1,null,null,0,0,null,-1,'N',null,-1,'cinvoicecustid',0,'N',1,'N','N',null,0,'cinvoicecustid','so.so_balance.cinvoicecustid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'客户档案,code=N',null,null,'N',0,7,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.so_balance.vtrantypecode',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',0,17,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMR',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalpaymny',0,'N',1,'N','N',null,0,'ntotalpaymny','so.so_balance.ntotalpaymny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,11,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMS',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaybillrowid',0,'N',1,'N','N',null,0,'cpaybillrowid','so.so_balance_b.cpaybillrowid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,22,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMT',1,-1,null,null,0,0,null,-1,'N',null,-1,'csobalancebid',0,'N',1,'N','N',null,0,'csobalancebid','so.so_balance_b.csobalancebid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,19,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMU',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.so_balance_b.cprodlineid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'产品线,code=N',null,null,'N',1,28,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMV',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaytermid',0,'N',1,'N','N',null,0,'cpaytermid','so.so_balance.cpaytermid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'收款协议,code=N',null,null,'N',0,13,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMW',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorderid',0,'N',1,'N','N',null,0,'csaleorderid','so.so_balance.csaleorderid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,2,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMX',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','N',null,0,'ccustomerid','so.so_balance.ccustomerid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'客户档案,code=N',null,null,'N',0,6,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMY',1,-1,null,null,0,1,'remainmny->zeroifnull(norigarmny)-zeroifnull(norigordbalmny)-zeroifnull(norigotherbalmny)-zeroifnull(norigthisbalmny)',-1,'N',null,-1,'norigthisbalmny',0,'N',1,'N','Y',null,0,'norigthisbalmny','so.so_balance_b.norigthisbalmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,31,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'darbilldate',0,'N',1,'N','Y',null,0,'darbilldate','so.so_balance_b.darbilldate',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,24,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN0',1,-1,null,null,0,0,null,-1,'N',null,-1,'fibaltype',0,'N',1,'N','Y',null,0,'fibaltype','so.so_balance_b.fibaltype',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,20,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN1',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','N',null,0,'vbillcode','so.so_balance.vbillcode',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,8,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN2',1,-1,null,null,0,0,null,-1,'N',null,-1,'carorigcurrencyid',0,'N',1,'N','N',null,0,'carorigcurrencyid','so.so_balance_b.carorigcurrencyid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'币种档案,code=N',null,null,'N',0,25,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN3',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigtaxmny',0,'N',1,'N','N',null,0,'ntotalorigtaxmny','so.so_balance.ntotalorigtaxmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,10,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN4',1,-1,null,null,0,0,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','N',null,0,'cemployeeid','so.so_balance.cemployeeid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'人员,code=N',null,null,'N',0,14,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN5',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_balance.pk_group',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'集团,code=N',null,null,'N',0,5,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN6',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigaccbalmny',0,'N',1,'N','N',null,0,'norigaccbalmny','so.so_balance_b.norigaccbalmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,32,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN7',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','N',null,0,'cdeptid','so.so_balance.cdeptid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'部门,code=N',null,null,'N',0,15,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN8',1,-1,null,null,0,0,null,-1,'N',null,-1,'varbillcode',0,'N',1,'N','Y',null,0,'varbillcode','so.so_balance_b.varbillcode',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,23,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EN9',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigbalmny',0,'N',1,'N','N',null,0,'ntotalorigbalmny','so.so_balance.ntotalorigbalmny',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,12,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ENA',1,-1,null,null,0,0,null,-1,'N',null,-1,'darbalancedate',0,'N',1,'N','Y',null,0,'darbalancedate','so.so_balance_b.darbalancedate',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',1,27,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ENB',1,-1,null,null,0,0,null,-1,'N',null,-1,'carorgid',0,'N',1,'N','N',null,0,'carorgid','so.so_balance.carorgid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'财务组织,code=N',null,null,'N',0,16,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ENC',1,-1,null,null,0,0,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','N',null,0,'cchanneltypeid','so.so_balance.cchanneltypeid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,'渠道类型,code=N',null,null,'N',0,18,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005END',1,-1,null,null,0,0,null,-1,'N',null,-1,'csobalanceid',0,'N',1,'N','N',null,0,'csobalanceid','so.so_balance.csobalanceid',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,1,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EO2',1,2,null,null,0,0,null,-1,'N',null,20,'remainmny',null,'N',1,'N','Y','remainmny->zeroifnull(norigarmny)-zeroifnull(norigordbalmny)-zeroifnull(norigotherbalmny)-zeroifnull(norigthisbalmny)',0,null,null,null,'N',0,null,'1001Z81000000000592F',null,1,'2','UC000-0000249',null,'N',1,33,'view','订单收款核销',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007XHY',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_balance_b.ts',null,'N',0,null,'1001Z81000000000592F','@@@@',1,null,null,null,'N',0,34,'view','view',0,'2013-07-10 16:42:23','N',null,null,null,1,1,'N',1,null,100,null)
go

