/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m38trantype.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
import nc.vo.so.m32trantype.entity.M32TranTypeVO;

/**
 * <b> 预订单交易类型VO </b>
 * <p>
 * 预订单交易类型VO
 * </p>
 * 创建日期:2010-03-25 17:00:02
 * 
 * @author 刘志伟
 * @version 6.0
 */

public class M38TranTypeVO extends SuperVO {

  private static final long serialVersionUID = 3003866045382547995L;

  /** 只能安排一次 */
  public static final String BARRANGE = "barrange";

  /** 询到价格是否可改 */
  public static final String BMODIFYASKEDQT = "bmodifyaskedqt";

  /** 允许修改折扣 */
  public static final String BMODIFYDISCOUNT = "bmodifydiscount";

  /** 未询到价格是否可改 */
  public static final String BMODIFYUNASKEDQT = "bmodifyunaskedqt";

  /** 同一货物可否列多行 */
  public static final String BMOREROWS = "bmorerows";

  /** 未询到价格是否提示 */
  public static final String BNOFINDPRICEHIT = "bnofindpricehit";

  /** 单据类型 */
  public static final String CTRANTYPEID = "ctrantypeid";

  /** 询价规则 */
  public static final String FASKQTRULE = "faskqtrule";

  /** 赠品取价规则 */
  public static final String FLARGESSGETQTRULE = "flargessgetqtrule";

  /** 调整金额影响折扣还是单价 */
  public static final String FMODIFYMNY = "fmodifymny";

  /** 集团 */
  public static final String PK_GROUP = "pk_group";

  /** 预订单交易类型主键 */
  public static final String PK_TRANTYPE = "pk_trantype";

  /** 时间戳 */
  public static final String TS = "ts";

  /** 交易类型编码 */
  public static final String VTRANTYPECODE = "vtrantypecode";

  /**
   * 按照默认方式创建构造子.
   * 
   * 创建日期:2010-03-25 17:00:02
   */
  public M38TranTypeVO() {
    super();
  }

  public UFBoolean getBarrange() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BARRANGE);
  }

  public UFBoolean getBmodifyaskedqt() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BMODIFYASKEDQT);
  }

  public UFBoolean getBmodifydiscount() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BMODIFYDISCOUNT);
  }

  public UFBoolean getBmodifyunaskedqt() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BMODIFYUNASKEDQT);
  }

  public UFBoolean getBmorerows() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BMOREROWS);
  }

  public UFBoolean getBnofindpricehit() {
    return (UFBoolean) this.getAttributeValue(M38TranTypeVO.BNOFINDPRICEHIT);
  }

  public String getCtrantypeid() {
    return (String) this.getAttributeValue(M38TranTypeVO.CTRANTYPEID);
  }

  public Integer getFaskqtrule() {
    return (Integer) this.getAttributeValue(M38TranTypeVO.FASKQTRULE);
  }

  public Integer getFlargessgetqtrule() {
    return (Integer) this.getAttributeValue(M38TranTypeVO.FLARGESSGETQTRULE);
  }

  public Integer getFmodifymny() {
    return (Integer) this.getAttributeValue(M38TranTypeVO.FMODIFYMNY);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("so.m38trantype");
    return meta;
  }

  public String getPk_group() {
    return (String) this.getAttributeValue(M38TranTypeVO.PK_GROUP);
  }

  public String getPkTrantype() {
    return (String) this.getAttributeValue(M38TranTypeVO.PK_TRANTYPE);
  }

  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(M32TranTypeVO.TS);
  }

  public String getVtrantypecode() {
    return (String) this.getAttributeValue(M38TranTypeVO.VTRANTYPECODE);
  }

  public void setBarrange(String barrange) {
    this.setAttributeValue(M38TranTypeVO.BARRANGE, barrange);
  }

  public void setBmodifyaskedqt(String bmodifyaskedqt) {
    this.setAttributeValue(M38TranTypeVO.BMODIFYASKEDQT, bmodifyaskedqt);
  }

  public void setBmodifydiscount(String bmodifydiscount) {
    this.setAttributeValue(M38TranTypeVO.BMODIFYDISCOUNT, bmodifydiscount);
  }

  public void setBmodifyunaskedqt(String bmodifyunaskedqt) {
    this.setAttributeValue(M38TranTypeVO.BMODIFYUNASKEDQT, bmodifyunaskedqt);
  }

  public void setBmorerows(String bmorerows) {
    this.setAttributeValue(M38TranTypeVO.BMOREROWS, bmorerows);
  }

  public void setBnofindpricehit(String bnofindpricehit) {
    this.setAttributeValue(M38TranTypeVO.BNOFINDPRICEHIT, bnofindpricehit);
  }

  public void setCtrantypeid(String ctrantypeid) {
    this.setAttributeValue(M38TranTypeVO.CTRANTYPEID, ctrantypeid);
  }

  public void setFaskqtrule(String faskqtrule) {
    this.setAttributeValue(M38TranTypeVO.FASKQTRULE, faskqtrule);
  }

  public void setFlargessgetqtrule(String flargessgetqtrule) {
    this.setAttributeValue(M38TranTypeVO.FLARGESSGETQTRULE, flargessgetqtrule);
  }

  public void setFmodifymny(String fmodifymny) {
    this.setAttributeValue(M38TranTypeVO.FMODIFYMNY, fmodifymny);
  }

  public void setPk_group(String pk_group) {
    this.setAttributeValue(M38TranTypeVO.PK_GROUP, pk_group);
  }

  public void setPkTrantype(String pkTrantype) {
    this.setAttributeValue(M38TranTypeVO.PK_TRANTYPE, pkTrantype);
  }

  public void setTs(UFDateTime ts) {
    this.setAttributeValue(M32TranTypeVO.TS, ts);
  }

  public void setVtrantypecode(String vtrantypecode) {
    this.setAttributeValue(M38TranTypeVO.VTRANTYPECODE, vtrantypecode);
  }
}
