insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000005889W',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmorerows',null,'N',1,'N','Y',null,0,'bmorerows','so.m4310trantype.bmorerows',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,15,'m4310trantype','m4310trantype',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000NX5',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fmodifymny',0,'N',1,'N','Y',null,0,'fmodifymny','so.m4310trantype.fmodifymny',null,'N',1,null,'1002Z81000000000K283','@@@@',0,null,null,null,'N',1,14,'m4310trantype','m4310trantype',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000AIRE',1,-1,null,'true',0,0,null,-1,'N',null,-1,'bunitmatrule',null,'N',1,'N','N',null,0,'bunitmatrule','so.m4310trantype.bunitmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,11,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,0,1,'N',0,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000AIRF',1,-1,null,'true',0,0,null,-1,'N',null,-1,'bcurrtypematrule',null,'N',1,'N','N',null,0,'bcurrtypematrule','so.m4310trantype.bcurrtypematrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,12,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,0,1,'N',0,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KEL7',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bsendtypematrule',null,'N',1,'N','Y',null,0,'bsendtypematrule','so.m4310trantype.bsendtypematrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,8,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KEL8',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bempmatrule',null,'N',1,'N','Y',null,0,'bempmatrule','so.m4310trantype.bempmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,5,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KEL9',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fsourceflag',null,'N',1,'N','Y',null,0,'fsourceflag','so.m4310trantype.fsourceflag',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,4,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELA',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bsuccqteditable',null,'N',1,'N','Y',null,0,'bsuccqteditable','so.m4310trantype.bsuccqteditable',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,10,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELB',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bquallevelmatrule',null,'N',1,'N','Y',null,0,'bquallevelmatrule','so.m4310trantype.bquallevelmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,9,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELC',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bpaytermmatrule',null,'N',1,'N','Y',null,0,'bpaytermmatrule','so.m4310trantype.bpaytermmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,6,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELD',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bautocloseflag',null,'N',1,'N','Y',null,0,'bautocloseflag','so.m4310trantype.bautocloseflag',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,8,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELE',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fhistoryflag',null,'N',1,'N','Y',null,0,'fhistoryflag','so.m4310trantype.fhistoryflag',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,5,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELF',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bfailqteditable',null,'N',1,'N','Y',null,0,'bfailqteditable','so.m4310trantype.bfailqteditable',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,11,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','so.m4310trantype.pk_group',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,9,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELH',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bbalatypematrule',null,'N',1,'N','Y',null,0,'bbalatypematrule','so.m4310trantype.bbalatypematrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,7,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELI',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bquotypematrule',null,'N',1,'N','Y',null,0,'bquotypematrule','so.m4310trantype.bquotypematrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,3,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmatchrule',null,'N',1,'N','N',null,0,'vmatchrule','so.m4310trantype.vmatchrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,7,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantype',null,'N',1,'N','N',null,0,'vtrantype','so.m4310trantype.vtrantype',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,3,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELM',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_trantype',null,'N',1,'N','N',null,0,'pk_trantype','so.m4310trantype.pk_trantype',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,1,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELN',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','so.m4310trantype.ts',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',0,13,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELO',1,-1,null,'1',0,1,null,-1,'N',null,-1,'iavgmonth',null,'N',1,'N','Y',null,0,'iavgmonth','so.m4310trantype.iavgmonth',null,'N',1,null,'1002Z81000000000K283',null,0,'0,',null,null,'N',1,6,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELP',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bchanmatrule',null,'N',1,'N','Y',null,0,'bchanmatrule','so.m4310trantype.bchanmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,2,'hisSalequoMatchRule',null,0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELR',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bareamatrule',null,'N',1,'N','Y',null,0,'bareamatrule','so.m4310trantype.bareamatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,10,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELS',1,-1,null,'true',0,1,null,-1,'N',null,-1,'bdiscounteditable',null,'N',1,'N','Y',null,0,'bdiscounteditable','so.m4310trantype.bdiscounteditable',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,12,'m4310trantype','报价单交易类型',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELU',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bdeptmatrule',null,'N',1,'N','Y',null,0,'bdeptmatrule','so.m4310trantype.bdeptmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,4,'hisSalequoMatchRule','hisSalequoMatchRule',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000KELV',1,-1,null,'true',0,1,null,-1,'N',null,-1,'bcustmatrule',null,'N',1,'N','Y',null,0,'bcustmatrule','so.m4310trantype.bcustmatrule',null,'N',0,null,'1002Z81000000000K283',null,0,null,null,null,'N',1,1,'hisSalequoMatchRule',null,0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001S2Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','N',null,0,'ctrantypeid','so.m4310trantype.ctrantypeid','vtrantype=pk_billtypecode','N',0,null,'1002Z81000000000K283','@@@@',0,null,null,null,'N',0,2,'m4310trantype','m4310trantype',0,'2015-04-22 22:37:55','N',null,null,null,1,1,'N',1,null,1,2)
go

