insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002DNE',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','N',null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,null,null,null,'N',0,10,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B6SF',1,5,'物料销售分类',null,0,1,null,-1,'N',null,20,'pk_materialsaleclass',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'物料销售分类','1400601010010',null,'N',1,11,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B6SG',1,5,'物料基本分类',null,0,1,null,-1,'N',null,20,'pk_materialbaseclass',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'物料基本分类','1400601010009',null,'N',1,10,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B7KR',1,5,'物料',null,0,1,null,-1,'N',null,20,'pk_material',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'物料','1400601010008',null,'N',1,12,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BTYH',1,5,'客户基本分类',null,0,1,null,-1,'N',null,20,'pk_custbaseclass',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'客户基本分类','1400601010005',null,'N',1,7,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BTYI',1,5,'客户编码',null,0,1,null,-1,'N',null,20,'pk_customer',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'客户档案,code=Y','1400601010006',null,'N',1,9,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BTYJ',1,5,'客户销售分类',null,0,1,null,-1,'N',null,20,'pk_custsaleclass',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z81000000000ED2U','@@@@',0,'客户销售分类','1400601010007',null,'N',1,8,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED2V',1,-1,'备注',null,0,1,null,-1,'N',null,-1,'vnote',null,'N',1,'N','Y',null,0,'vnote','so.so_custmatrel_b.vnote',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,'UC000-0001376',null,'N',1,16,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED2W',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','so.so_custmatrel_b.pk_org',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,null,null,'N',0,2,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',0,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED2X',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialsaleclass',null,'N',1,'N','Y',null,0,'pk_materialsaleclass','so.so_custmatrel_b.pk_materialsaleclass',null,'N',0,null,'1002Z81000000000ED2U',null,1,'物料销售分类,code=N',null,null,'N',1,8,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED2Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','so.so_custmatrel.pk_org',null,'N',1,null,'1002Z81000000000ED2U',null,0,null,null,null,'N',0,2,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',0,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED2Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_custmatrel_b',null,'N',1,'N','N',null,0,'pk_custmatrel_b','so.so_custmatrel_b.pk_custmatrel_b',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,null,null,'N',0,1,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED30',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','so.so_custmatrel.ts',null,'N',0,null,'1002Z81000000000ED2U',null,0,null,null,null,'N',0,6,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED31',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','N',null,0,'pk_org_v','so.so_custmatrel.pk_org_v',null,'N',1,null,'1002Z81000000000ED2U',null,0,null,null,null,'N',0,3,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',0,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED32',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_custsaleclass',null,'N',1,'N','Y',null,0,'pk_custsaleclass','so.so_custmatrel_b.pk_custsaleclass',null,'N',0,null,'1002Z81000000000ED2U',null,1,'客户销售分类,code=N',null,null,'N',1,4,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED33',1,-1,null,null,0,1,null,-1,'N',null,-1,'exclude',null,'N',1,'N','Y',null,0,'exclude','so.so_custmatrel_b.exclude',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,null,null,'N',1,15,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED34',1,-1,'物料编码',null,0,1,null,-1,'N',null,-1,'pk_material_v',null,'N',1,'N','Y',null,0,'pk_material_v','so.so_custmatrel_b.pk_material_v','pk_material=pk_source','N',0,null,'1002Z81000000000ED2U',null,1,'物料（多版本）','UC000-0002911',null,'N',1,11,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED35',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_material',null,'N',1,'N','N',null,0,'pk_material','so.so_custmatrel_b.pk_material',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,null,null,'N',0,9,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED36',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','so.so_custmatrel.pk_group',null,'N',1,null,'1002Z81000000000ED2U',null,0,null,null,null,'N',0,4,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED37',1,-1,'客户编码',null,0,1,null,-1,'N',null,-1,'pk_customer',null,'N',1,'N','Y',null,0,'pk_customer','so.so_custmatrel_b.pk_customer',null,'N',0,null,'1002Z81000000000ED2U',null,1,'客户档案','UC000-0001611',null,'N',1,5,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED38',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_custbaseclass',null,'N',1,'N','Y',null,0,'pk_custbaseclass','so.so_custmatrel_b.pk_custbaseclass',null,'N',0,null,'1002Z81000000000ED2U',null,1,'客户基本分类,code=N',null,null,'N',1,3,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED39',1,-1,'允许销售/禁止销售',null,0,1,null,-1,'N',null,-1,'allowsale',null,'N',1,'N','Y',null,0,'allowsale','so.so_custmatrel.allowsale',null,'N',1,null,'1002Z81000000000ED2U',null,0,null,'1400601010001',null,'N',1,5,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3A',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialbaseclass',null,'N',1,'N','Y',null,0,'pk_materialbaseclass','so.so_custmatrel_b.pk_materialbaseclass',null,'N',0,null,'1002Z81000000000ED2U',null,1,'物料基本分类,code=N',null,null,'N',1,7,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3B',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','so.so_custmatrel_b.ts',null,'N',0,null,'1002Z81000000000ED2U',null,1,null,null,null,'N',0,17,'pk_custmatrel_b','客户物料关系子实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3C',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_custmatrel',null,'N',1,'N','N',null,0,'pk_custmatrel','so.so_custmatrel.pk_custmatrel',null,'N',0,null,'1002Z81000000000ED2U',null,0,null,null,null,'N',0,1,'so_custmatrel','客户物料关系主实体',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3J',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,null,null,null,'N',1,13,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3K',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,null,null,null,'N',1,12,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3L',1,-1,null,null,0,0,null,-1,'N','pk_customer',-1,'pk_customer.name',0,'N',1,'N','Y',null,0,'name','uap.customer.name',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,null,null,null,'N',1,6,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ED3M',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,null,null,null,'N',1,14,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z8100000000017ZY',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_custmatrel_b.pk_group',null,'N',0,null,'1002Z81000000000ED2U','@@@@',1,'集团,code=N',null,null,'N',0,18,'pk_custmatrel_b','pk_custmatrel_b',0,'2015-07-08 10:28:39','N',null,null,null,0,1,'N',0,null,100,18)
go

