insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019IX','客户档案',5,27,0,null,null,'ccustomercode','客户.客户编码',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010048',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019IY','-99',9,28,1,null,null,'ccustomername','客户.客户名称',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010038',2,null,null,'2011-10-25 17:49:48','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019IZ','客户基本分类',5,29,1,null,null,'pk_custclass','客户.客户基本分类',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010042',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J0','地区分类',5,30,1,null,null,'ccustomerpk_areacl','客户.地区分类',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010039',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J2','销售组织',5,32,1,null,null,'csaleorgid','销售组织',null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'UC000-0004128',2,null,null,'2011-10-25 15:02:03','N','#mainorg#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J3','物料',5,33,0,null,null,'cmaterialcode','物料编码.物料编码',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010053',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J4','-99',9,34,1,null,null,'cmaterialname','物料编码.物料名称',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010043',2,null,null,'2011-10-25 17:49:48','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J5','物料基本分类',5,35,1,null,null,'pk_marbasclass','物料编码.物料分类',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010054',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z8100000000019J7','影响因素交 易类型',5,37,1,null,null,'ctrantypeid','交易类型',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010046',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOH','-99',3,1,1,null,null,'dbilldate','单据日期',null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'N',9999,null,'between@','介于@',0,'@@@@','1002Z81000000000BKOE',null,'UC000-0000799',2,null,null,'2011-10-25 15:02:03','N','#day(-1)#,#day(-1)#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOS','IX,1400609010034=0,1400609010033=1',6,12,1,null,null,'isdeducttranslos','扣除途损',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','N','Y',null,'N',9999,null,'==@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010052',2,null,null,'2011-12-02 10:00:04','N','0')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOT','部门',5,13,1,null,null,'cdeptid','部门',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'UC000-0004064',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOU','人员',5,14,1,null,null,'cemployeeid','业务员',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010041',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOV','币种档案',5,15,1,null,null,'corigcurrencyid','原币币种',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'=','等于@',0,'@@@@','1002Z81000000000BKOE',null,'UC000-0000914',2,null,null,'2011-10-25 15:02:03','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOX','IX,1400609010036=0,1400609010035=1',6,17,1,null,null,'containlaboranddiscount','统计服务和折扣',null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'N',9999,null,'==@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010044',2,null,null,'2011-12-02 10:00:04','N','1')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BKOY','IM,380e1847-6624-48b9-b525-2bcba39b6d7d',6,18,1,null,null,'saleorderfstatusflag','销售订单状态',null,'N','Y','N','Y','N','N','N','N','N','Y','N','Y','N','N','Y',null,'N',9999,null,'=@<>@','等于@不等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010047',2,null,null,'2011-10-25 15:02:03','N','2')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BM89','IM,380e1847-6624-48b9-b525-2bcba39b6d7d',6,23,1,null,null,'deliveryfstatusflag','发货单单据状态',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010049',2,null,null,'2011-10-25 15:02:03','N','2')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BM8D','IM,b5a99c8d-3fe5-4392-bdac-31a95c60cae9',6,24,1,null,null,'generalstatusflag','出库单单据状态',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010051',2,null,null,'2011-10-25 15:02:03','N','3')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BM8H','IM,380e1847-6624-48b9-b525-2bcba39b6d7d',6,25,1,null,null,'saleinvoicefstatusflag','销售发票单据状态',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010037',2,null,null,'2011-10-25 15:02:03','N','2')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1002Z81000000000BM8L','IM,fae2410f-330e-47e5-80fe-ed1a4ca4275a',6,26,1,null,null,'recbillfstatusflag','应收单单据状态',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1002Z81000000000BKOE',null,'1400609010045',2,null,null,'2011-10-25 15:02:03','N','1')
go

