insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000079M2',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','so.returnpolicy.pk_org',null,'N',0,null,'1002Z8100000000033AD',null,1,'销售组织,code=N,type=0','140060801050001',null,'N',0,1,'returnpolicy','returnpolicy',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007QKI',1,-1,null,null,0,0,null,-1,'N',null,-1,'vexpresscode',0,'N',1,'N','N',null,0,'vexpresscode','so.returnpolicy.vexpresscode',null,'N',0,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',0,9,'returnpolicy','returnpolicy',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007QKJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vexpressname',0,'N',1,'N','Y',null,0,'vexpressname','so.returnpolicy.vexpressname',null,'N',1,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,6,'returnpolicy','returnpolicy',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003676',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_returnpolicy',0,'N',1,'N','N',null,0,'pk_returnpolicy','so.returnpolicy.pk_returnpolicy',null,'N',0,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',0,3,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003677',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpolicyname',0,'N',1,'N','Y',null,0,'vpolicyname','so.returnpolicy.vpolicyname',null,'N',1,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,5,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003678',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','Y',null,0,'pk_group','so.returnpolicy.pk_group',null,'N',0,null,'1002Z8100000000033AD','@@@@',1,'集团,code=N',null,null,'N',1,2,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000367A',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpolicydetail',0,'N',1,'N','Y',null,0,'vpolicydetail','so.returnpolicy.vpolicydetail',null,'N',0,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,7,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000367B',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpolicycode',0,'N',1,'N','Y',null,0,'vpolicycode','so.returnpolicy.vpolicycode',null,'N',1,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,4,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000367D',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.returnpolicy.ts',null,'N',0,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',0,8,'returnpolicy','退货政策设置',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000SWW9',1,-1,null,null,0,1,null,-1,'N',null,-1,'dstartdate',0,'N',1,'N','Y',null,0,'dstartdate','so.returnpolicy.dstartdate',null,'N',1,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,10,'returnpolicy','returnpolicy',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000SWWA',1,-1,null,null,0,1,null,-1,'N',null,-1,'denddate',0,'N',1,'N','Y',null,0,'denddate','so.returnpolicy.denddate',null,'N',1,null,'1002Z8100000000033AD','@@@@',1,null,null,null,'N',1,11,'returnpolicy','returnpolicy',0,'2011-08-16 16:30:20','N',null,null,null,1,1,'N',1,null,100,null)
go

