/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m38.entity;

import nc.vo.credit.creditaudit.entity.CreditAuditHVO;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 预订单表头VO </b>
 * <p>
 * 预订单表头VO
 * </p>
 * 创建日期:2010-03-31 13:38:44
 * 
 * @author 刘志伟
 * @version NCPrj 6.0
 */

public class PreOrderHVO extends SuperVO {

  private static final long serialVersionUID = -8745067909122827639L;

  /** 审批人 */
  public static final String APPROVER = "approver";

  /** 制单人 */
  public static final String BILLMAKER = "billmaker";

  /** 销售渠道类型 */
  public static final String CCHANNELTYPEID = "cchanneltypeid";

  /** 客户 */
  public static final String CCUSTOMERID = "ccustomerid";

  /** 部门 */
  public static final String CDEPTID = "cdeptid";

  /** 部门版本 */
  public static final String CDEPTVID = "cdeptvid";

  /** 业务员 */
  public static final String CEMPLOYEEID = "cemployeeid";

  /** 开票客户 */
  public static final String CINVOICECUSTID = "cinvoicecustid";

  /** 币种 */
  public static final String CORIGCURRENCYID = "corigcurrencyid";

  /** 收款协议 */
  public static final String CPAYTERMID = "cpaytermid";

  /** 预订单主表 */
  public static final String CPREORDERID = "cpreorderid";

  /** 创建时间 */
  public static final String CREATIONTIME = "creationtime";

  /** 创建人 */
  public static final String CREATOR = "creator";

  /** 运输方式 */
  public static final String CTRANSPORTTYPEID = "ctransporttypeid";

  /** 预订单类型 */
  public static final String CTRANTYPEID = "ctrantypeid";

  /** 网上订单制单人 */
  public static final String CWEBOPERATORID = "cweboperatorid";

  /** 失效日期 */
  public static final String DABATEDATE = "dabatedate";

  /** 订货日期 */
  public static final String DBILLDATE = "dbilldate";

  /** 单据状态 */
  public static final String FSTATUSFLAG = "fstatusflag";

  /** 打印次数 */
  public static final String IPRINTCOUNT = "iprintcount";

  /** 最后修改时间 */
  public static final String MODIFIEDTIME = "modifiedtime";

  /** 最后修改人 */
  public static final String MODIFIER = "modifier";

  /** 整单折扣 */
  public static final String NDISCOUNTRATE = "ndiscountrate";

  /** 价税合计 */
  public static final String NHEADSUMMNY = "nheadsummny";

  /** 总数量 */
  public static final String NTOTALNUM = "ntotalnum";

  /** 集团 */
  public static final String PK_GROUP = "pk_group";

  /** 销售组织 */
  public static final String PK_ORG = "pk_org";

  /** 销售组织版本 */
  public static final String PK_ORG_V = "pk_org_v";

  /** 审批时间 */
  public static final String TAUDITTIME = "taudittime";

  /** 时间戳 */
  public static final String TS = "ts";

  /** 单据号 */
  public static final String VBILLCODE = "vbillcode";

  /** 自定义项1 */
  public static final String VDEF1 = "vdef1";

  /** 自定义项10 */
  public static final String VDEF10 = "vdef10";

  /** 自定义项11 */
  public static final String VDEF11 = "vdef11";

  /** 自定义项12 */
  public static final String VDEF12 = "vdef12";

  /** 自定义项13 */
  public static final String VDEF13 = "vdef13";

  /** 自定义项14 */
  public static final String VDEF14 = "vdef14";

  /** 自定义项15 */
  public static final String VDEF15 = "vdef15";

  /** 自定义项16 */
  public static final String VDEF16 = "vdef16";

  /** 自定义项17 */
  public static final String VDEF17 = "vdef17";

  /** 自定义项18 */
  public static final String VDEF18 = "vdef18";

  /** 自定义项19 */
  public static final String VDEF19 = "vdef19";

  /** 自定义项2 */
  public static final String VDEF2 = "vdef2";

  /** 自定义项20 */
  public static final String VDEF20 = "vdef20";

  /** 自定义项3 */
  public static final String VDEF3 = "vdef3";

  /** 自定义项4 */
  public static final String VDEF4 = "vdef4";

  /** 自定义项5 */
  public static final String VDEF5 = "vdef5";

  /** 自定义项6 */
  public static final String VDEF6 = "vdef6";

  /** 自定义项7 */
  public static final String VDEF7 = "vdef7";

  /** 自定义项8 */
  public static final String VDEF8 = "vdef8";

  /** 自定义项9 */
  public static final String VDEF9 = "vdef9";
  
  /** 制单日期 */
  public static final String DMAKEDATE = "dmakedate";

  /** 备注 */
  public static final String VNOTE = "vnote";

  /** 来源类型 */
  public static final String VSRCTYPE = "vsrctype";

  /** 预订单类型编码 */
  public static final String VTRANTYPECODE = "vtrantypecode";

  /**
   * 按照默认方式创建构造子.
   * 
   * 创建日期:2010-03-18 16:00:21
   */
  public PreOrderHVO() {
    super();
  }

  public String getApprover() {
    return (String) this.getAttributeValue(PreOrderHVO.APPROVER);
  }

  public String getBillmaker() {
    return (String) this.getAttributeValue(PreOrderHVO.BILLMAKER);
  }

  public String getCchanneltypeid() {
    return (String) this.getAttributeValue(PreOrderHVO.CCHANNELTYPEID);
  }

  public String getCcustomerid() {
    return (String) this.getAttributeValue(PreOrderHVO.CCUSTOMERID);
  }

  public String getCdeptid() {
    return (String) this.getAttributeValue(PreOrderHVO.CDEPTID);
  }

  public String getCdeptvid() {
    return (String) this.getAttributeValue(PreOrderHVO.CDEPTVID);
  }

  public String getCemployeeid() {
    return (String) this.getAttributeValue(PreOrderHVO.CEMPLOYEEID);
  }

  public String getCinvoicecustid() {
    return (String) this.getAttributeValue(PreOrderHVO.CINVOICECUSTID);
  }

  public String getCorigcurrencyid() {
    return (String) this.getAttributeValue(PreOrderHVO.CORIGCURRENCYID);
  }

  public String getCpaytermid() {
    return (String) this.getAttributeValue(PreOrderHVO.CPAYTERMID);
  }

  public String getCpreorderid() {
    return (String) this.getAttributeValue(PreOrderHVO.CPREORDERID);
  }

  public UFDateTime getCreationtime() {
    return (UFDateTime) this.getAttributeValue(PreOrderHVO.CREATIONTIME);
  }

  public String getCreator() {
    return (String) this.getAttributeValue(PreOrderHVO.CREATOR);
  }

  public String getCtransporttypeid() {
    return (String) this.getAttributeValue(PreOrderHVO.CTRANSPORTTYPEID);
  }

  public String getCtrantypeid() {
    return (String) this.getAttributeValue(PreOrderHVO.CTRANTYPEID);
  }

  public String getCweboperatorid() {
    return (String) this.getAttributeValue(PreOrderHVO.CWEBOPERATORID);
  }

  public UFDate getDabatedate() {
    return (UFDate) this.getAttributeValue(PreOrderHVO.DABATEDATE);
  }

  public UFDate getDbilldate() {
    return (UFDate) this.getAttributeValue(PreOrderHVO.DBILLDATE);
  }

  public Integer getFstatusflag() {
    return (Integer) this.getAttributeValue(PreOrderHVO.FSTATUSFLAG);
  }

  public Integer getIprintcount() {
    return (Integer) this.getAttributeValue(PreOrderHVO.IPRINTCOUNT);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("so.preorder");
    return meta;
  }

  public UFDateTime getModifiedtime() {
    return (UFDateTime) this.getAttributeValue(PreOrderHVO.MODIFIEDTIME);
  }

  public String getModifier() {
    return (String) this.getAttributeValue(PreOrderHVO.MODIFIER);
  }

  public UFDouble getNdiscountrate() {
    return (UFDouble) this.getAttributeValue(PreOrderHVO.NDISCOUNTRATE);
  }

  public UFDouble getNheadsummny() {
    return (UFDouble) this.getAttributeValue(PreOrderHVO.NHEADSUMMNY);
  }

  public UFDouble getNtotalnum() {
    return (UFDouble) this.getAttributeValue(PreOrderHVO.NTOTALNUM);
  }

  public String getPk_group() {
    return (String) this.getAttributeValue(PreOrderHVO.PK_GROUP);
  }

  public String getPk_org() {
    return (String) this.getAttributeValue(PreOrderHVO.PK_ORG);
  }

  public String getPk_org_v() {
    return (String) this.getAttributeValue(PreOrderHVO.PK_ORG_V);
  }

  public UFDate getTaudittime() {
    return (UFDate) this.getAttributeValue(PreOrderHVO.TAUDITTIME);
  }

  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(PreOrderHVO.TS);
  }

  public String getVbillcode() {
    return (String) this.getAttributeValue(PreOrderHVO.VBILLCODE);
  }

  public String getVdef1() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF1);
  }

  public String getVdef10() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF10);
  }

  public String getVdef11() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF11);
  }

  public String getVdef12() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF12);
  }

  public String getVdef13() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF13);
  }

  public String getVdef14() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF14);
  }

  public String getVdef15() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF15);
  }

  public String getVdef16() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF16);
  }

  public String getVdef17() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF17);
  }

  public String getVdef18() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF18);
  }

  public String getVdef19() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF19);
  }

  public String getVdef2() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF2);
  }

  public String getVdef20() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF20);
  }

  public String getVdef3() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF3);
  }

  public String getVdef4() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF4);
  }

  public String getVdef5() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF5);
  }

  public String getVdef6() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF6);
  }

  public String getVdef7() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF7);
  }

  public String getVdef8() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF8);
  }

  public String getVdef9() {
    return (String) this.getAttributeValue(PreOrderHVO.VDEF9);
  }

  public UFDate getDmakedate() {
    return (UFDate) this.getAttributeValue(CreditAuditHVO.DMAKEDATE);
  }

  public String getVnote() {
    return (String) this.getAttributeValue(PreOrderHVO.VNOTE);
  }

  public Integer getVsrctype() {
    return (Integer) this.getAttributeValue(PreOrderHVO.VSRCTYPE);
  }

  public String getVtrantypecode() {
    return (String) this.getAttributeValue(PreOrderHVO.VTRANTYPECODE);
  }

  public void setApprover(String approver) {
    this.setAttributeValue(PreOrderHVO.APPROVER, approver);
  }

  public void setBillmaker(String billmaker) {
    this.setAttributeValue(PreOrderHVO.BILLMAKER, billmaker);
  }

  public void setCchanneltypeid(String cchanneltypeid) {
    this.setAttributeValue(PreOrderHVO.CCHANNELTYPEID, cchanneltypeid);
  }

  public void setCcustomerid(String ccustomerid) {
    this.setAttributeValue(PreOrderHVO.CCUSTOMERID, ccustomerid);
  }

  public void setCdeptid(String cdeptid) {
    this.setAttributeValue(PreOrderHVO.CDEPTID, cdeptid);
  }

  public void setCdeptvid(String cdeptvid) {
    this.setAttributeValue(PreOrderHVO.CDEPTVID, cdeptvid);
  }

  public void setCemployeeid(String cemployeeid) {
    this.setAttributeValue(PreOrderHVO.CEMPLOYEEID, cemployeeid);
  }

  public void setCinvoicecustid(String cinvoicecustid) {
    this.setAttributeValue(PreOrderHVO.CINVOICECUSTID, cinvoicecustid);
  }

  public void setCorigcurrencyid(String corigcurrencyid) {
    this.setAttributeValue(PreOrderHVO.CORIGCURRENCYID, corigcurrencyid);
  }

  public void setCpaytermid(String cpaytermid) {
    this.setAttributeValue(PreOrderHVO.CPAYTERMID, cpaytermid);
  }

  public void setCpreorderid(String cpreorderid) {
    this.setAttributeValue(PreOrderHVO.CPREORDERID, cpreorderid);
  }

  public void setCreationtime(UFDateTime creationtime) {
    this.setAttributeValue(PreOrderHVO.CREATIONTIME, creationtime);
  }

  public void setCreator(String creator) {
    this.setAttributeValue(PreOrderHVO.CREATOR, creator);
  }

  public void setCtransporttypeid(String ctransporttypeid) {
    this.setAttributeValue(PreOrderHVO.CTRANSPORTTYPEID, ctransporttypeid);
  }

  public void setCtrantypeid(String ctrantypeid) {
    this.setAttributeValue(PreOrderHVO.CTRANTYPEID, ctrantypeid);
  }

  public void setCweboperatorid(String cweboperatorid) {
    this.setAttributeValue(PreOrderHVO.CWEBOPERATORID, cweboperatorid);
  }

  public void setDabatedate(UFDate dabatedate) {
    this.setAttributeValue(PreOrderHVO.DABATEDATE, dabatedate);
  }

  public void setDbilldate(UFDate dbilldate) {
    this.setAttributeValue(PreOrderHVO.DBILLDATE, dbilldate);
  }

  public void setFstatusflag(Integer fstatusflag) {
    this.setAttributeValue(PreOrderHVO.FSTATUSFLAG, fstatusflag);
  }

  public void setIprintcount(Integer iprintcount) {
    this.setAttributeValue(PreOrderHVO.IPRINTCOUNT, iprintcount);
  }

  public void setModifiedtime(UFDateTime modifiedtime) {
    this.setAttributeValue(PreOrderHVO.MODIFIEDTIME, modifiedtime);
  }

  public void setModifier(String modifier) {
    this.setAttributeValue(PreOrderHVO.MODIFIER, modifier);
  }

  public void setNdiscountrate(UFDouble ndiscountrate) {
    this.setAttributeValue(PreOrderHVO.NDISCOUNTRATE, ndiscountrate);
  }

  public void setNheadsummny(UFDouble nheadsummny) {
    this.setAttributeValue(PreOrderHVO.NHEADSUMMNY, nheadsummny);
  }

  public void setNtotalnum(UFDouble ntotalnum) {
    this.setAttributeValue(PreOrderHVO.NTOTALNUM, ntotalnum);
  }

  public void setPk_group(String pk_group) {
    this.setAttributeValue(PreOrderHVO.PK_GROUP, pk_group);
  }

  public void setPk_org(String pk_org) {
    this.setAttributeValue(PreOrderHVO.PK_ORG, pk_org);
  }

  public void setPk_org_v(String pk_org_v) {
    this.setAttributeValue(PreOrderHVO.PK_ORG_V, pk_org_v);
  }

  public void setTaudittime(UFDate taudittime) {
    this.setAttributeValue(PreOrderHVO.TAUDITTIME, taudittime);
  }

  public void setTs(UFDateTime ts) {
    this.setAttributeValue(PreOrderHVO.TS, ts);
  }

  public void setVbillcode(String vbillcode) {
    this.setAttributeValue(PreOrderHVO.VBILLCODE, vbillcode);
  }

  public void setVdef1(String vdef1) {
    this.setAttributeValue(PreOrderHVO.VDEF1, vdef1);
  }

  public void setVdef10(String vdef10) {
    this.setAttributeValue(PreOrderHVO.VDEF10, vdef10);
  }

  public void setVdef11(String vdef11) {
    this.setAttributeValue(PreOrderHVO.VDEF11, vdef11);
  }

  public void setVdef12(String vdef12) {
    this.setAttributeValue(PreOrderHVO.VDEF12, vdef12);
  }

  public void setVdef13(String vdef13) {
    this.setAttributeValue(PreOrderHVO.VDEF13, vdef13);
  }

  public void setVdef14(String vdef14) {
    this.setAttributeValue(PreOrderHVO.VDEF14, vdef14);
  }

  public void setVdef15(String vdef15) {
    this.setAttributeValue(PreOrderHVO.VDEF15, vdef15);
  }

  public void setVdef16(String vdef16) {
    this.setAttributeValue(PreOrderHVO.VDEF16, vdef16);
  }

  public void setVdef17(String vdef17) {
    this.setAttributeValue(PreOrderHVO.VDEF17, vdef17);
  }

  public void setVdef18(String vdef18) {
    this.setAttributeValue(PreOrderHVO.VDEF18, vdef18);
  }

  public void setVdef19(String vdef19) {
    this.setAttributeValue(PreOrderHVO.VDEF19, vdef19);
  }

  public void setVdef2(String vdef2) {
    this.setAttributeValue(PreOrderHVO.VDEF2, vdef2);
  }

  public void setVdef20(String vdef20) {
    this.setAttributeValue(PreOrderHVO.VDEF20, vdef20);
  }

  public void setVdef3(String vdef3) {
    this.setAttributeValue(PreOrderHVO.VDEF3, vdef3);
  }

  public void setVdef4(String vdef4) {
    this.setAttributeValue(PreOrderHVO.VDEF4, vdef4);
  }

  public void setVdef5(String vdef5) {
    this.setAttributeValue(PreOrderHVO.VDEF5, vdef5);
  }

  public void setVdef6(String vdef6) {
    this.setAttributeValue(PreOrderHVO.VDEF6, vdef6);
  }

  public void setVdef7(String vdef7) {
    this.setAttributeValue(PreOrderHVO.VDEF7, vdef7);
  }

  public void setVdef8(String vdef8) {
    this.setAttributeValue(PreOrderHVO.VDEF8, vdef8);
  }

  public void setVdef9(String vdef9) {
    this.setAttributeValue(PreOrderHVO.VDEF9, vdef9);
  }

  public void setVnote(String vnote) {
    this.setAttributeValue(PreOrderHVO.VNOTE, vnote);
  }

  public void setDmakedate(UFDate dmakedate) {
    this.setAttributeValue(CreditAuditHVO.DMAKEDATE, dmakedate);
  }

  public void setVsrctype(Integer vsrctype) {
    this.setAttributeValue(PreOrderHVO.VSRCTYPE, vsrctype);
  }

  public void setVtrantypecode(String vtrantypecode) {
    this.setAttributeValue(PreOrderHVO.VTRANTYPECODE, vtrantypecode);
  }

}
