/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.so.report.analy.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
import nc.vo.so.m30.entity.SaleOrderHVO;

/**
 * <b> 销售订单移动报表 分析实体</b>
 * <p>
 * 销售订单移动报表分析实体
 * </p>
 * 创建日期:2012-05-24 14:19:21
 * 
 * @author yixl
 * @version NCv61
 */

public class SaleOrderAnalyVO extends SuperVO {

  /**
   *  品牌
   */
  public static final String CBRANDID = "cbrandid";

  /**
   * 渠道类型
   */
  public static final String CCHANNELTYPEID = "cchanneltypeid";

  /**
   * 客户
   */
  public static final String CCUSTOMERID = "ccustomerid";

  /**
   * 部门
   */
  public static final String CDEPTID = "cdeptid";

  /**
   * 业务员
   */
  public static final String CEMPLOYEEID = "cemployeeid";

  /**
   * 物料
   */
  public static final String CMATERIALID = "cmaterialid";

  /**
   * 产品线
   */
  public static final String CPRODLINEID = "cprodlineid";

  /**
   * 单据日期
   */
  public static final String DBILLDATE = "dbilldate";

  /**
   * 分组字段
   */
  public static final String GROUPKEY = "groupkey";

  /**
   * 销售主数量
   */
  public static final String NNUM = "nnum";

  /**
   * 价税合计
   */
  public static final String NORIGTAXMNY = "norigtaxmny";

  /**
   * 销售主表ID
   */
  public static final String CSALEORDERID = "csaleorderid";
  
  /**
   * 原币
   */
  public static final String CORIGCURRENCYID = "corigcurrencyid";
  
  /**
   * 本币价税合计
   */
  public static final String NTAXMNY = "ntaxmny";
  
  /**
   * 集团本币价税合计
   */
  public static final String NGROUPTAXMNY = "ngrouptaxmny";
  
  /**
   * 集团
   */
  public static final String PK_GROUP = "pk_group";

  /**
   * 销售组织
   */
  public static final String PK_ORG = "pk_org";

  /**
   * 用户
   */
  public static final String PK_USER = "pk_user";
  
  /**
   * 时间戳
   */
  public static final String TS = "ts";

  /**
   * 订单号
   */
  public static final String VBILLCODE = "vbillcode";

  private static final long serialVersionUID = 1L;

  /**
   * 获取品牌
   * 
   * @return 品牌
   */
  public String getCbrandid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CBRANDID);
  }

  /**
   * 获取渠道类型
   * @return 渠道类型
   */
  public String getCchanneltypeid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CCHANNELTYPEID);
  }

  /**
   * 获取客户
   * 
   * @return 客户
   */
  public String getCcustomerid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CCUSTOMERID);
  }

  /**
   * 获取部门
   * 
   * @return 部门
   */
  public String getCdeptid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CDEPTID);
  }
  
  /**
   * 获取原币
   *
   * @return 原币
   */
  public String getCorigcurrencyid() {
    return (String) this.getAttributeValue(SaleOrderHVO.CORIGCURRENCYID);
  }
  
  /**
   * 获取业务员
   * 
   * @return 业务员
   */
  public String getCemployeeid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CEMPLOYEEID);
  }

  /**
   * 获取物料
   * 
   * @return 物料
   */
  public String getCmaterialid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CMATERIALID);
  }

  /**
   * 获取产品线
   * 
   * @return 产品线
   */
  public String getCprodlineid() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.CPRODLINEID);
  }

  /**
   * 获取单据日期
   * 
   * @return 单据日期
   */
  public UFDate getDbilldate() {
    return (UFDate) this.getAttributeValue(SaleOrderAnalyVO.DBILLDATE);
  }

  /**
   * 获取分组字段
   * 
   * @return 分组字段
   */
  public String getGroupkey() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.GROUPKEY);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("so.saleorderanaly");
    return meta;
  }

  /**
   * 获取销售主数量
   * 
   * @return 销售主数量
   */
  public UFDouble getNnum() {
    return (UFDouble) this.getAttributeValue(SaleOrderAnalyVO.NNUM);
  }

  /**
   * 获取价税合计
   * 
   * @return 价税合计
   */
  public UFDouble getNorigtaxmny() {
    return (UFDouble) this.getAttributeValue(SaleOrderAnalyVO.NORIGTAXMNY);
  }
  
  /**
   * 获取本币价税合计
   * 
   * @return 价税合计
   */
  public UFDouble getNtaxmny() {
    return (UFDouble) this.getAttributeValue(SaleOrderAnalyVO.NTAXMNY);
  }
  
  /**
   * 获取销售主表ID
   *
   * @return 销售主表ID
   */
  public String getCsaleorderid() {
    return (String) this.getAttributeValue(SaleOrderHVO.CSALEORDERID);
  }
  
  /**
   * 设置销售主表ID
   *
   * @param csaleorderid 销售主表ID
   */
  public void setCsaleorderid(String csaleorderid) {
    this.setAttributeValue(SaleOrderHVO.CSALEORDERID, csaleorderid);
  }
  
  /**
   * 获取集团本币价税合计
   * 
   * @return 价税合计
   */
  public UFDouble getNgrouptaxmny() {
    return (UFDouble) this.getAttributeValue(SaleOrderAnalyVO.NGROUPTAXMNY);
  }
  
  /**
   * 设置原币
   *
   * @param corigcurrencyid 原币
   */
  public void setCorigcurrencyid(String corigcurrencyid) {
    this.setAttributeValue(SaleOrderHVO.CORIGCURRENCYID, corigcurrencyid);
  }

  /**
   * 获取集团
   * 
   * @return 集团
   */
  public String getPk_group() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.PK_GROUP);
  }

  /**
   * 获取销售组织
   * 
   * @return 销售组织
   */
  public String getPk_org() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.PK_ORG);
  }

  /**
   * 获取用户
   * 
   * @return 用户
   */
  public String getPk_user() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.PK_USER);
  }

  /**
   * 获取时间戳
   * 
   * @return 时间戳
   */
  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(SaleOrderAnalyVO.TS);
  }

  /**
   * 获取订单号
   * 
   * @return 订单号
   */
  public String getVbillcode() {
    return (String) this.getAttributeValue(SaleOrderAnalyVO.VBILLCODE);
  }

  /**
   * 设置品牌
   * 
   * @param cbrandid 品牌
   */
  public void setCbrandid(String cbrandid) {
    this.setAttributeValue(SaleOrderAnalyVO.CBRANDID, cbrandid);
  }

  /**
   * 设置渠道类型
   * 
   * @param cchanneltypeid 渠道类型
   */
  public void setCchanneltypeid(String cchanneltypeid) {
    this.setAttributeValue(SaleOrderAnalyVO.CCHANNELTYPEID, cchanneltypeid);
  }

  /**
   * 设置客户
   * 
   * @param ccustomerid 客户
   */
  public void setCcustomerid(String ccustomerid) {
    this.setAttributeValue(SaleOrderAnalyVO.CCUSTOMERID, ccustomerid);
  }

  /**
   * 设置部门
   * 
   * @param cdeptid 部门
   */
  public void setCdeptid(String cdeptid) {
    this.setAttributeValue(SaleOrderAnalyVO.CDEPTID, cdeptid);
  }

  /**
   * 设置业务员
   * 
   * @param cemployeeid 业务员
   */
  public void setCemployeeid(String cemployeeid) {
    this.setAttributeValue(SaleOrderAnalyVO.CEMPLOYEEID, cemployeeid);
  }

  /**
   * 设置物料
   * 
   * @param cmaterialid 物料
   */
  public void setCmaterialid(String cmaterialid) {
    this.setAttributeValue(SaleOrderAnalyVO.CMATERIALID, cmaterialid);
  }

  /**
   * 设置产品线
   * 
   * @param cprodlineid 产品线
   */
  public void setCprodlineid(String cprodlineid) {
    this.setAttributeValue(SaleOrderAnalyVO.CPRODLINEID, cprodlineid);
  }

  /**
   * 设置单据日期
   * 
   * @param dbilldate 单据日期
   */
  public void setDbilldate(UFDate dbilldate) {
    this.setAttributeValue(SaleOrderAnalyVO.DBILLDATE, dbilldate);
  }

  /**
   * 设置分组字段
   * 
   * @param groupkey 分组字段
   */
  public void setGroupkey(String groupkey) {
    this.setAttributeValue(SaleOrderAnalyVO.GROUPKEY, groupkey);
  }

  /**
   * 设置销售主数量
   * 
   * @param nnum 销售主数量
   */
  public void setNnum(UFDouble nnum) {
    this.setAttributeValue(SaleOrderAnalyVO.NNUM, nnum);
  }

  /**
   * 设置价税合计
   * 
   * @param norigtaxmny 价税合计
   */
  public void setNorigtaxmny(UFDouble norigtaxmny) {
    this.setAttributeValue(SaleOrderAnalyVO.NORIGTAXMNY, norigtaxmny);
  }
  
  /**
   * 设置本币价税合计
   * 
   * @param norigtaxmny 价税合计
   */
  public void setNtaxmny(UFDouble ntaxmny) {
    this.setAttributeValue(SaleOrderAnalyVO.NTAXMNY, ntaxmny);
  }
  
  /**
   * 设置集团本币价税合计
   * 
   * @param norigtaxmny 价税合计
   */
  public void setNgrouptaxmny(UFDouble ngrouptaxmny) {
    this.setAttributeValue(SaleOrderAnalyVO.NGROUPTAXMNY, ngrouptaxmny);
  }

  /**
   * 设置集团
   * 
   * @param pk_group 集团
   */
  public void setPk_group(String pk_group) {
    this.setAttributeValue(SaleOrderAnalyVO.PK_GROUP, pk_group);
  }

  /**
   * 设置销售组织
   * 
   * @param pk_org 销售组织
   */
  public void setPk_org(String pk_org) {
    this.setAttributeValue(SaleOrderAnalyVO.PK_ORG, pk_org);
  }

  /**
   * 设置用户
   * 
   * @param pk_user 用户
   */
  public void setPk_user(String pk_user) {
    this.setAttributeValue(SaleOrderAnalyVO.PK_USER, pk_user);
  }

  /**
   * 设置时间戳
   * 
   * @param ts 时间戳
   */
  public void setTs(UFDateTime ts) {
    this.setAttributeValue(SaleOrderAnalyVO.TS, ts);
  }

  /**
   * 设置订单号
   * 
   * @param vbillcode 订单号
   */
  public void setVbillcode(String vbillcode) {
    this.setAttributeValue(SaleOrderAnalyVO.VBILLCODE, vbillcode);
  }

}
