insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000004796',1,-1,null,null,0,1,null,-1,'N',null,-1,'csalebillid',null,'N',1,'N','N',null,0,'csalebillid','so.arsub_detail.csalebillid',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',0,3,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000004797',1,-1,null,null,0,1,null,-1,'N',null,-1,'carsubdetailid',null,'N',1,'N','N',null,0,'carsubdetailid','so.arsub_detail.carsubdetailid',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',0,1,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000004798',1,-1,null,null,0,1,null,-1,'N',null,-1,'carsubbid',null,'N',1,'N','N',null,0,'carsubbid','so.arsub_detail.carsubbid',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',0,2,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000004799',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','so.arsub_detail.ts',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',0,9,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000479A',1,-1,null,null,0,1,null,-1,'N',null,-1,'dsubdate',null,'N',1,'N','Y',null,0,'dsubdate','so.arsub_detail.dsubdate',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',1,7,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000479B',1,-1,null,null,0,1,null,-1,'N',null,-1,'ndetailsubmny',null,'N',1,'N','Y',null,0,'ndetailsubmny','so.arsub_detail.ndetailsubmny',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',1,6,'arsub_detail','冲抵明细实体',1,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000479C',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',null,'N',1,'N','Y',null,0,'vbillcode','so.arsub_detail.vbillcode',null,'N',0,null,'1002Z810000000004795',null,1,null,null,null,'N',1,5,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000479D',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbilltypecode',null,'N',1,'N','Y',null,0,'cbilltypecode','so.arsub_detail.cbilltypecode',null,'N',0,null,'1002Z810000000004795',null,1,'影响因素交 易类型,code=N',null,null,'N',1,4,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000479E',1,-1,null,null,0,1,null,-1,'N',null,-1,'csuboperator',null,'N',1,'N','Y',null,0,'csuboperator','so.arsub_detail.csuboperator',null,'N',0,null,'1002Z810000000004795',null,1,'人员,code=N',null,null,'N',1,8,'arsub_detail','冲抵明细实体',0,'2013-12-12 13:24:00','N',null,null,null,1,1,'N',1,null,100,null)
go

