insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000018333',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cmffileid',null,'N',1,'Y','N',null,0,'cmffileid','so.saleinvoice_b.cmffileid',null,'N',0,null,'1002Z81000000001BSOI',null,1,'特征码档案,code=N',null,null,'N',0,4,'saleinvoice_b','销售发票表体',0,'2015-03-25 20:06:16','N',null,null,null,0,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000IAYB',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccustmaterialid',0,'N',1,'N','N',null,0,'ccustmaterialid','so.saleinvoice_b.ccustmaterialid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',0,1,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000IAYC',1,-1,null,null,0,0,null,-1,'N','ccustmaterialid',-1,'ccustmaterialid.name',0,'N',1,'N','N',null,0,'name','uapbd.custmaterial.name',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',0,2,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:07','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOL',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.saleinvoice.pk_org','pk_org_v=pk_vid','N',1,null,'1002Z81000000001BSOI','@@@@',0,'财务组织',null,null,'N',0,3,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',0,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOM',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','so.saleinvoice.pk_org_v',null,'N',1,null,'1002Z81000000001BSOI','@@@@',0,null,'1400605010006',null,'N',0,4,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',0,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSON',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','Y',null,0,'ctrantypeid','so.saleinvoice.ctrantypeid','vtrantypecode=pk_billtypecode','N',1,null,'1002Z81000000001BSOI','@@@@',0,'影响因素交 易类型',null,null,'N',1,5,'saleinvoice_h','saleinvoice_h',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','so.saleinvoice.vbillcode',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'UC000-0000981',null,'N',1,7,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOR',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.saleinvoice.dbilldate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'UC000-0001902',null,'N',1,9,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOS',1,-1,null,null,0,1,'ccustbankaccid->getcolvalue2( bd_custbank, pk_bankaccbas,pk_cust ,cinvoicecustid ,isdefault , "Y")',-1,'Y',null,-1,'cinvoicecustid',0,'N',1,'Y','Y',null,0,'cinvoicecustid','so.saleinvoice.cinvoicecustid','vprintcustname=shortname','N',1,null,'1002Z81000000001BSOI','@@@@',0,null,'UC000-0001595',null,'N',1,10,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOT',1,-1,null,null,0,0,null,-1,'N','cinvoicecustid',-1,'cinvoicecustid.tel1',0,'N',1,'N','Y',null,0,'tel1','uap.customer.tel1',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'1400605010014',null,'N',1,11,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOU',1,-1,null,null,0,1,null,-1,'N',null,-1,'vprintcustname',0,'N',1,'N','Y',null,0,'vprintcustname','so.saleinvoice.vprintcustname',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,12,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOV',1,-1,null,null,0,0,null,-1,'N','cinvoicecustid',-1,'cinvoicecustid.taxpayerid',0,'N',1,'N','Y',null,0,'taxpayerid','uap.customer.taxpayerid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'1400605010013',null,'N',1,13,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOW',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustbankid',0,'N',1,'N','Y',null,0,'ccustbankid','so.saleinvoice.ccustbankid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,14,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOX',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustbankaccid',0,'N',1,'N','Y',null,0,'ccustbankaccid','so.saleinvoice.ccustbankaccid','ccustbankid=pk_bankaccbas.pk_bankdoc','N',0,null,'1002Z81000000001BSOI','@@@@',0,'客商银行账户,code=Y','1400605010005',null,'N',1,15,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSOY',1,-1,null,null,0,0,null,-1,'N','cinvoicecustid',-1,'cinvoicecustid.corpaddress.detailinfo',0,'N',1,'N','Y',null,0,'corpaddress.detailinfo','uap.address.detailinfo',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'1400605010020',null,'N',1,16,'saleinvoice_h','saleinvoice_h',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSP4',1,-1,null,null,0,1,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.saleinvoice.corigcurrencyid',null,'N',1,null,'1002Z81000000001BSOI','@@@@',0,null,'UC000-0001755',null,'N',1,22,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSP5',1,-1,null,null,0,1,null,-1,'N',null,-1,'nexchangerate',0,'N',1,'N','Y',null,0,'nexchangerate','so.saleinvoice.nexchangerate',null,'N',1,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,23,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSP9',1,-1,null,null,0,1,null,-1,'N',null,-1,'nhvoicedisrate',0,'N',1,'N','Y',null,0,'nhvoicedisrate','so.saleinvoice.nhvoicedisrate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,27,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPB',1,2,null,null,0,0,null,-1,'N',null,20,'ntotalmny',0,'N',1,'N','Y','ntotalmny->add( ntotalorigmny,ntotalorigsubmny )',0,null,null,null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,'1400605010009',null,'N',1,29,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPC',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalorigsubmny',0,'N',1,'N','Y',null,0,'ntotalorigsubmny','so.saleinvoice.ntotalorigsubmny',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,'8,,,,,,Y',null,null,'N',1,30,'saleinvoice_h','saleinvoice_h',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPD',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigmny',0,'N',1,'N','Y',null,0,'ntotalorigmny','so.saleinvoice.ntotalorigmny',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,'8,,,,,,Y',null,null,'N',1,31,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPN',1,-1,null,'0',0,0,null,-1,'N',null,-1,'fopposeflag',0,'N',1,'N','Y',null,0,'fopposeflag','so.saleinvoice.fopposeflag',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,41,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.saleinvoice.vnote',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,44,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSPR',1,-1,null,'1',0,0,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','Y',null,0,'fstatusflag','so.saleinvoice.fstatusflag',null,'N',0,null,'1002Z81000000001BSOI','@@@@',0,null,null,null,'N',1,45,'saleinvoice_h','销售发票表头',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,1,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQF',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.saleinvoice_b.pk_group',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'集团,code=N',null,null,'N',0,2,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',0,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.saleinvoice_b.pk_org',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'财务组织,code=N',null,null,'N',0,3,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',0,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQI',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.saleinvoice_b.crowno',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,0,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQK',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmarbascalssid',0,'N',1,'N','N',null,0,'cmarbascalssid','so.saleinvoice_b.cmarbascalssid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'物料基本分类,code=N',null,null,'N',0,7,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQL',1,-1,null,null,0,1,null,-1,'Y',null,-1,'cmaterialvid',0,'N',1,'Y','Y',null,0,'cmaterialvid','so.saleinvoice_b.cmaterialvid','cmaterialid=pk_source,cunitid=pk_measdoc,bdiscountflag=discountflag,blaborflag=fee,cprodlineid=pk_prodline','N',1,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,3,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQM',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,4,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQN',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,5,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQO',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,6,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQP',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','so.saleinvoice_b.cvendorid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'供应商档案,code=N',null,null,'N',0,12,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','so.saleinvoice_b.cprojectid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'项目,code=N,nl=N',null,null,'N',0,13,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','so.saleinvoice_b.cproductorid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,14,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQS',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','so.saleinvoice_b.castunitid',null,'N',1,null,'1002Z81000000001BSOI','@@@@',1,'计量单位,code=N,type=-1',null,null,'N',1,7,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQT',1,-1,null,null,0,1,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','so.saleinvoice_b.nastnum',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,8,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQU',1,-1,null,null,0,1,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','so.saleinvoice_b.cunitid',null,'N',1,null,'1002Z81000000001BSOI','@@@@',1,'计量单位,code=N,type=-1',null,null,'N',1,9,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQV',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.saleinvoice_b.nnum',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,10,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','Y',null,0,'vchangerate','so.saleinvoice_b.vchangerate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,11,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSQX',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqtunitid',0,'N',1,'N','N',null,0,'cqtunitid','so.saleinvoice_b.cqtunitid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'计量单位,code=N,type=-1',null,null,'N',0,20,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSR0',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctaxcodeid',0,'N',1,'N','N',null,0,'ctaxcodeid','so.saleinvoice_b.ctaxcodeid',null,'N',1,null,'1002Z81000000001BSOI','@@@@',1,'税码税率',null,null,'N',0,23,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSR1',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntaxrate',0,'N',1,'N','Y',null,0,'ntaxrate','so.saleinvoice_b.ntaxrate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,12,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSR7',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorigtaxprice',0,'N',1,'N','Y',null,0,'nqtorigtaxprice','so.saleinvoice_b.nqtorigtaxprice',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,13,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSR8',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorigprice',0,'N',1,'N','Y',null,0,'nqtorigprice','so.saleinvoice_b.nqtorigprice',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,14,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSR9',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorigtaxnetprc',0,'N',1,'N','Y',null,0,'nqtorigtaxnetprc','so.saleinvoice_b.nqtorigtaxnetprc',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,15,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRA',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorignetprice',0,'N',1,'N','Y',null,0,'nqtorignetprice','so.saleinvoice_b.nqtorignetprice',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,16,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRB',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntax',0,'N',1,'N','Y',null,0,'ntax','so.saleinvoice_b.ntax',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,17,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRD',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigmny',0,'N',1,'N','Y',null,0,'norigmny','so.saleinvoice_b.norigmny',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,18,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRE',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigtaxmny',0,'N',1,'N','Y',null,0,'norigtaxmny','so.saleinvoice_b.norigtaxmny',null,'N',1,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,19,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRF',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigdiscount',0,'N',1,'N','Y',null,0,'norigdiscount','so.saleinvoice_b.norigdiscount',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,20,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRI',1,-1,null,null,0,1,null,-1,'N',null,-1,'blargessflag',0,'N',1,'N','Y',null,0,'blargessflag','so.saleinvoice_b.blargessflag',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,'UC000-0003895',null,'N',1,21,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRL',1,-1,null,null,0,0,null,-1,'N',null,-1,'ndiscountrate',0,'N',1,'N','Y',null,0,'ndiscountrate','so.saleinvoice_b.ndiscountrate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,22,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRM',1,-1,null,null,0,0,null,-1,'N',null,-1,'nitemdiscountrate',0,'N',1,'N','Y',null,0,'nitemdiscountrate','so.saleinvoice_b.nitemdiscountrate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,'1400605010018',null,'N',1,23,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRN',1,-1,null,null,0,0,null,-1,'N',null,-1,'ninvoicedisrate',0,'N',1,'N','Y',null,0,'ninvoicedisrate','so.saleinvoice_b.ninvoicedisrate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,24,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSRZ',1,2,null,null,0,0,null,-1,'N',null,20,'nbforigsubmny',0,'N',1,'N','Y','nbforigsubmny->add( norigtaxmny,norigsubmny )',0,null,null,null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,'1400605010010',null,'N',1,25,'saleinvoice_b','销售发票表体',1,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSS0',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigsubmny',0,'N',1,'N','Y',null,0,'norigsubmny','so.saleinvoice_b.norigsubmny',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'8,-100000000000000000000.00000000,100000000000000000000.00000000',null,null,'N',1,26,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSS5',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfirsttype',0,'N',1,'N','N',null,0,'vfirsttype','so.saleinvoice_b.vfirsttype',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'影响因素单据类型,code=N,type=-1',null,null,'N',0,65,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,65)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSS7',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfirsttrantype',0,'N',1,'N','N',null,0,'vfirsttrantype','so.saleinvoice_b.vfirsttrantype',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'影响因素交 易类型,code=N','1400605010003',null,'N',0,67,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSB',1,-1,null,null,0,0,null,-1,'N',null,-1,'vsrctype',0,'N',1,'N','N',null,0,'vsrctype','so.saleinvoice_b.vsrctype',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'影响因素单据类型,code=N,type=-1',null,null,'N',0,71,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSD',1,-1,null,null,0,0,null,-1,'N',null,-1,'vsrctrantype',0,'N',1,'N','N',null,0,'vsrctrantype','so.saleinvoice_b.vsrctrantype',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'影响因素交 易类型,code=N','1400605010002',null,'N',0,73,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,73)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSI',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprofitcenterid',0,'N',1,'N','N',null,0,'cprofitcenterid','so.saleinvoice_b.cprofitcenterid','cprofitcentervid=pk_vid','N',0,null,'1002Z81000000001BSOI','@@@@',1,'利润中心,code=N,type=-1','1400605010011',null,'N',0,78,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,78)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprofitcentervid',0,'N',1,'N','N',null,0,'cprofitcentervid','so.saleinvoice_b.cprofitcentervid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'利润中心版本,code=N,type=-1','1400605010017',null,'N',0,79,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,79)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSK',1,-1,null,null,0,0,null,-1,'N',null,-1,'carorgid',0,'N',1,'N','N',null,0,'carorgid','so.saleinvoice_b.carorgid','carorgvid=pk_vid','N',0,null,'1002Z81000000001BSOI','@@@@',1,'财务组织,code=N,type=-1','1400605010021',null,'N',0,80,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,80)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSL',1,-1,null,null,0,1,null,-1,'N',null,-1,'carorgvid',0,'N',1,'N','N',null,0,'carorgvid','so.saleinvoice_b.carorgvid','carorgid=pk_financeorg','N',0,null,'1002Z81000000001BSOI','@@@@',1,'财务组织版本,code=N','1400605010004',null,'N',0,81,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,81)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSM',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cordercustid',0,'N',1,'Y','Y',null,0,'cordercustid','so.saleinvoice_b.cordercustid','bfreecustflag=isfreecust','N',0,null,'1002Z81000000001BSOI','@@@@',1,'客户档案,code=N,type=-1',null,null,'N',1,27,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSO',1,-1,null,null,0,0,null,-1,'N',null,-1,'cfreecustid',0,'N',1,'N','N',null,0,'cfreecustid','so.saleinvoice_b.cfreecustid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'散户,code=N,type=-1',null,null,'N',0,84,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,84)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSP',1,-1,null,null,0,0,null,-1,'Y',null,-1,'creceivecustid',0,'N',1,'Y','Y',null,0,'creceivecustid','so.saleinvoice_b.creceivecustid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'客户档案,code=N,type=-1',null,null,'N',1,28,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'creceiveaddrid',0,'N',1,'N','N','formataddress(creceiveaddrid_ID)',0,'creceiveaddrid','so.saleinvoice_b.creceiveaddrid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'客户收货地址,code=N',null,null,'N',0,86,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,86)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSR',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctransporttypeid',0,'N',1,'N','N',null,0,'ctransporttypeid','so.saleinvoice_b.ctransporttypeid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'运输方式,code=N,type=-1',null,null,'N',0,87,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,87)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSS',1,-1,null,null,0,0,'rowcount->getrowcount("bd_psnjob","pk_psndoc" ,cemployeeid_ID,"pk_org",csaleorgid_ID);cdeptid_ID->iif(rowcount==1,getcolvalue2(bd_psnjob ,pk_dept ,pk_psndoc , cemployeeid_ID ,pk_org ,csaleorgid_ID),cdeptid_ID);cdeptid->iif(rowcount==1,getcolvalue(org_dept,name,pk_dept ,cdeptid_ID),cdeptid);cdeptvid_ID->iif(rowcount==1,getcolvalue(org_dept,pk_vid,pk_dept ,cdeptid_ID),cdeptvid_ID);cdeptvid->iif(rowcount==1,getcolvalue(org_dept_v,name,pk_vid ,cdeptvid_ID),cdeptvid)',-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','so.saleinvoice_b.cemployeeid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'人员,code=N,type=-1',null,null,'N',1,29,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSST',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','N',null,0,'cdeptid','so.saleinvoice_b.cdeptid','cdeptvid=pk_vid','N',0,null,'1002Z81000000001BSOI','@@@@',1,'部门,code=N,type=-1','1400605010012',null,'N',0,90,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,90)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSU',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptvid',0,'N',1,'N','Y',null,0,'cdeptvid','so.saleinvoice_b.cdeptvid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'部门版本,code=N','UC000-0004133',null,'N',1,30,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSV',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorgid',0,'N',1,'N','N',null,0,'csaleorgid','so.saleinvoice_b.csaleorgid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'销售组织,code=N,type=-1','1400605010007',null,'N',0,92,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,92)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSW',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorgvid',0,'N',1,'N','Y',null,0,'csaleorgvid','so.saleinvoice_b.csaleorgvid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'销售组织版本,code=N','UC000-0004128',null,'N',1,31,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSX',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendstockorgid',0,'N',1,'N','N',null,0,'csendstockorgid','so.saleinvoice_b.csendstockorgid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'库存组织,code=N,type=-1','1400605010001',null,'N',0,94,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,94)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSY',1,-1,null,null,0,0,null,-1,'N',null,-1,'csendstockorgvid',0,'N',1,'N','Y',null,0,'csendstockorgvid','so.saleinvoice_b.csendstockorgvid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'库存组织版本,code=N','UC000-0001825',null,'N',1,32,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSSZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendstordocid',0,'N',1,'N','Y',null,0,'csendstordocid','so.saleinvoice_b.csendstordocid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'仓库,code=N,type=-1',null,null,'N',1,33,'saleinvoice_b','saleinvoice_b',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BST0',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','N',null,0,'cprodlineid','so.saleinvoice_b.cprodlineid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'产品线,code=N,type=-1',null,null,'N',0,97,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,97)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BST1',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccostsubjid',0,'N',1,'N','N',null,0,'ccostsubjid','so.saleinvoice_b.ccostsubjid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'收支项目,code=N,type=-1',null,null,'N',0,98,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,98)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BST5',1,-1,null,null,0,0,null,-1,'N',null,-1,'cvmivenderid',0,'N',1,'N','N',null,0,'cvmivenderid','so.saleinvoice_b.cvmivenderid',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,'供应商档案,code=N',null,null,'N',0,102,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,0,1,'N',1,null,100,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSTC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vrownote',0,'N',1,'N','Y',null,0,'vrownote','so.saleinvoice_b.vrownote',null,'N',0,null,'1002Z81000000001BSOI','@@@@',1,null,null,null,'N',1,34,'saleinvoice_b','销售发票表体',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUA',1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','so.saleinvoice.billmaker',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,101,'saleinvoicetail1','saleinvoicetail1',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUB',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','so.saleinvoice.creator',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,101,'saleinvoicetail2','saleinvoicetail2',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUC',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','so.saleinvoice.creationtime',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,102,'saleinvoicetail2','saleinvoicetail2',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUD',1,-1,null,null,0,1,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','so.saleinvoice.dmakedate',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,102,'saleinvoicetail1','saleinvoicetail1',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUE',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','so.saleinvoice.modifier',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,103,'saleinvoicetail2','saleinvoicetail2',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,103)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUF',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','so.saleinvoice.approver',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,103,'saleinvoicetail1','saleinvoicetail1',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,103)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUG',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','so.saleinvoice.modifiedtime',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,null,null,'N',1,104,'saleinvoicetail2','saleinvoicetail2',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,104)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BSUH',1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','so.saleinvoice.taudittime',null,'N',0,null,'1002Z81000000001BSOI','@@@@',2,null,'1400603010095',null,'N',1,104,'saleinvoicetail1','saleinvoicetail1',0,'2012-12-12 15:52:06','N',null,null,null,1,1,'N',1,null,1,104)
go

