/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.so.report.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;
import nc.vo.bank_cvp.type.IType;

/**
 * 销售订单毛利分析汇总规则字段名枚举
 * 
 * @since 6.0
 * @version 2011-5-10 下午12:58:20
 * @author 么贵敬
 */
public class SumPara extends MDEnum {

  /** 客户名称 */
  public static final SumPara CCUSTOMERID = MDEnum.valueOf(SumPara.class,
      "ccustomerid");

  /** 物料 */
  public static final SumPara CMATERIALID = MDEnum.valueOf(SumPara.class,
      "cmaterialid");

  public SumPara(IEnumValue enumvalue) {
    super(enumvalue);
  }

  @Override
  public int getReturnType() {
    return IType.STRING;
  }

}
