insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523N',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbrandid',0,'N',1,'N','Y',null,0,'cbrandid','so.saleorderanaly.cbrandid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'品牌档案,code=N',null,null,'N',1,11,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523O',1,-1,null,null,0,1,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','Y',null,0,'cchanneltypeid','so.saleorderanaly.cchanneltypeid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'渠道类型,code=N',null,null,'N',1,8,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523P',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','so.saleorderanaly.pk_org',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'销售组织,code=N',null,null,'N',1,3,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','Y',null,0,'cmaterialid','so.saleorderanaly.cmaterialid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'物料（多版本）,code=N',null,null,'N',1,9,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523R',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.saleorderanaly.dbilldate',null,'N',0,null,'1005Z81000000000523M','@@@@',1,null,null,null,'N',1,2,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523S',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.saleorderanaly.cprodlineid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'产品线,code=N',null,null,'N',1,10,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523T',1,-1,null,null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','so.saleorderanaly.cemployeeid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'人员,code=N',null,null,'N',1,7,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523U',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','Y',null,0,'cdeptid','so.saleorderanaly.cdeptid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'部门,code=N',null,null,'N',1,6,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523V',1,-1,null,'H01,00011110000000004W35',0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','Y',null,0,'pk_group','so.saleorderanaly.pk_group',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'集团,code=N',null,null,'N',1,1,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523W',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.saleorderanaly.nnum',null,'N',0,null,'1005Z81000000000523M','@@@@',1,null,null,null,'N',1,12,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523X',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',null,0,'ccustomerid','so.saleorderanaly.ccustomerid',null,'N',0,null,'1005Z81000000000523M','@@@@',1,'客户档案,code=N',null,null,'N',1,5,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigtaxmny',0,'N',1,'N','Y',null,0,'norigtaxmny','so.saleorderanaly.norigtaxmny',null,'N',0,null,'1005Z81000000000523M','@@@@',1,null,null,null,'N',1,13,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000523Z',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.saleorderanaly.vbillcode',null,'N',0,null,'1005Z81000000000523M','@@@@',1,null,null,null,'N',1,4,'saleorderanaly','销售订单移动报表分析实体',0,'2012-06-25 09:55:47','N',null,null,null,1,1,'N',1,null,100,null)
go

