insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001KLT8',1,-1,null,null,0,1,null,-1,'N',null,-1,'csaleorderid',0,'N',1,'N','Y',null,0,'csaleorderid','so.saleorderanaly.csaleorderid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,11,'head','head',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001KLT9',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntaxmny',0,'N',1,'N','Y',null,0,'ntaxmny','so.saleorderanaly.ntaxmny',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,12,'head','head',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001KLTA',1,-1,null,null,0,1,null,-1,'N',null,-1,'ngrouptaxmny',0,'N',1,'N','Y',null,0,'ngrouptaxmny','so.saleorderanaly.ngrouptaxmny',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,13,'head','head',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXN',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.saleorderanaly.cprodlineid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,7,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXO',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.saleorderanaly.nnum',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,9,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXP',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','so.saleorderanaly.pk_org',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,1,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigtaxmny',0,'N',1,'N','Y',null,0,'norigtaxmny','so.saleorderanaly.norigtaxmny',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,10,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXR',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.saleorderanaly.vbillcode',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,2,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXS',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','Y',null,0,'cmaterialid','so.saleorderanaly.cmaterialid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,6,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXT',1,-1,null,null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','so.saleorderanaly.cemployeeid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,4,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXU',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbrandid',0,'N',1,'N','Y',null,0,'cbrandid','so.saleorderanaly.cbrandid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,8,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXV',1,-1,null,null,0,1,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','Y',null,0,'cchanneltypeid','so.saleorderanaly.cchanneltypeid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,5,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000005MXW',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',null,0,'ccustomerid','so.saleorderanaly.ccustomerid',null,'N',0,null,'1005Z810000000005MXM','@@@@',0,null,null,null,'N',1,3,'head','表头',0,'2012-08-16 09:41:48','N',null,null,null,1,1,'N',1,null,1,null)
go

