insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KX8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_returnassign',0,'N',1,'N','N',null,0,'pk_returnassign','so.returnassign.pk_returnassign',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',0,1,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KX9',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.returnassign.pk_group',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,'集团,code=N,type=0',null,null,'N',0,2,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,0,1,'N',0,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXA',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_saleorg',0,'N',1,'N','N',null,0,'pk_saleorg','so.returnassign.pk_saleorg',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,'销售组织,code=N,type=0',null,null,'N',0,3,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXB',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_productline',0,'N',1,'N','Y',null,0,'pk_productline','so.returnassign.pk_productline',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,4,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXC',1,-1,null,null,0,0,null,-1,'N','pk_productline',-1,'pk_productline.name',0,'N',1,'N','Y',null,0,'name','uap.prodline.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,5,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_customer',0,'N',1,'N','Y',null,0,'pk_customer','so.returnassign.pk_customer',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,16,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXE',1,-1,null,null,0,0,null,-1,'N','pk_customer',-1,'pk_customer.name',0,'N',1,'N','Y',null,0,'name','uap.customer.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,17,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_custclass',0,'N',1,'N','Y',null,0,'pk_custclass','so.returnassign.pk_custclass',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,12,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXG',1,-1,null,null,0,0,null,-1,'N','pk_custclass',-1,'pk_custclass.name',0,'N',1,'N','Y',null,0,'name','uap.custclass.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,13,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXH',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_custsaleclass',0,'N',1,'N','Y',null,0,'pk_custsaleclass','so.returnassign.pk_custsaleclass',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,'客户销售分类',null,null,'N',1,14,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXI',1,-1,'客户销售分类名称',null,0,0,null,-1,'N','pk_custsaleclass',-1,'pk_custsaleclass.name',0,'N',1,'N','Y',null,0,'name','uap.custsaleclass.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,'140060801080003',null,'N',1,15,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_material',0,'N',1,'N','Y',null,0,'pk_material','so.returnassign.pk_material',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,10,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXL',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_marbasclass',0,'N',1,'N','Y',null,0,'pk_marbasclass','so.returnassign.pk_marbasclass',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,6,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXM',1,-1,null,null,0,0,null,-1,'N','pk_marbasclass',-1,'pk_marbasclass.name',0,'N',1,'N','Y',null,0,'name','uap.marbasclass.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,7,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXN',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_marsaleclass',0,'N',1,'N','Y',null,0,'pk_marsaleclass','so.returnassign.pk_marsaleclass',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,'物料销售分类',null,null,'N',1,8,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXO',1,-1,'物料销售分类名称',null,0,0,null,-1,'N','pk_marsaleclass',-1,'pk_marsaleclass.name',0,'N',1,'N','Y',null,0,'name','uap.marsaleclass.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,'140060801080001',null,'N',1,9,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003KXS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.returnassign.ts',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',0,21,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000079MN',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_returnpolicy',null,'N',1,'N','Y',null,0,'pk_returnpolicy','so.returnassign.pk_returnpolicy',null,'N',1,null,'1001Z810000000003KX7',null,1,'退货政策设置',null,null,'N',1,18,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000079MR',1,-1,'退货政策表述',null,0,0,null,-1,'N','pk_returnpolicy',-1,'pk_returnpolicy.vpolicydetail',0,'N',1,'N','Y',null,0,'vpolicydetail','so.returnpolicy.vpolicydetail',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,'140060801080002',null,'N',1,20,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000079MS',1,-1,null,null,0,0,null,-1,'N','pk_returnpolicy',-1,'pk_returnpolicy.vpolicyname',0,'N',1,'N','Y',null,0,'vpolicyname','so.returnpolicy.vpolicyname',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,19,'returnassign','returnassign',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000014DW0',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z810000000003KX7','@@@@',1,null,null,null,'N',1,11,'returnassign','退货政策分配',0,'2015-07-02 20:52:09','N',null,null,null,1,1,'N',1,null,100,11)
go

