insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002DNM',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','N',null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',0,7,'pk_tranmatrel_b','pk_tranmatrel_b',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLM',1,-1,null,null,0,1,null,-1,'N',null,-1,'exclude',0,'N',1,'N','Y',null,0,'exclude','so.so_tranmatrel_b.exclude',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',1,12,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLN',1,-1,null,null,0,1,null,-1,'N',null,-1,'trantype',0,'N',1,'N','Y',null,0,'trantype','so.so_tranmatrel_b.trantype',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',1,3,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLO',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialbaseclass',0,'N',1,'N','Y',null,0,'pk_materialbaseclass','so.so_tranmatrel_b.pk_materialbaseclass',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,'物料基本分类,code=N',null,null,'N',1,4,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLP',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','so.so_tranmatrel.pk_org_v',null,'N',1,null,'1002Z81000000000OMLL','@@@@',0,'销售组织版本',null,null,'N',0,3,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLQ',1,-1,null,'false',0,1,null,-1,'N',null,-1,'applylower',0,'N',1,'N','Y',null,0,'applylower','so.so_tranmatrel.applylower',null,'N',1,null,'1002Z81000000000OMLL','@@@@',0,null,null,null,'N',1,6,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_material',0,'N',1,'N','N',null,0,'pk_material','so.so_tranmatrel_b.pk_material',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',0,6,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.so_tranmatrel_b.vnote',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',1,13,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLT',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_tranmatrel_b.pk_org',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',0,2,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLU',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_tranmatrel_b',0,'N',1,'N','N',null,0,'pk_tranmatrel_b','so.so_tranmatrel_b.pk_tranmatrel_b',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',0,1,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLV',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_material_v',0,'N',1,'N','Y',null,0,'pk_material_v','so.so_tranmatrel_b.pk_material_v','pk_material=pk_source','N',0,null,'1002Z81000000000OMLL','@@@@',1,'物料（多版本）','UC000-0002911',null,'N',1,8,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLW',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_tranmatrel.ts',null,'N',0,null,'1002Z81000000000OMLL','@@@@',0,null,null,null,'N',0,7,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLX',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_tranmatrel',0,'N',1,'N','N',null,0,'pk_tranmatrel','so.so_tranmatrel.pk_tranmatrel',null,'N',0,null,'1002Z81000000000OMLL','@@@@',0,null,null,null,'N',0,1,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLY',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_tranmatrel_b.ts',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',0,14,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'allowsale',0,'N',1,'N','Y',null,0,'allowsale','so.so_tranmatrel.allowsale',null,'N',1,null,'1002Z81000000000OMLL','@@@@',0,null,'1400601040004',null,'N',1,5,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMM0',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_tranmatrel.pk_group',null,'N',1,null,'1002Z81000000000OMLL','@@@@',0,null,null,null,'N',0,4,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMM1',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialsaleclass',0,'N',1,'N','Y',null,0,'pk_materialsaleclass','so.so_tranmatrel_b.pk_materialsaleclass',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,'物料销售分类,code=N',null,null,'N',1,5,'pk_tranmatrel_b','订单类型物料关系子实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMM2',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_tranmatrel.pk_org',null,'N',1,null,'1002Z81000000000OMLL','@@@@',0,'销售组织',null,null,'N',0,2,'so_tranmatrel','订单类型物料关系主实体',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMM',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',1,10,'pk_tranmatrel_b','pk_tranmatrel_b',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMN',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',1,9,'pk_tranmatrel_b','pk_tranmatrel_b',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMO',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,null,null,null,'N',1,11,'pk_tranmatrel_b','pk_tranmatrel_b',0,'2011-10-25 10:11:50','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001807',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_tranmatrel_b.pk_group',null,'N',0,null,'1002Z81000000000OMLL','@@@@',1,'集团,code=N',null,null,'N',0,15,'pk_tranmatrel_b','pk_tranmatrel_b',0,'2011-10-25 10:11:50','N',null,null,null,0,1,'N',0,null,100,null)
go

