insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003K3R',1,-1,null,null,0,0,null,-1,'N',null,-1,'cffileid',0,'N',1,'N','N',null,0,'cffileid','ic.OnhandDimVO.cffileid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,39,'OnhandDimVO','OnhandDimVO',0,'2015-03-31 18:50:24','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_onhanddim',0,'N',1,'N','N',null,0,'pk_onhanddim','ic.OnhandDimVO.pk_onhanddim',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,1,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL1',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','ic.OnhandDimVO.pk_group',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,2,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','ic.OnhandDimVO.pk_org',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,3,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL3',1,0,'行号',null,0,1,null,-1,'N',null,20,'crowno',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,'1400603010184',null,'N',1,4,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL4',1,-1,null,null,0,1,null,-1,'N',null,-1,'clocationid',0,'N',1,'N','N',null,0,'clocationid','ic.OnhandDimVO.clocationid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,5,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL5',1,-1,null,null,0,0,null,13,'N',null,-1,'cwarehouseid',0,'N',1,'N','Y',null,0,'cwarehouseid','ic.OnhandDimVO.cwarehouseid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,6,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL6',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','Y',null,0,'cmaterialvid','ic.OnhandDimVO.cmaterialvid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'物料（多版本）,code=Y,dpc=SCMDefault',null,null,'N',1,7,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL7',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialoid',0,'N',1,'N','N',null,0,'cmaterialoid','ic.OnhandDimVO.cmaterialoid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'物料档案,dpc=SCMDefault',null,null,'N',0,8,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL8',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',1,9,'OnhandDimVO','OnhandDimVO',0,'2015-03-31 18:50:24','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VL9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_batchcode',0,'N',1,'N','N',null,0,'pk_batchcode','ic.OnhandDimVO.pk_batchcode',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,10,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbatchcode',0,'N',1,'N','N',null,0,'vbatchcode','ic.OnhandDimVO.vbatchcode',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,11,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','N',null,0,'vchangerate','ic.OnhandDimVO.vchangerate',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,12,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvmivenderid',0,'N',1,'N','N',null,0,'cvmivenderid','ic.OnhandDimVO.cvmivenderid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,13,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLD',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctplcustomerid',0,'N',1,'N','N',null,0,'ctplcustomerid','ic.OnhandDimVO.ctplcustomerid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,14,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLE',1,-1,null,null,0,1,null,-1,'N',null,-1,'cstateid',0,'N',1,'N','N',null,0,'cstateid','ic.OnhandDimVO.cstateid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,15,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLF',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','ic.OnhandDimVO.cvendorid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,16,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLG',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','ic.OnhandDimVO.cprojectid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,17,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLH',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','ic.OnhandDimVO.cproductorid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,18,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLI',1,-1,null,null,0,1,null,-1,'N',null,-1,'casscustid',0,'N',1,'N','N',null,0,'casscustid','ic.OnhandDimVO.casscustid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,19,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','N',null,0,'vfree1','ic.OnhandDimVO.vfree1',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,20,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','N',null,0,'vfree2','ic.OnhandDimVO.vfree2',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,21,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','N',null,0,'vfree3','ic.OnhandDimVO.vfree3',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,22,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','N',null,0,'vfree4','ic.OnhandDimVO.vfree4',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,23,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLN',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','N',null,0,'vfree5','ic.OnhandDimVO.vfree5',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,24,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','N',null,0,'vfree6','ic.OnhandDimVO.vfree6',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,25,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','N',null,0,'vfree7','ic.OnhandDimVO.vfree7',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,26,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','N',null,0,'vfree8','ic.OnhandDimVO.vfree8',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,27,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLR',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','N',null,0,'vfree9','ic.OnhandDimVO.vfree9',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,28,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','N',null,0,'vfree10','ic.OnhandDimVO.vfree10',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,29,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vhashcode',0,'N',1,'N','N',null,0,'vhashcode','ic.OnhandDimVO.vhashcode',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,30,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLU',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsubhashcode',0,'N',1,'N','N',null,0,'vsubhashcode','ic.OnhandDimVO.vsubhashcode',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,31,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLV',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','ic.OnhandDimVO.ts',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,null,null,null,'N',0,32,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLW',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','ic.OnhandDimVO.castunitid',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'计量单位',null,null,'N',1,33,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLX',1,5,'主单位',null,0,0,null,-1,'N',null,20,'cunitid',0,'N',1,'N','Y',null,0,null,'uap.material_v.pk_measdoc',null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'计量单位,nl=N','1400603010023',null,'N',1,34,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLY',1,2,'待处理数量',null,0,0,null,-1,'N',null,20,'onhandshouldassnum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'8,,','1400603010183',null,'N',0,35,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VLZ',1,2,'待处理主数量',null,0,0,null,-1,'N',null,20,'onhandshouldnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'8,,','1400603010185',null,'N',1,36,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM0',1,2,'本次主数量',null,0,0,null,-1,'N',null,20,'onhandcurrentnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'8,,','1400603010186',null,'N',1,37,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM1',1,6,'主数量满足度',null,0,0,null,-1,'N',null,20,'fulfiltype',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VKZ','@@@@',0,'SX,未满足=1,已满足=2,已超出=3','1400603010187',null,'N',1,38,'OnhandDimVO','现存量维度',0,'2015-03-31 18:50:24','N',null,null,null,0,1,'N',1,null,1,38)
go

