insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AV8',1,-1,null,null,0,0,null,-1,'N',null,-1,'cbilltypecode',0,'N',1,'N','Y','iif(cbilltypecode==null,getcolvalue(bd_billtype , BILLTYPENAME,pk_billtypecode ,getcolvalue(so_arsub_detail,cbilltypecode, carsubdetailid ,carsubdetailid )),cbilltypecode)',0,'cbilltypecode','so.arsub_detail.cbilltypecode',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,'影响因素单据类型,code=N',null,null,'N',1,4,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AV9',1,-1,null,null,0,0,null,-1,'N',null,-1,'csalebillid',0,'N',1,'N','N',null,0,'csalebillid','so.arsub_detail.csalebillid',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',0,3,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVA',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.arsub_detail.vbillcode',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',1,5,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVB',1,-1,null,null,0,0,null,-1,'N',null,-1,'carsubdetailid',0,'N',1,'N','N',null,0,'carsubdetailid','so.arsub_detail.carsubdetailid',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',0,1,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVC',1,-1,null,null,0,0,null,-1,'N',null,-1,'carsubbid',0,'N',1,'N','N',null,0,'carsubbid','so.arsub_detail.carsubbid',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',0,2,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVD',1,-1,null,null,0,0,null,-1,'N',null,-1,'dsubdate',0,'N',1,'N','Y',null,0,'dsubdate','so.arsub_detail.dsubdate',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',1,7,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVE',1,-1,null,null,0,0,null,-1,'N',null,-1,'csuboperator',0,'N',1,'N','Y',null,0,'csuboperator','so.arsub_detail.csuboperator',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,'null,code=N',null,null,'N',1,8,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVF',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.arsub_detail.ts',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',0,9,'arsub_detail','冲减明细实体',0,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000006AVG',1,-1,null,null,0,0,null,-1,'N',null,-1,'ndetailsubmny',0,'N',1,'N','Y',null,0,'ndetailsubmny','so.arsub_detail.ndetailsubmny',null,'N',0,null,'1001Z810000000006AV7','@@@@',1,null,null,null,'N',1,6,'arsub_detail','冲减明细实体',1,'2015-06-23 09:19:17','N',null,null,null,0,0,'N',1,null,100,6)
go

