/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m30.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:${vmObject.createdDate}
 * 
 * @author
 * @version NCPrj ??
 */
public class Fretexchange extends MDEnum {
  // 非退换货
  public static final Fretexchange COMMON = MDEnum.valueOf(Fretexchange.class,
      Integer.valueOf(0));

  // 退货
  public static final Fretexchange WITHDRAW = MDEnum.valueOf(
      Fretexchange.class, Integer.valueOf(1));

  // 换货
  public static final Fretexchange EXCHANGE = MDEnum.valueOf(
      Fretexchange.class, Integer.valueOf(2));

  public Fretexchange(IEnumValue enumvalue) {
    super(enumvalue);
  }

  public Integer getIntegerValue() {
    return Integer.valueOf(this.value().toString());
  }

  public int getIntValue() {
    return Integer.parseInt(this.value().toString());
  }

  public String getStringValue() {
    return this.value().toString();
  }

}
