insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5M',1,-1,null,null,0,0,null,-1,'N',null,-1,'nmny',null,'N',1,'N','Y',null,0,'nmny','so.saleinvoice_b.nmny',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,9,'vatsubtotal','vatsubtotal',1,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5N',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',null,'N',1,'N','N',null,0,'ccurrencyid','so.saleinvoice.ccurrencyid',null,'N',0,null,'0001Z81000000000ZD5L',null,1,'币种档案,code=N',null,null,'N',0,2,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5O',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxmny',null,'N',1,'N','Y',null,0,'ntaxmny','so.saleinvoice_b.ntaxmny',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,12,'vatsubtotal','vatsubtotal',1,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5P',1,-1,null,null,0,0,null,-1,'N',null,-1,'ncaltaxmny',null,'N',1,'N','Y',null,0,'ncaltaxmny','so.saleinvoice_b.ncaltaxmny',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,10,'vatsubtotal','vatsubtotal',1,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'blargessflag',null,'N',1,'N','Y',null,0,'blargessflag','so.saleinvoice_b.blargessflag',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,8,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5R',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleinvoicebid',null,'N',1,'N','N',null,0,'csaleinvoicebid','so.saleinvoice_b.csaleinvoicebid',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',0,3,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5S',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctaxcodeid',null,'N',1,'N','Y',null,0,'ctaxcodeid','so.saleinvoice_b.ctaxcodeid',null,'N',0,null,'0001Z81000000000ZD5L',null,1,'税码税率',null,null,'N',1,4,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5T',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntax',null,'N',1,'N','Y',null,0,'ntax','so.saleinvoice_b.ntax',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,11,'vatsubtotal','vatsubtotal',1,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5U',1,-1,null,null,0,0,null,-1,'N',null,-1,'fbuysellflag',null,'N',1,'N','Y',null,0,'fbuysellflag','so.saleinvoice.fbuysellflag',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,7,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5V',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleinvoiceid',null,'N',1,'N','N',null,0,'csaleinvoiceid','so.saleinvoice.csaleinvoiceid',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',0,1,'vatsubtotal','销售发票税额小计',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5W',1,-1,null,null,0,0,null,-1,'N',null,-1,'ftaxtypeflag',null,'N',1,'N','Y',null,0,'ftaxtypeflag','so.saleinvoice_b.ftaxtypeflag',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,6,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000ZD5X',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxrate',null,'N',1,'N','Y',null,0,'ntaxrate','so.saleinvoice_b.ntaxrate',null,'N',0,null,'0001Z81000000000ZD5L',null,1,null,null,null,'N',1,5,'vatsubtotal','vatsubtotal',0,'2012-11-22 19:42:05','N',null,null,null,1,1,'N',1,null,100,null)
go

