insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000054F0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.so_saleorder.vbillcode',null,'N',0,null,'1005Z8100000000054EZ','@@@@',0,null,null,null,'N',1,3,'csaleorderid',null,0,'2012-07-26 09:38:43','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000054F2',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.so_saleorder.dbilldate',null,'N',0,null,'1005Z8100000000054EZ','@@@@',0,null,null,null,'N',1,2,'csaleorderid',null,0,'2012-07-26 09:38:43','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000054F3',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',null,0,'ccustomerid','so.so_saleorder.ccustomerid',null,'N',0,null,'1005Z8100000000054EZ','@@@@',0,'客户档案,code=N,dpc=SCMDefault',null,null,'N',1,4,'csaleorderid',null,0,'2012-07-26 09:38:43','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000055YJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'csaleorderid',0,'N',1,'N','Y',null,0,'csaleorderid','so.so_saleorder.csaleorderid',null,'N',0,null,'1005Z8100000000054EZ','@@@@',0,null,null,null,'N',1,1,'csaleorderid','销售订单主实体',0,'2012-07-26 09:38:43','N',null,null,null,1,1,'N',1,null,1,null)
go

