insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003K3T',1,-1,null,null,0,1,null,-1,'N',null,-1,'cffileid',0,'N',1,'N','N',null,0,'cffileid','ic.OnhandDimVO.cffileid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,null,'N',0,59,'new','new',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM6',1,-1,null,null,0,0,null,-1,'N','pk_org',-1,'pk_org.code',0,'N',1,'N','N',null,0,'code','uap.stockorg.code',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,1,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM7',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','ic.OnhandDimVO.pk_org',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,2,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',0,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM8',1,-1,null,null,0,0,null,-1,'N','pk_org',-1,'pk_org.name',0,'N',1,'N','N',null,0,'name','uap.stockorg.name',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,3,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VM9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_onhanddim',0,'N',1,'N','N',null,0,'pk_onhanddim','ic.OnhandDimVO.pk_onhanddim',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,4,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMA',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','ic.OnhandDimVO.pk_group',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,5,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,0,1,'N',0,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMB',1,-1,null,null,0,0,null,-1,'N',null,-1,'cwarehouseid',0,'N',1,'N','Y','cwarehouseidname->getColValue(bd_stordoc,name,pk_stordoc,cwarehouseid)',0,'cwarehouseid','ic.OnhandDimVO.cwarehouseid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,6,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMC',1,-1,null,null,0,0,null,-1,'N','cwarehouseid',-1,'cwarehouseid.name',0,'N',1,'N','N',null,0,'name','uap.stordoc.name',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,7,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMD',1,-1,null,null,0,0,null,-1,'N','cwarehouseid',-1,'cwarehouseid.code',0,'N',1,'N','N',null,0,'code','uap.stordoc.code',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,8,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VME',1,-1,null,null,0,0,null,-1,'N','castunitid',-1,'castunitid.name',0,'N',1,'N','N',null,0,'name','uap.measdoc.name',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,'1400830020004','1400830020013','N',0,9,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMF',1,-1,null,null,0,0,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','N',null,0,'vchangerate','ic.OnhandDimVO.vchangerate',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,10,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMG',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.vbatchcode',0,'N',1,'N','Y',null,0,'vbatchcode','ic.BatchcodeVO.vbatchcode',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,11,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMH',1,-1,null,null,0,0,null,-1,'N',null,-1,'clocationid',0,'N',1,'N','N',null,0,'clocationid','ic.OnhandDimVO.clocationid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,12,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMI',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cvendorid',0,'N',1,'Y','N',null,0,'cvendorid','ic.OnhandDimVO.cvendorid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'供应商档案,code=N',null,'1400830020013','N',0,13,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','ic.OnhandDimVO.cprojectid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'项目,code=N',null,'1400830020013','N',0,14,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMK',1,-1,null,null,0,0,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','ic.OnhandDimVO.cproductorid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'生产厂商(自定义档案),code=N','UC000-0002929','1400830020013','N',0,15,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VML',1,-1,null,null,0,0,null,-1,'N',null,-1,'casscustid',0,'N',1,'N','N',null,0,'casscustid','ic.OnhandDimVO.casscustid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'客户档案,code=N',null,'1400830020013','N',0,16,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMM',1,-1,null,null,0,0,null,-1,'N',null,-1,'cstateid',0,'N',1,'N','N',null,0,'cstateid','ic.OnhandDimVO.cstateid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'库存状态,code=N',null,'1400830020013','N',0,17,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMN',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','N',null,0,'vfree1','ic.OnhandDimVO.vfree1',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,18,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMO',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','N',null,0,'vfree2','ic.OnhandDimVO.vfree2',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,19,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMP',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','N',null,0,'vfree3','ic.OnhandDimVO.vfree3',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,20,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','N',null,0,'vfree4','ic.OnhandDimVO.vfree4',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,21,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMR',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','N',null,0,'vfree5','ic.OnhandDimVO.vfree5',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,22,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMS',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','N',null,0,'vfree6','ic.OnhandDimVO.vfree6',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,23,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMT',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','N',null,0,'vfree7','ic.OnhandDimVO.vfree7',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,24,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMU',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','N',null,0,'vfree8','ic.OnhandDimVO.vfree8',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,25,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMV',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','N',null,0,'vfree9','ic.OnhandDimVO.vfree9',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,26,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMW',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','N',null,0,'vfree10','ic.OnhandDimVO.vfree10',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,27,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMX',1,-1,null,null,0,0,null,-1,'N',null,-1,'cvmivenderid',0,'N',1,'N','N',null,0,'cvmivenderid','ic.OnhandDimVO.cvmivenderid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,28,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMY',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctplcustomerid',0,'N',1,'N','N',null,0,'ctplcustomerid','ic.OnhandDimVO.ctplcustomerid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,29,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VMZ',1,-1,null,null,0,1,null,-1,'Y',null,-1,'cmaterialvid',0,'N',1,'Y','N',null,0,'cmaterialvid','ic.OnhandDimVO.cmaterialvid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'物料（多版本）,code=Y,dpc=SCMDefault',null,'1400830020013','N',0,30,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN0',0,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',0,'N','N',null,0,'name','uap.material.name',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,31,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN1',0,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.code',0,'N',0,'N','N',null,0,'code','uap.material.code',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,32,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN2',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.dproducedate',0,'N',1,'N','Y',null,0,'dproducedate','ic.BatchcodeVO.dproducedate',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,33,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN3',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialoid',0,'N',1,'N','N',null,0,'cmaterialoid','ic.OnhandDimVO.cmaterialoid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'null,dpc=SCMDefault',null,'1400830020013','N',0,34,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN4',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','ic.OnhandDimVO.castunitid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,35,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN5',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_batchcode',0,'N',1,'N','N',null,0,'pk_batchcode','ic.OnhandDimVO.pk_batchcode',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,36,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbatchcode',0,'N',1,'N','N',null,0,'vbatchcode','ic.OnhandDimVO.vbatchcode',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,37,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN7',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.dvalidate',0,'N',1,'N','Y',null,0,'dvalidate','ic.BatchcodeVO.dvalidate',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',1,38,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN8',1,-1,null,null,0,0,null,-1,'N',null,-1,'vhashcode',0,'N',1,'N','N',null,0,'vhashcode','ic.OnhandDimVO.vhashcode',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,39,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VN9',1,-1,null,null,0,0,null,-1,'N',null,-1,'vsubhashcode',0,'N',1,'N','N',null,0,'vsubhashcode','ic.OnhandDimVO.vsubhashcode',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,40,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNA',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','ic.OnhandDimVO.ts',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,41,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNB',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.version',0,'N',1,'N','N',null,0,'version','uap.material.version',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,42,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNC',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.cqualitylevelid',0,'N',1,'N','Y',null,0,'cqualitylevelid','ic.BatchcodeVO.cqualitylevelid',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,null,null,'1400830020013','N',0,43,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VND',1,2,null,null,0,1,null,-1,'N',null,20,'nnum1',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020006','1400830020013','N',0,44,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNE',1,2,null,null,0,1,null,-1,'N',null,20,'nastnum1',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','UC000-0000327','1400830020013','N',0,45,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNF',1,2,null,null,0,1,null,-1,'N',null,20,'nnum2',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020001','1400830020013','N',0,46,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNG',1,2,null,null,0,1,null,-1,'N',null,20,'nastnum2',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','UC000-0000329','1400830020013','N',0,47,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNH',1,2,null,null,0,1,null,-1,'N',null,20,'nrsnum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020010','1400830020013','N',0,48,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNI',1,2,null,null,0,1,null,-1,'N',null,20,'nrsastnum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020005','1400830020013','N',0,49,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,52)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNJ',1,2,null,null,0,0,null,-1,'N',null,20,'nonhandastnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','UC000-0003217','1400830020013','N',1,50,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNK',1,2,null,null,0,0,null,-1,'N',null,20,'nonhandnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020012','1400830020013','N',1,51,'new','现存量维度',1,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,54)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNL',1,2,null,null,0,0,null,-1,'N',null,20,'nlocknum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'8,,','1400830020030','1400830020013','N',0,52,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,55)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNM',1,2,null,null,0,0,null,-1,'N',null,20,'natpnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','UC000-0001084','1400830020013','N',1,53,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,56)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNN',1,0,null,null,0,1,null,-1,'N',null,20,'cunitid',0,'N',1,'N','Y',null,0,null,'uap.material_v.pk_measdoc',null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'计量单位','1400830020011','1400830020013','N',0,54,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNO',1,2,null,null,0,0,null,-1,'N',null,20,'nforedayatpnum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'2','1400830020008','1400830020013','N',0,55,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,57)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNP',1,2,null,null,0,0,null,-1,'N',null,20,'nlockastnum',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'8,,','1400830020030','1400830020013','N',0,56,'new','现存量维度',0,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNQ',1,2,null,null,0,1,null,-1,'N',null,20,'nassistnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'8,,','1400830020009','1400830020013','N',1,57,'new','现存量维度',1,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000004VNR',1,2,null,null,0,1,null,-1,'N',null,20,'nnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1004Z810000000004VM5','@@@@',0,'8,,','1400830020002','1400830020013','N',1,58,'new','现存量维度',1,'2015-07-07 18:06:22','N',null,null,null,1,1,'N',1,null,1,42)
go

