insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000028AM',1,0,null,null,0,1,'name->getcolvalue(bd_material_v ,name ,pk_source ,pk_material );vspec->getcolvalue(bd_material_v ,materialspec ,pk_source ,pk_material );vtype->getcolvalue(bd_material_v ,materialtype ,pk_source ,pk_material );code->getcolvalue(bd_material_v ,code ,pk_source ,pk_material );',-1,'N',null,20,'pk_material',0,'N',1,null,'N','name->getcolvalue(bd_material_v ,name ,pk_source ,pk_material );vspec->getcolvalue(bd_material_v ,materialspec ,pk_source ,pk_material );vtype->getcolvalue(bd_material_v ,materialtype ,pk_source ,pk_material );code->getcolvalue(bd_material_v ,code ,pk_source ,pk_material );',0,null,null,null,'N',0,null,'1002Z8100000000028AL','@@@@',1,null,'1400610_HisSalequo0009',null,'N',0,2,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC1',1,0,null,null,0,0,null,-1,'N',null,20,'crowno',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,null,'1400610_HisSalequo0002',null,'N',1,1,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC3',1,2,null,null,0,0,null,-1,'N',null,20,'hisprice',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,'2','1400610_HisSalequo0003',null,'N',1,7,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC5',1,2,null,null,0,0,null,-1,'N',null,20,'newprice',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,'2','1400610_HisSalequo0004',null,'N',1,8,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC7',1,0,null,null,0,0,null,-1,'N',null,200,'name',null,'N',1,null,'Y','name->getcolvalue(bd_material_v ,name ,pk_source ,pk_material );',0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,null,'1400610_HisSalequo0005',null,'N',1,4,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC8',1,0,null,null,0,0,null,-1,'N',null,20,'vtype',null,'N',1,null,'Y','vtype->getcolvalue(bd_material_v ,materialtype ,pk_source ,pk_material );',0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,null,'1400610_HisSalequo0006',null,'N',1,6,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BC9',1,0,null,null,0,0,null,-1,'N',null,20,'vspec',null,'N',1,null,'Y','vspec->getcolvalue(bd_material_v ,materialspec ,pk_source ,pk_material );',0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,null,'1400610_HisSalequo0007',null,'N',1,5,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002BCA',1,5,null,null,0,0,'name->getcolvalue(bd_material_v ,name ,pk_source ,pk_material );vspec->getcolvalue(bd_material_v ,materialspec ,pk_source ,pk_material );vtype->getcolvalue(bd_material_v ,materialtype ,pk_source ,pk_material );',-1,'N','pk_material',20,'code',null,'N',1,null,'Y','name->getcolvalue(bd_material_v ,name ,pk_source ,pk_material );vspec->getcolvalue(bd_material_v ,materialspec ,pk_source ,pk_material );vtype->getcolvalue(bd_material_v ,materialtype ,pk_source ,pk_material );code->getcolvalue(bd_material_v ,code ,pk_source ,pk_material );',0,null,null,null,'N',0,null,'1002Z8100000000028AL',null,1,'物料','1400610_HisSalequo0001',null,'N',1,3,'HisSalequoRes','历史报价结果',0,'2010-07-21 14:04:56','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000VNO9',1,0,null,null,0,0,null,5,'N',null,20,'pk_currtype',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1002Z8100000000028AL','@@@@',1,null,'1400610_HisSalequo0010',null,'N',0,9,'HisSalequoRes','历史报价结果',0,'2015-06-26 09:54:43','N',null,null,null,1,1,'N',1,null,100,9)
go

