insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005KMK',1,-1,null,null,0,0,null,-1,'N',null,-1,'ninvoicesubmny',0,'N',1,'N','N',null,0,'ninvoicesubmny','so.arsub_b.ninvoicesubmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,55,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005KML',1,-1,null,null,0,0,null,-1,'N',null,-1,'nredarsubmny',0,'N',1,'N','N',null,0,'nredarsubmny','so.arsub_b.nredarsubmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,57,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005KMM',1,-1,null,null,0,0,null,-1,'N',null,-1,'nordersubmny',0,'N',1,'N','N',null,0,'nordersubmny','so.arsub_b.nordersubmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,56,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DP23',1,-1,null,null,0,1,null,-1,'N',null,-1,'nthissubmny',0,'N',1,'N','Y',null,0,'nthissubmny','so.arsub_b.nthissubmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',1,62,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DP24',1,-1,null,null,0,0,null,-1,'N',null,-1,'nsumusedmny',0,'N',1,'N','Y',null,0,'nsumusedmny','so.arsub_b.nsumusedmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,'1400605020032',null,'N',1,58,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000HJ6C',1,-1,null,null,0,0,null,-1,'N',null,-1,'noriginvoicemny',0,'N',1,'N','N',null,0,'noriginvoicemny','so.arsub_b.noriginvoicemny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,63,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001AD9',1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.arsub.vtrantypecode',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,7,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001ADB',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','Y',null,0,'ctrantypeid','so.arsub.ctrantypeid','vtrantypecode=pk_billtypecode','N',0,null,'1005Z810000000004NFV','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',1,6,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001ADG',1,-1,null,null,0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','N',null,0,'billmaker','so.arsub.billmaker',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'用户,code=N',null,null,'N',0,21,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000002C3Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'vordertrantypecode',null,'N',1,'N','N',null,0,'vordertrantypecode','so.arsub_b.vordertrantypecode',null,'N',0,null,'1005Z810000000004NFV',null,1,null,null,null,'N',0,53,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000002C43',1,-1,null,null,0,0,null,-1,'N',null,-1,'cordertrantypeid',0,'N',1,'N','Y',null,0,'cordertrantypeid','so.arsub_b.cordertrantypeid','vordertrantypecode=pk_billtypecode','N',0,null,'1005Z810000000004NFV','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',1,52,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NFW',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef3',0,'N',1,'N','N',null,0,'vdef3','so.arsub.vdef3',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,30,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NFX',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigarsubmny',0,'N',1,'N','Y',null,0,'norigarsubmny','so.arsub_b.norigarsubmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,'1400605020006',null,'N',1,54,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NFY',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorgid',0,'N',1,'N','Y',null,0,'csaleorgid','so.arsub.csaleorgid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'销售组织,code=N','UC000-0004128',null,'N',1,9,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NFZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.arsub.corigcurrencyid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'币种档案,code=N',null,null,'N',1,17,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG1',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef12',0,'N',1,'N','N',null,0,'vdef12','so.arsub.vdef12',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,39,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG2',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.arsub_b.crowno',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',1,50,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG3',1,-1,null,null,0,0,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','N',null,0,'taudittime','so.arsub.taudittime',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,26,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG4',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef6',0,'N',1,'N','N',null,0,'vbdef6','so.arsub_b.vbdef6',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,69,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG5',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef17',0,'N',1,'N','N',null,0,'vdef17','so.arsub.vdef17',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,44,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG6',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef3',0,'N',1,'N','N',null,0,'vbdef3','so.arsub_b.vbdef3',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,66,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG7',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef13',0,'N',1,'N','N',null,0,'vbdef13','so.arsub_b.vbdef13',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,76,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG8',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.arsub_b.cprodlineid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'产品线,code=N',null,null,'N',1,51,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NG9',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.arsub.pk_org',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'财务组织,code=N',null,null,'N',0,3,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGA',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','so.arsub.modifiedtime',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,24,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGB',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef16',0,'N',1,'N','N',null,0,'vdef16','so.arsub.vdef16',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,43,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGC',1,-1,null,null,0,0,null,-1,'N',null,-1,'carsubbid',0,'N',1,'N','N',null,0,'carsubbid','so.arsub_b.carsubbid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,49,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGD',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','so.arsub.creator',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'用户,code=N',null,null,'N',0,20,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGE',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.arsub.vbillcode',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',1,5,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGF',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','N',null,0,'cdeptid','so.arsub.cdeptid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'部门,code=N','UC000-0004133',null,'N',0,14,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGH',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.arsub.pk_group',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,',code=N',null,null,'N',0,2,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGI',1,-1,null,null,0,0,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','N',null,0,'cemployeeid','so.arsub.cemployeeid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'人员,code=N',null,null,'N',0,13,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef20',0,'N',1,'N','N',null,0,'vbdef20','so.arsub_b.vbdef20',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,83,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGK',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',null,0,'approver','so.arsub.approver',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'用户,code=N',null,null,'N',0,25,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGL',1,-1,null,null,0,0,null,-1,'N',null,-1,'cordercustid',0,'N',1,'N','Y',null,0,'cordercustid','so.arsub.cordercustid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'客户档案,code=N',null,null,'N',1,11,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGM',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef7',0,'N',1,'N','N',null,0,'vbdef7','so.arsub_b.vbdef7',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,70,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGN',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','N',null,0,'dbilldate','so.arsub.dbilldate',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,8,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGP',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef15',0,'N',1,'N','N',null,0,'vdef15','so.arsub.vdef15',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,42,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGR',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef20',0,'N',1,'N','N',null,0,'vdef20','so.arsub.vdef20',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,47,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGS',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef5',0,'N',1,'N','N',null,0,'vbdef5','so.arsub_b.vbdef5',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,68,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGT',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef8',0,'N',1,'N','N',null,0,'vbdef8','so.arsub_b.vbdef8',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,71,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGU',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef19',0,'N',1,'N','N',null,0,'vbdef19','so.arsub_b.vbdef19',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,82,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGV',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorgvid',0,'N',1,'N','N',null,0,'csaleorgvid','so.arsub.csaleorgvid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'销售组织版本,code=N',null,null,'N',0,10,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGW',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef18',0,'N',1,'N','N',null,0,'vdef18','so.arsub.vdef18',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,45,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGX',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef6',0,'N',1,'N','N',null,0,'vdef6','so.arsub.vdef6',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,33,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGY',1,-1,null,null,0,0,null,-1,'N',null,-1,'cinvoicecustid',0,'N',1,'N','Y',null,0,'cinvoicecustid','so.arsub.cinvoicecustid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'客户档案,code=N','1400605020002',null,'N',1,16,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NGZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.arsub.ts',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,48,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH0',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef16',0,'N',1,'N','N',null,0,'vbdef16','so.arsub_b.vbdef16',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,79,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH1',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef10',0,'N',1,'N','N',null,0,'vbdef10','so.arsub_b.vbdef10',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,73,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH2',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef5',0,'N',1,'N','N',null,0,'vdef5','so.arsub.vdef5',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,32,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH3',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef13',0,'N',1,'N','N',null,0,'vdef13','so.arsub.vdef13',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,40,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH4',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef2',0,'N',1,'N','N',null,0,'vbdef2','so.arsub_b.vbdef2',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,65,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH5',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','so.arsub.creationtime',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,22,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH6',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef8',0,'N',1,'N','N',null,0,'vdef8','so.arsub.vdef8',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,35,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH7',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptvid',0,'N',1,'N','N',null,0,'cdeptvid','so.arsub.cdeptvid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'部门版本,code=N',null,null,'N',0,15,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH8',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef14',0,'N',1,'N','N',null,0,'vdef14','so.arsub.vdef14',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,41,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NH9',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef2',0,'N',1,'N','N',null,0,'vdef2','so.arsub.vdef2',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,29,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHA',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef4',0,'N',1,'N','N',null,0,'vdef4','so.arsub.vdef4',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,31,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHB',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef1',0,'N',1,'N','N',null,0,'vdef1','so.arsub.vdef1',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,28,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHC',1,-1,null,null,0,0,null,-1,'N',null,-1,'frownote',0,'N',1,'N','N',null,0,'frownote','so.arsub_b.frownote',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,60,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHD',1,-1,null,null,0,0,null,-1,'N',null,-1,'carsubid',0,'N',1,'N','N',null,0,'carsubid','so.arsub.carsubid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,'1400605020004',null,'N',0,1,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHE',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef7',0,'N',1,'N','N',null,0,'vdef7','so.arsub.vdef7',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,34,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHF',1,-1,null,null,0,0,null,-1,'N',null,-1,'nremainmny',0,'N',1,'N','Y','nremainmny->norigarsubmny-ninvoicesubmny-nordersubmny-nredarsubmny',0,'nremainmny','so.arsub_b.nremainmny',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,'1400605020005',null,'N',1,61,'arsub','arsub',1,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHG',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef11',0,'N',1,'N','N',null,0,'vbdef11','so.arsub_b.vbdef11',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,74,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHH',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','so.arsub.modifier',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'用户,code=N',null,null,'N',0,23,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHI',1,-1,null,null,0,0,null,-1,'N',null,-1,'bsubfinshflag',0,'N',1,'N','N',null,0,'bsubfinshflag','so.arsub_b.bsubfinshflag',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,59,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','N',null,0,'cchanneltypeid','so.arsub.cchanneltypeid',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'渠道类型,code=N',null,null,'N',0,12,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHK',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef9',0,'N',1,'N','N',null,0,'vbdef9','so.arsub_b.vbdef9',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,72,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHL',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef11',0,'N',1,'N','N',null,0,'vdef11','so.arsub.vdef11',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,38,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHM',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','so.arsub.pk_org_v',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,'财务组织版本(所有),code=N','1400605020001',null,'N',1,4,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHN',1,-1,null,null,0,0,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.arsub.vnote',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',1,19,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHO',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef18',0,'N',1,'N','N',null,0,'vbdef18','so.arsub_b.vbdef18',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,81,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHP',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef14',0,'N',1,'N','N',null,0,'vbdef14','so.arsub_b.vbdef14',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,77,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef1',0,'N',1,'N','N',null,0,'vbdef1','so.arsub_b.vbdef1',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,64,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHR',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef10',0,'N',1,'N','N',null,0,'vdef10','so.arsub.vdef10',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,37,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHS',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef17',0,'N',1,'N','N',null,0,'vbdef17','so.arsub_b.vbdef17',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,80,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHT',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef19',0,'N',1,'N','N',null,0,'vdef19','so.arsub.vdef19',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,46,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHV',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef12',0,'N',1,'N','N',null,0,'vbdef12','so.arsub_b.vbdef12',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,75,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHW',1,-1,null,null,0,0,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','N',null,0,'fstatusflag','so.arsub.fstatusflag',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,18,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHX',1,-1,null,null,0,0,null,-1,'N',null,-1,'vdef9',0,'N',1,'N','N',null,0,'vdef9','so.arsub.vdef9',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,36,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHY',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef4',0,'N',1,'N','N',null,0,'vbdef4','so.arsub_b.vbdef4',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,67,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NHZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbdef15',0,'N',1,'N','N',null,0,'vbdef15','so.arsub_b.vbdef15',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,78,'arsub','arsub',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000004NI0',1,-1,null,null,0,0,null,-1,'N',null,-1,'iprintcount',0,'N',1,'N','N',null,0,'iprintcount','so.arsub.iprintcount',null,'N',0,null,'1005Z810000000004NFV','@@@@',1,null,null,null,'N',0,27,'arsub','冲应收单',0,'2013-07-10 16:43:09','N',null,null,null,0,1,'N',1,null,100,null)
go

