insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9G5',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.recvplan.vbillcode',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,1,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9G7',1,-1,null,null,0,0,null,-1,'N',null,-1,'dinsideenddate',0,'N',1,'N','N',null,0,'dinsideenddate','so.recvplan.dinsideenddate',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',0,6,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',0,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9G8',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbegindate',0,'N',1,'N','Y',null,0,'dbegindate','so.recvplan.dbegindate',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,4,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9G9',1,-1,null,null,0,0,null,-1,'N',null,-1,'iaccounttermno',0,'N',1,'N','Y',null,0,'iaccounttermno','so.recvplan.iaccounttermno',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,3,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9GA',1,-1,null,null,0,0,null,-1,'N',null,-1,'nrate',0,'N',1,'N','Y',null,0,'nrate','so.recvplan.nrate',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,'2,-100000000000000000000.00,100000000000000000000.00',null,null,'N',1,7,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9GB',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigmny',0,'N',1,'N','Y',null,0,'norigmny','so.recvplan.norigmny',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,8,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9GC',1,-1,null,null,0,0,null,-1,'N',null,-1,'bpreflag',0,'N',1,'N','Y',null,0,'bpreflag','so.recvplan.bpreflag',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,9,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000I9GD',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.recvplan.ts',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',0,10,'recvplan','销售模块收款计划',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000PM2J',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaytermid',0,'N',1,'N','Y',null,0,'cpaytermid','so.recvplan.cpaytermid',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,'收款协议',null,null,'N',1,2,'recvplan','recvplan',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000PM2K',1,-1,null,null,0,0,null,-1,'N',null,-1,'denddate',0,'N',1,'N','Y',null,0,'denddate','so.recvplan.denddate',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,null,null,null,'N',1,5,'recvplan','recvplan',0,'2015-07-27 10:47:23','N',null,null,null,0,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011XQQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','N',null,0,'corigcurrencyid','so.recvplan.corigcurrencyid',null,'N',0,null,'1001Z81000000000I9G4','@@@@',1,'币种档案,code=N',null,null,'N',0,11,'recvplan','recvplan',0,'2015-07-27 10:47:23','N',null,null,null,1,1,'N',1,null,100,11)
go

