insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001KC3',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_trantype',null,'N',1,null,'N',null,0,'pk_trantype','so.m4331trantype.pk_trantype',null,'N',0,null,'1005Z810000000003DX0',null,0,null,null,null,'N',0,6,'m4331trantype','m4331trantype',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000003DX1',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,null,'N',null,0,'ts','so.m4331trantype.ts',null,'N',0,null,'1005Z810000000003DX0','@@@@',0,null,null,null,'N',0,5,'m4331trantype','发货单交易类型',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000003DX2',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,null,'N',null,0,'pk_group','so.m4331trantype.pk_group',null,'N',0,null,'1005Z810000000003DX0','@@@@',0,null,null,null,'N',0,2,'m4331trantype','发货单交易类型',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000003DX3',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bonceoutflag',0,'N',1,null,'Y',null,0,'bonceoutflag','so.m4331trantype.bonceoutflag',null,'N',0,null,'1005Z810000000003DX0','@@@@',0,null,null,null,'N',1,4,'m4331trantype','发货单交易类型',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000003DX4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,null,'N',null,0,'vtrantypecode','so.m4331trantype.vtrantypecode',null,'N',0,null,'1005Z810000000003DX0','@@@@',0,null,null,null,'N',0,3,'m4331trantype','发货单交易类型',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000003DX5',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,null,'N',null,0,'ctrantypeid','so.m4331trantype.ctrantypeid','vtrantypecode=pk_billtypecode','N',0,null,'1005Z810000000003DX0','@@@@',0,null,null,null,'N',0,1,'m4331trantype','发货单交易类型',0,'2011-04-26 09:54:27','N',null,null,null,1,1,'N',1,null,1,null)
go

