insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000UR96',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigarmny',0,'N',1,'N','Y',null,0,'norigarmny','so.so_balance_b.norigarmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,'1400603040002',null,'N',1,9,'so_balance_b','so_balance_b',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8N9',1,-1,null,null,0,0,null,-1,'N',null,-1,'darbilldate',0,'N',1,'N','Y',null,0,'darbilldate','so.so_balance_b.darbilldate',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',1,7,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NA',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.so_balance.corigcurrencyid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,'币种档案',null,null,'N',1,10,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NB',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigthisbalmny',0,'N',1,'N','Y',null,0,'norigthisbalmny','so.so_balance_b.norigthisbalmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',1,14,'so_balance_b','订单收款核销子实体',1,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NC',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigordbalmny',0,'N',1,'N','Y',null,0,'norigordbalmny','so.so_balance_b.norigordbalmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,'1400603040012',null,'N',1,13,'so_balance_b','订单收款核销子实体',1,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8ND',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_balance_b.pk_org',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,2,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NE',1,-1,null,null,0,0,null,-1,'N',null,-1,'carorigcurrencyid',0,'N',1,'N','Y',null,0,'carorigcurrencyid','so.so_balance_b.carorigcurrencyid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,'币种档案,code=N',null,null,'N',1,8,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NF',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_balance_b.ts',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,16,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_balance.pk_group',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,5,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NH',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_balance.ts',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,20,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NI',1,-1,null,null,0,0,null,-1,'N',null,-1,'csobalanceid',0,'N',1,'N','N',null,0,'csobalanceid','so.so_balance.csobalanceid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,1,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalpaymny',0,'N',1,'N','Y',null,0,'ntotalpaymny','so.so_balance.ntotalpaymny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,'1400603040014',null,'N',1,12,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NK',1,-1,null,null,0,0,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','N',null,0,'cemployeeid','so.so_balance.cemployeeid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,15,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NL',1,-1,null,null,0,0,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','N',null,0,'cchanneltypeid','so.so_balance.cchanneltypeid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,19,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NM',1,-1,null,null,0,0,null,-1,'Y',null,-1,'ccustomerid',0,'N',1,'Y','Y',null,0,'ccustomerid','so.so_balance.ccustomerid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',1,6,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NN',1,-1,null,null,0,0,null,-1,'N',null,-1,'csaleorderid',0,'N',1,'N','N',null,0,'csaleorderid','so.so_balance.csaleorderid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,2,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NO',1,-1,null,null,0,0,null,-1,'N',null,-1,'darbalancedate',0,'N',1,'N','Y',null,0,'darbalancedate','so.so_balance_b.darbalancedate',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',1,10,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NP',1,-1,null,null,0,0,null,-1,'N',null,-1,'carorgid',0,'N',1,'N','N',null,0,'carorgid','so.so_balance.carorgid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,17,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','N',null,0,'cdeptid','so.so_balance.cdeptid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,16,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NR',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaybillrowid',0,'N',1,'N','N',null,0,'cpaybillrowid','so.so_balance_b.cpaybillrowid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,5,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NS',1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.so_balance.vtrantypecode',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,18,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NU',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','so.so_balance.pk_org',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,3,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NV',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cinvoicecustid',0,'N',1,'Y','Y',null,0,'cinvoicecustid','so.so_balance.cinvoicecustid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',1,7,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NW',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigbalmny',0,'N',1,'N','N',null,0,'ntotalorigbalmny','so.so_balance.ntotalorigbalmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,'1400603040013',null,'N',0,13,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NX',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','so.so_balance.pk_org_v',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,4,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NY',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaybillid',0,'N',1,'N','N',null,0,'cpaybillid','so.so_balance_b.cpaybillid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,4,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8NZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigtaxmny',0,'N',1,'N','Y',null,0,'ntotalorigtaxmny','so.so_balance.ntotalorigtaxmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',1,11,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O0',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.so_balance_b.cprodlineid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,'产品线,code=N',null,null,'N',1,11,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O1',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','so.so_balance.vbillcode',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',1,8,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O2',1,-1,null,null,0,0,null,-1,'N',null,-1,'fibaltype',0,'N',1,'N','Y',null,0,'fibaltype','so.so_balance_b.fibaltype',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',1,3,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O3',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigaccbalmny',0,'N',1,'N','N',null,0,'norigaccbalmny','so.so_balance_b.norigaccbalmny',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,'1400603040011',null,'N',0,15,'so_balance_b','订单收款核销子实体',1,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O4',1,-1,null,null,0,0,null,-1,'N',null,-1,'cpaytermid',0,'N',1,'N','N',null,0,'cpaytermid','so.so_balance.cpaytermid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',0,14,'so_balance','订单收款核销主实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O5',1,-1,null,null,0,1,null,-1,'N',null,-1,'varbillcode',0,'N',1,'N','Y',null,0,'varbillcode','so.so_balance_b.varbillcode',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',1,6,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000F8O6',1,-1,null,null,0,0,null,-1,'N',null,-1,'csobalancebid',0,'N',1,'N','N',null,0,'csobalancebid','so.so_balance_b.csobalancebid',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,1,'so_balance_b','订单收款核销子实体',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OK9D',1,-1,null,null,0,0,null,-1,'N',null,-1,'bpreceiveflag',0,'N',1,'N','N',null,0,'bpreceiveflag','so.so_balance_b.bpreceiveflag',null,'N',0,null,'1002Z81000000000F8N8','@@@@',1,null,null,null,'N',0,12,'so_balance_b','so_balance_b',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OK9E',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.so_balance.dbilldate',null,'N',0,null,'1002Z81000000000F8N8','@@@@',0,null,null,null,'N',1,9,'so_balance','so_balance',0,'2013-08-09 13:52:38','N',null,null,null,1,1,'N',1,null,1,null)
go

