insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002DNH',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',null,'N',1,'N','N',null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z81000000000OMKS',null,1,null,null,null,'N',0,11,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKT',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_depmatrel.pk_group',null,'N',1,null,'1002Z81000000000OMKS','@@@@',0,null,null,null,'N',0,4,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKU',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_depmatrel_b.pk_org',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',0,2,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKV',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_material',0,'N',1,'N','N',null,0,'pk_material','so.so_depmatrel_b.pk_material',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',0,10,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKW',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','so.so_depmatrel.pk_org_v',null,'N',1,null,'1002Z81000000000OMKS','@@@@',0,null,null,null,'N',0,3,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKX',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.so_depmatrel.pk_org',null,'N',1,null,'1002Z81000000000OMKS','@@@@',0,null,null,null,'N',0,2,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKY',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_depmatrel.ts',null,'N',0,null,'1002Z81000000000OMKS','@@@@',0,null,null,null,'N',0,6,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMKZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','so.so_depmatrel_b.cemployeeid',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,'人员','UC000-0000056',null,'N',1,6,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML0',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.so_depmatrel_b.ts',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',0,18,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML1',1,-1,null,null,0,1,null,-1,'N',null,-1,'exclude',0,'N',1,'N','Y',null,0,'exclude','so.so_depmatrel_b.exclude',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',1,16,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_material_v',0,'N',1,'N','Y',null,0,'pk_material_v','so.so_depmatrel_b.pk_material_v','pk_material=pk_source','N',0,null,'1002Z81000000000OMKS','@@@@',1,'物料（多版本）','UC000-0002911',null,'N',1,12,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML3',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_depmatrel',0,'N',1,'N','N',null,0,'pk_depmatrel','so.so_depmatrel.pk_depmatrel',null,'N',0,null,'1002Z81000000000OMKS','@@@@',0,null,null,null,'N',0,1,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML4',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept',0,'N',1,'N','N',null,0,'pk_dept','so.so_depmatrel_b.pk_dept',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,'部门,code=N',null,null,'N',0,3,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML5',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialbaseclass',0,'N',1,'N','Y',null,0,'pk_materialbaseclass','so.so_depmatrel_b.pk_materialbaseclass',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,'物料基本分类,code=N',null,null,'N',1,8,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML6',1,-1,null,null,0,1,null,-1,'N',null,-1,'allowsale',0,'N',1,'N','Y',null,0,'allowsale','so.so_depmatrel.allowsale',null,'N',1,null,'1002Z81000000000OMKS','@@@@',0,null,'1400601030002',null,'N',1,5,'so_depmatrel','部门物料关系主实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML7',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialsaleclass',0,'N',1,'N','Y',null,0,'pk_materialsaleclass','so.so_depmatrel_b.pk_materialsaleclass',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,'物料销售分类,code=N',null,null,'N',1,9,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_depmatrel_b',0,'N',1,'N','N',null,0,'pk_depmatrel_b','so.so_depmatrel_b.pk_depmatrel_b',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',0,1,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OML9',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.so_depmatrel_b.vnote',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,'UC000-0001376',null,'N',1,17,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMLA',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',null,0,'pk_dept_v','so.so_depmatrel_b.pk_dept_v','pk_dept=pk_dept','N',0,null,'1002Z81000000000OMKS','@@@@',1,'部门版本','UC000-0004073',null,'N',1,4,'pk_depmatrel_b','部门物料关系子实体',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMC',1,-1,null,null,0,0,null,-1,'N','cemployeeid',-1,'cemployeeid.name',0,'N',1,'N','Y',null,0,'name','uap.psndoc.name',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,'1400601030001',null,'N',1,7,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMD',1,-1,null,null,0,0,null,-1,'N','pk_dept_v',-1,'pk_dept_v.name',0,'N',1,'N','Y',null,0,'name','uap.dept_v.name',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,'UC000-0004069',null,'N',1,5,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMME',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',1,14,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMF',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',1,15,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OMMG',1,-1,null,null,0,0,null,-1,'N','pk_material_v',-1,'pk_material_v.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,null,null,null,'N',1,13,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z8100000000017ZS',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.so_depmatrel_b.pk_group',null,'N',0,null,'1002Z81000000000OMKS','@@@@',1,'集团,code=N',null,null,'N',0,19,'pk_depmatrel_b','pk_depmatrel_b',0,'2011-09-07 09:27:32','N',null,null,null,0,1,'N',0,null,100,null)
go

