insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P4Z','-99',0,8,1,null,0,'vdef1',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P50','-99',0,9,1,null,0,'vdef2',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P51','-99',0,10,1,null,0,'vdef3',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P52','-99',0,11,1,null,0,'vdef4',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P53','-99',0,12,1,null,0,'vdef5',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P54','-99',0,13,1,null,0,'vdef6',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P55','-99',0,14,1,null,0,'vdef7',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P56','-99',0,15,1,null,0,'vdef8',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P57','-99',0,16,1,null,0,'vdef9',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P58','-99',0,17,1,null,0,'vdef10',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P59','-99',0,18,1,null,0,'vdef11',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5A','-99',0,19,1,null,0,'vdef12',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5B','-99',0,20,1,null,0,'vdef13',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5C','-99',0,21,1,null,0,'vdef14',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5D','-99',0,22,1,null,0,'vdef15',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5E','-99',0,23,1,null,0,'vdef16',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5F','-99',0,24,1,null,0,'vdef17',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5G','-99',0,25,1,null,0,'vdef18',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5H','-99',0,26,1,null,0,'vdef19',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5I','-99',0,27,1,null,0,'vdef20',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5J','-99',0,28,1,null,0,'so_saleorder_b.vfree1',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5K','-99',0,29,1,null,0,'so_saleorder_b.vfree2',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5L','-99',0,30,1,null,0,'so_saleorder_b.vfree3',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5M','-99',0,31,1,null,0,'so_saleorder_b.vfree4',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5N','-99',0,32,1,null,0,'so_saleorder_b.vfree5',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5O','-99',0,33,1,null,0,'so_saleorder_b.vfree6',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5P','-99',0,34,1,null,0,'so_saleorder_b.vfree7',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5Q','-99',0,35,1,null,0,'so_saleorder_b.vfree8',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5R','-99',0,36,1,null,0,'so_saleorder_b.vfree9',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5S','-99',0,37,1,null,0,'so_saleorder_b.vfree10',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5T','-99',0,38,1,null,0,'so_saleorder_b.vbdef1',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5U','-99',0,39,1,null,0,'so_saleorder_b.vbdef2',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5V','-99',0,40,1,null,0,'so_saleorder_b.vbdef3',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5W','-99',0,41,1,null,0,'so_saleorder_b.vbdef4',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5X','-99',0,42,1,null,0,'so_saleorder_b.vbdef5',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5Y','-99',0,43,1,null,0,'so_saleorder_b.vbdef6',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P5Z','-99',0,44,1,null,0,'so_saleorder_b.vbdef7',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P60','-99',0,45,1,null,0,'so_saleorder_b.vbdef8',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P61','-99',0,46,1,null,0,'so_saleorder_b.vbdef9',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P62','-99',0,47,1,null,0,'so_saleorder_b.vbdef10',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P63','-99',0,48,1,null,0,'so_saleorder_b.vbdef11',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P64','-99',0,49,1,null,0,'so_saleorder_b.vbdef12',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P65','-99',0,50,1,null,0,'so_saleorder_b.vbdef13',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P66','-99',0,51,1,null,0,'so_saleorder_b.vbdef14',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P67','-99',0,52,1,null,0,'so_saleorder_b.vbdef15',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P68','-99',0,53,1,null,0,'so_saleorder_b.vbdef16',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P69','-99',0,54,1,null,0,'so_saleorder_b.vbdef17',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P6A','-99',0,55,1,null,0,'so_saleorder_b.vbdef18',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P6B','-99',0,56,1,null,0,'so_saleorder_b.vbdef19',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002P6C','-99',0,57,1,null,0,'so_saleorder_b.vbdef20',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-06-02 13:51:54','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002RJI','普通特征码档案',5,59,1,null,null,'so_saleorder_b.cmffileid',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2015-05-25 18:22:39','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000003RJI','普通特征码档案',5,60,0,null,null,'so_saleorder_b.cmffileid.vskucode',null,null,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,0,null,null,'2015-05-25 18:22:39','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000000824J','物料',5,61,1,null,null,'so_saleorder_b.cmaterialid',null,null,'N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2015-05-25 18:22:39','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000000857V','物料',5,58,0,null,0,'so_saleorder_b.cmaterialid.code',null,null,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,0,null,null,'2015-05-25 18:22:39','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5Y9','采购组织',5,0,1,null,0,'pk_puorg','采购组织',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','Y','Y',null,'N',9999,null,'==','等于@',0,'@@@@','1001Z81000000002V5Y8',null,'UC000-0004091',2,null,null,'2011-03-24 15:25:42','N','#mainorg#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YA','销售组织',5,1,1,null,0,'pk_org',null,null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-05-27 09:02:19','N','#mainorg#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YB','-99',3,2,1,null,0,'dbilldate',null,null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'Y',null,null,'between@=@','介于@等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2010-12-24 14:04:45','N','#month(0)#,#day(0)#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YC','财务组织',5,3,1,null,0,'so_saleorder_b.csettleorgid',null,null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','1001Z81000000002V5Y8',null,'2UC000-000716',2,null,null,'2011-12-26 10:30:13','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YD','影响因素交 易类型',5,4,1,null,0,'ctrantypeid',null,null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',null,null,'=@','等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-03-08 20:14:20','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YE','-99',0,5,1,null,0,'vbillcode',null,null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,40,'=@left like@','等于@左包含@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2011-04-02 12:51:48','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YF','部门',5,6,1,null,0,'cdeptid',null,null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','1001Z81000000002V5Y8',null,'2UC000-000974',2,null,null,'2011-12-21 14:06:48','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z81000000002V5YG','人员',5,7,1,null,0,'cemployeeid',null,null,'N','Y','N','Y','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',null,null,'=@','等于@',0,'@@@@','1001Z81000000002V5Y8',null,null,2,null,null,'2010-11-26 10:09:20','N',null)
go

