insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000018324',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cmffileid',0,'N',1,'Y','N',null,0,'cmffileid','so.delivery_b.cmffileid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'特征码档案,code=N',null,null,'N',0,8,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002IAI',1,-1,null,null,0,0,null,-1,'N',null,-1,'vqtunitrate',null,'N',1,'N','N',null,0,'vqtunitrate','so.delivery_check.vqtunitrate',null,'N',0,null,'1001Z81000000000BLOM',null,1,null,null,null,'N',0,79,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,79)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002IAK',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalnotoutnum',0,'N',1,'N','N',null,0,'ntotalnotoutnum','so.delivery_check.ntotalnotoutnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,80,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,80)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000049KV',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeliverybid',0,'N',1,'N','N',null,0,'cdeliverybid','so.delivery_b.cdeliverybid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,1,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLON',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeliverycid',0,'N',1,'N','N',null,0,'cdeliverycid','so.delivery_check.cdeliverycid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,2,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOO',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.delivery_check.crowno',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,3,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOP',1,-1,null,null,0,0,null,-1,'N',null,-1,'vsrcrowno',0,'N',1,'N','Y',null,0,'vsrcrowno','so.delivery_check.vsrcrowno',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,4,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vcheckcode',0,'N',1,'N','N',null,0,'vcheckcode','so.delivery_check.vcheckcode',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,5,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOR',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','N',null,0,'cmaterialid','so.delivery_check.cmaterialid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'物料,code=N',null,null,'N',0,6,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOS',1,-1,'物料编码',null,0,0,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','Y',null,0,'cmaterialvid','so.delivery_check.cmaterialvid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,'UC000-0002911',null,'N',1,7,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOT',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,8,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOU',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,9,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOV',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,10,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOW',1,-1,'物料版本',null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.version',0,'N',1,'N','Y',null,0,'version','uap.material.version',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,'1400604020002',null,'N',1,11,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOX',1,-1,null,null,0,0,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','so.delivery_check.cvendorid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'供应商档案,code=N',null,null,'N',0,12,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOY',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','so.delivery_check.cprojectid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'项目,code=N',null,null,'N',0,13,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLOZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqualitylevelid',0,'N',1,'N','N',null,0,'cqualitylevelid','so.delivery_check.cqualitylevelid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,14,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP0',1,-1,null,null,0,0,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','so.delivery_check.cproductorid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,15,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP1',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_batchcode',0,'N',1,'N','N',null,0,'pk_batchcode','so.delivery_check.pk_batchcode',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,16,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP2',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbatchcode',0,'N',1,'N','N',null,0,'vbatchcode','so.delivery_check.vbatchcode',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,17,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP3',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','so.delivery_check.castunitid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'计量单位,code=N',null,null,'N',1,18,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP4',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','so.delivery_check.nastnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,19,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP5',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','so.delivery_check.cunitid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'计量单位,code=N',null,null,'N',1,20,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP6',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.delivery_check.nnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,21,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP7',1,-1,null,null,0,0,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','N',null,0,'vchangerate','so.delivery_check.vchangerate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,22,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP8',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqtunitid',0,'N',1,'N','N',null,0,'cqtunitid','so.delivery_check.cqtunitid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'计量单位,code=N',null,null,'N',0,23,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLP9',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqtunitnum',0,'N',1,'N','N',null,0,'nqtunitnum','so.delivery_check.nqtunitnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,24,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPB',1,-1,null,null,0,0,null,-1,'N',null,-1,'dcheckdate',0,'N',1,'N','N',null,0,'dcheckdate','so.delivery_check.dcheckdate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,25,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPC',1,-1,null,'false',0,0,null,-1,'N',null,-1,'blargessflag',0,'N',1,'N','Y',null,0,'blargessflag','so.delivery_check.blargessflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,26,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPD',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccheckstatebid',0,'N',1,'N','Y',null,0,'ccheckstatebid','so.delivery_check.ccheckstatebid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,',code=N',null,null,'N',1,27,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPE',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdefectprocessid',0,'N',1,'N','Y',null,0,'cdefectprocessid','so.delivery_check.cdefectprocessid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,',code=N',null,null,'N',1,28,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPF',1,-1,null,'false',0,0,null,-1,'N',null,-1,'beligflag',0,'N',1,'N','N',null,0,'beligflag','so.delivery_check.beligflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,29,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPG',1,-1,null,'false',0,0,null,-1,'N',null,-1,'bcheckinflag',0,'N',1,'N','N',null,0,'bcheckinflag','so.delivery_check.bcheckinflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,30,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPH',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.delivery_check.corigcurrencyid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'币种档案,code=N',null,null,'N',1,31,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPI',1,-1,null,null,0,0,null,-1,'N',null,-1,'nexchangerate',0,'N',1,'N','Y',null,0,'nexchangerate','so.delivery_check.nexchangerate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,32,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxrate',0,'N',1,'N','Y',null,0,'ntaxrate','so.delivery_check.ntaxrate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,33,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPK',1,-1,null,null,0,0,null,-1,'N',null,-1,'ndiscountrate',0,'N',1,'N','N',null,0,'ndiscountrate','so.delivery_check.ndiscountrate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,34,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPL',1,-1,null,null,0,0,null,-1,'N',null,-1,'nitemdiscountrate',0,'N',1,'N','N',null,0,'nitemdiscountrate','so.delivery_check.nitemdiscountrate',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,35,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPM',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigtaxprice',0,'N',1,'N','N',null,0,'norigtaxprice','so.delivery_check.norigtaxprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,36,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPN',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigprice',0,'N',1,'N','N',null,0,'norigprice','so.delivery_check.norigprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,37,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPO',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigtaxnetprice',0,'N',1,'N','N',null,0,'norigtaxnetprice','so.delivery_check.norigtaxnetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,38,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPP',1,-1,null,null,0,0,null,-1,'N',null,-1,'norignetprice',0,'N',1,'N','N',null,0,'norignetprice','so.delivery_check.norignetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,39,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqtorigtaxprice',0,'N',1,'N','N',null,0,'nqtorigtaxprice','so.delivery_check.nqtorigtaxprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,40,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPR',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqtorigprice',0,'N',1,'N','N',null,0,'nqtorigprice','so.delivery_check.nqtorigprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,41,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPS',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorigtaxnetprc',0,'N',1,'N','Y',null,0,'nqtorigtaxnetprc','so.delivery_check.nqtorigtaxnetprc',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,42,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPT',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtorignetprice',0,'N',1,'N','Y',null,0,'nqtorignetprice','so.delivery_check.nqtorignetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,43,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPV',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigmny',0,'N',1,'N','Y',null,0,'norigmny','so.delivery_check.norigmny',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,45,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPW',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigtaxmny',0,'N',1,'N','Y',null,0,'norigtaxmny','so.delivery_check.norigtaxmny',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,46,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPX',1,-1,null,null,0,0,null,-1,'N',null,-1,'norigdiscount',0,'N',1,'N','N',null,0,'norigdiscount','so.delivery_check.norigdiscount',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,47,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPY',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxprice',0,'N',1,'N','N',null,0,'ntaxprice','so.delivery_check.ntaxprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,48,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLPZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'nprice',0,'N',1,'N','N',null,0,'nprice','so.delivery_check.nprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,49,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ0',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxnetprice',0,'N',1,'N','N',null,0,'ntaxnetprice','so.delivery_check.ntaxnetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,50,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ1',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnetprice',0,'N',1,'N','N',null,0,'nnetprice','so.delivery_check.nnetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,51,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ2',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqttaxprice',0,'N',1,'N','N',null,0,'nqttaxprice','so.delivery_check.nqttaxprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,52,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,52)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ3',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqtprice',0,'N',1,'N','N',null,0,'nqtprice','so.delivery_check.nqtprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,53,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ4',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqttaxnetprice',0,'N',1,'N','Y',null,0,'nqttaxnetprice','so.delivery_check.nqttaxnetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,54,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,54)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ5',1,-1,null,null,0,0,null,-1,'N',null,-1,'nqtnetprice',0,'N',1,'N','Y',null,0,'nqtnetprice','so.delivery_check.nqtnetprice',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,55,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,55)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ6',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntax',0,'N',1,'N','Y',null,0,'ntax','so.delivery_check.ntax',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,56,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,56)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ7',1,-1,null,null,0,0,null,-1,'N',null,-1,'nmny',0,'N',1,'N','Y',null,0,'nmny','so.delivery_check.nmny',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,57,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,57)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ8',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxmny',0,'N',1,'N','Y',null,0,'ntaxmny','so.delivery_check.ntaxmny',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,58,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQ9',1,-1,null,null,0,0,null,-1,'N',null,-1,'ndiscount',0,'N',1,'N','Y',null,0,'ndiscount','so.delivery_check.ndiscount',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,59,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,59)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQA',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','so.delivery_check.ccurrencyid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'币种档案,code=N',null,null,'N',0,60,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,60)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQB',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotaltransnum',0,'N',1,'N','N',null,0,'ntotaltransnum','so.delivery_check.ntotaltransnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,61,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,61)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQC',1,-1,null,'false',0,0,null,-1,'N',null,-1,'btransendflag',0,'N',1,'N','N',null,0,'btransendflag','so.delivery_check.btransendflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,62,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,62)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQD',1,-1,'已出库主数量',null,0,0,null,-1,'N',null,-1,'ntotaloutnum',0,'N',1,'N','Y',null,0,'ntotaloutnum','so.delivery_check.ntotaloutnum',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,'1400604020005',null,'N',1,63,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,63)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQE',1,-1,null,'false',0,0,null,-1,'N',null,-1,'boutendflag',0,'N',1,'N','N',null,0,'boutendflag','so.delivery_check.boutendflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,64,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,64)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQF',1,-1,null,null,0,0,null,-1,'N',null,-1,'vrownote',0,'N',1,'N','N',null,0,'vrownote','so.delivery_check.vrownote',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,65,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,65)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQG',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.delivery_check.ts',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,66,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,66)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQH',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','Y',null,0,'vfree1','so.delivery_check.vfree1',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,67,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQI',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','Y',null,0,'vfree2','so.delivery_check.vfree2',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,68,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,68)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','Y',null,0,'vfree3','so.delivery_check.vfree3',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,69,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,69)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQK',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','Y',null,0,'vfree4','so.delivery_check.vfree4',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,70,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,70)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQL',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','Y',null,0,'vfree5','so.delivery_check.vfree5',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,71,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQM',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','Y',null,0,'vfree6','so.delivery_check.vfree6',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,72,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,72)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQN',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','Y',null,0,'vfree7','so.delivery_check.vfree7',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,73,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,73)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQO',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','Y',null,0,'vfree8','so.delivery_check.vfree8',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,74,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,74)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQP',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','Y',null,0,'vfree9','so.delivery_check.vfree9',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,75,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,75)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','Y',null,0,'vfree10','so.delivery_check.vfree10',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,76,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,76)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BLQR',1,-1,null,'false',0,0,null,-1,'N',null,-1,'bpricechgflag',0,'N',1,'N','Y',null,0,'bpricechgflag','so.delivery_check.bpricechgflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',1,77,'cdeliverycid','发货单质检信息',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,77)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080I',1,-1,null,null,0,0,null,-1,'N',null,-1,'ncaltaxmny',0,'N',1,'N','N',null,0,'ncaltaxmny','so.delivery_check.ncaltaxmny',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,91,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,91)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080J',1,-1,null,null,0,0,null,-1,'N',null,-1,'crececountryid',0,'N',1,'N','N',null,0,'crececountryid','so.delivery_check.crececountryid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'国家地区,code=N',null,null,'N',0,81,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,81)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080K',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigareaid',0,'N',1,'N','N',null,0,'corigareaid','so.delivery_check.corigareaid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'行政区划,code=N',null,null,'N',0,90,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,90)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080L',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctaxcountryid',0,'N',1,'N','N',null,0,'ctaxcountryid','so.delivery_check.ctaxcountryid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'国家地区,code=N',null,null,'N',0,83,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,83)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080M',1,-1,null,null,0,0,null,-1,'N',null,-1,'fbuysellflag',0,'N',1,'N','N',null,0,'fbuysellflag','so.delivery_check.fbuysellflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,84,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,84)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080N',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctaxcodeid',0,'N',1,'N','N',null,0,'ctaxcodeid','so.delivery_check.ctaxcodeid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,86,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,86)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080O',1,-1,null,null,0,0,null,-1,'N',null,-1,'csendcountryid',0,'N',1,'N','N',null,0,'csendcountryid','so.delivery_check.csendcountryid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'国家地区,code=N',null,null,'N',0,82,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,1,1,'N',1,null,100,82)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080P',1,-1,null,null,0,0,null,-1,'N',null,-1,'btriatradeflag',0,'N',1,'N','N',null,0,'btriatradeflag','so.delivery_check.btriatradeflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,85,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,85)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcountryid',0,'N',1,'N','N',null,0,'corigcountryid','so.delivery_check.corigcountryid',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'国家地区,code=N',null,null,'N',0,88,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,88)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001080R',1,-1,null,null,0,0,null,-1,'N',null,-1,'ftaxtypeflag',0,'N',1,'N','N',null,0,'ftaxtypeflag','so.delivery_check.ftaxtypeflag',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,null,null,null,'N',0,87,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',1,null,100,87)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z8100000000019JR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.delivery_check.pk_group',null,'N',0,null,'1001Z81000000000BLOM','@@@@',1,'集团,code=N',null,null,'N',0,78,'cdeliverycid','cdeliverycid',0,'2015-07-07 16:34:09','N',null,null,null,0,1,'N',0,null,100,78)
go

