insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000018328',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cmffileid',0,'N',1,'Y','N',null,0,'cmffileid','so.delivery_b.cmffileid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,'特征码档案,code=N',null,null,'N',0,29,'delivery','发货单主表',0,'2015-03-25 20:06:16','N',null,null,null,0,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002AQ5',1,-1,null,null,0,0,null,-1,'N',null,-1,'csenddeptid',0,'N',1,'N','N',null,0,'csenddeptid','so.delivery.csenddeptid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,14,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002AQ6',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendemployeeid',0,'N',1,'N','Y',null,0,'csendemployeeid','so.delivery.csendemployeeid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,7,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002AQ7',1,-1,null,null,0,1,null,-1,'N',null,-1,'csenddeptvid',0,'N',1,'N','Y',null,0,'csenddeptvid','so.delivery.csenddeptvid','csenddeptid=pk_dept','N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,8,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002AQ8',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctradewordid',0,'N',1,'N','Y',null,0,'ctradewordid','so.delivery.ctradewordid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,6,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002IB0',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalnotoutnum',0,'N',1,'N','N',null,0,'ntotalnotoutnum','so.delivery_b.ntotalnotoutnum',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,71,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005DTH',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccustmaterialid',0,'N',1,'N','N',null,0,'ccustmaterialid','so.delivery_b.ccustmaterialid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,22,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000H02N',1,-1,null,null,0,0,null,-1,'N','ccustmaterialid',-1,'ccustmaterialid.name',0,'N',1,'N','N',null,0,'name','uapbd.custmaterial.name',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,23,'delivery','delivery',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3D',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.delivery_b.crowno',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,0,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3E',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeliveryid',0,'N',1,'N','N',null,0,'cdeliveryid','so.delivery.cdeliveryid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,2,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3F',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.delivery.pk_group',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,3,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3G',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.delivery.pk_org','pk_org_v=pk_vid','N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,4,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',0,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3H',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','Y',null,0,'ctrantypeid','so.delivery.ctrantypeid','vtrantypecode=pk_billtypecode','N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,1,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3I',1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.delivery.vtrantypecode',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,6,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3J',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','so.delivery.pk_org_v',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,'1400604020001',null,'N',1,2,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',0,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3K',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.delivery.vbillcode',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,3,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3L',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbiztypeid',0,'N',1,'N','N',null,0,'cbiztypeid','so.delivery.cbiztypeid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,9,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3M',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.delivery.dbilldate',null,'N',1,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,4,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctransporttypeid',0,'N',1,'N','Y',null,0,'ctransporttypeid','so.delivery.ctransporttypeid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,5,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3R',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctransportrouteid',0,'N',1,'N','Y',null,0,'ctransportrouteid','so.delivery.ctransportrouteid',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,9,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3S',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalastnum',0,'N',1,'N','Y',null,0,'ntotalastnum','so.delivery.ntotalastnum',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,10,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3T',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalweight',0,'N',1,'N','Y',null,0,'ntotalweight','so.delivery.ntotalweight',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,11,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3U',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalvolume',0,'N',1,'N','Y',null,0,'ntotalvolume','so.delivery.ntotalvolume',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,12,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3V',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalpiece',0,'N',1,'N','Y',null,0,'ntotalpiece','so.delivery.ntotalpiece',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,13,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3W',1,-1,null,'1',0,0,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','Y',null,0,'fstatusflag','so.delivery.fstatusflag',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,'UC000-0000804',null,'N',1,14,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3X',1,-1,null,null,0,0,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.delivery.vnote',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,15,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef1',0,'N',1,'N','N',null,0,'vdef1','so.delivery.vdef1',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,23,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A3Z',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef2',0,'N',1,'N','N',null,0,'vdef2','so.delivery.vdef2',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,25,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A40',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef3',0,'N',1,'N','N',null,0,'vdef3','so.delivery.vdef3',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,25,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A41',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef4',0,'N',1,'N','N',null,0,'vdef4','so.delivery.vdef4',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,26,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A42',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef5',0,'N',1,'N','N',null,0,'vdef5','so.delivery.vdef5',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,29,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A43',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef6',0,'N',1,'N','N',null,0,'vdef6','so.delivery.vdef6',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,30,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A44',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef7',0,'N',1,'N','N',null,0,'vdef7','so.delivery.vdef7',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,31,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A45',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef8',0,'N',1,'N','N',null,0,'vdef8','so.delivery.vdef8',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,33,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A46',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef9',0,'N',1,'N','N',null,0,'vdef9','so.delivery.vdef9',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,34,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A47',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef10',0,'N',1,'N','N',null,0,'vdef10','so.delivery.vdef10',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,35,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A48',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef11',0,'N',1,'N','N',null,0,'vdef11','so.delivery.vdef11',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,36,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A49',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef12',0,'N',1,'N','N',null,0,'vdef12','so.delivery.vdef12',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,36,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4A',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef13',0,'N',1,'N','N',null,0,'vdef13','so.delivery.vdef13',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,38,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4B',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef14',0,'N',1,'N','N',null,0,'vdef14','so.delivery.vdef14',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,38,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4C',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef15',0,'N',1,'N','N',null,0,'vdef15','so.delivery.vdef15',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,40,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4D',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef16',0,'N',1,'N','N',null,0,'vdef16','so.delivery.vdef16',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,41,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4E',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef17',0,'N',1,'N','N',null,0,'vdef17','so.delivery.vdef17',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,42,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4F',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef18',0,'N',1,'N','N',null,0,'vdef18','so.delivery.vdef18',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,43,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4G',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef19',0,'N',1,'N','N',null,0,'vdef19','so.delivery.vdef19',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,44,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4H',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef20',0,'N',1,'N','N',null,0,'vdef20','so.delivery.vdef20',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,45,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4I',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.delivery.ts',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,48,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4J',1,-1,null,null,0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','so.delivery.billmaker',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,16,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4K',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','so.delivery.creationtime',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,17,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4L',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','so.delivery.creator',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',0,67,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4M',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','so.delivery.approver',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,18,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4N',1,-1,null,null,0,0,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','so.delivery.taudittime',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,19,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4O',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','so.delivery.modifier',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,20,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4P',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','so.delivery.modifiedtime',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,21,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'cordercustid',0,'N',1,'N','Y',null,0,'cordercustid','so.delivery_b.cordercustid',null,'N',1,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,'UC000-0001611',null,'N',1,24,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4R',1,-1,null,null,0,0,null,-1,'N','cordercustid',-1,'cordercustid.name',0,'N',1,'N','Y',null,0,'name','uap.customer.name',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,24,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4S',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','Y',null,0,'cmaterialvid','so.delivery_b.cmaterialvid',null,'N',1,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,'物料（多版本）,code=Y',null,null,'N',1,26,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4T',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,27,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4U',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,30,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4V',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,31,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4W',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','so.delivery_b.castunitid',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,'计量单位,code=N','1400604020008',null,'N',1,32,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4X',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','so.delivery_b.nastnum',null,'N',1,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,32,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','so.delivery_b.cunitid',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,33,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A4Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.delivery_b.nnum',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,34,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A50',1,-1,null,null,0,0,null,-1,'N',null,-1,'nweight',0,'N',1,'N','Y',null,0,'nweight','so.delivery_b.nweight',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,35,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A51',1,-1,null,null,0,0,null,-1,'N',null,-1,'nvolume',0,'N',1,'N','Y',null,0,'nvolume','so.delivery_b.nvolume',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,37,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A52',1,-1,null,null,0,0,null,-1,'N',null,-1,'npiece',0,'N',1,'N','Y',null,0,'npiece','so.delivery_b.npiece',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,37,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A53',1,-1,null,'false',0,0,null,-1,'N',null,-1,'blargessflag',0,'N',1,'N','Y',null,0,'blargessflag','so.delivery_b.blargessflag',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,39,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A54',1,-1,null,'false',0,1,null,-1,'N',null,-1,'boutendflag',0,'N',1,'N','N',null,0,'boutendflag','so.delivery_b.boutendflag',null,'N',0,null,'1003Z810000000001A3C','@@@@',0,null,'1400604020003',null,'N',0,69,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,69)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001A55',1,-1,null,null,0,0,null,-1,'N',null,-1,'frownote',0,'N',1,'N','Y',null,0,'frownote','so.delivery_b.frownote',null,'N',0,'<root><tab code="sharecode" showflag="N" listshowflag="N" /></root>','1003Z810000000001A3C','@@@@',0,null,null,null,'N',1,39,'delivery','发货单主表',0,'2012-12-10 13:19:48','N',null,null,null,1,1,'N',1,null,1,39)
go

