/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.so.base.entity;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:${vmObject.createdDate}
 * 
 * @author
 * @version NCPrj ??
 */
public class AllowSale extends MDEnum {

  // 允许销售
  public static final AllowSale ALLOW_SALE = MDEnum.valueOf(AllowSale.class,
      Integer.valueOf(1));

  // 禁止销售
  public static final AllowSale FORBID_SALE = MDEnum.valueOf(AllowSale.class,
      Integer.valueOf(2));

  public AllowSale(IEnumValue enumvalue) {
    super(enumvalue);
  }

  public int getIntValue() {
    return Integer.parseInt(this.value().toString());
  }

  public Integer getIntegerValue() {
    return Integer.valueOf(this.value().toString());
  }

  public String getStringValue() {
    return this.value().toString();
  }

}
