insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000018330',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cmffileid',0,'N',1,'Y','N',null,0,'cmffileid','so.delivery_b.cmffileid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'特征码档案,code=N',null,null,'N',0,6,'cdeliverybid','物料信息',0,'2015-03-25 20:06:16','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000IAYM',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccustmaterialid',0,'N',1,'N','N',null,0,'ccustmaterialid','so.delivery_b.ccustmaterialid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,null,null,null,'N',0,3,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000IAYN',1,-1,null,null,0,0,null,-1,'N','ccustmaterialid',-1,'ccustmaterialid.name',0,'N',1,'N','N',null,0,'name','uapbd.custmaterial.name',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,null,null,null,'N',0,4,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8VX',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.delivery.pk_group',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,'集团',null,null,'N',0,2,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8VY',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.delivery.pk_org','pk_org_v=pk_vid','N',0,null,'1002Z81000000001C8VV','@@@@',0,'物流组织',null,null,'N',0,3,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',0,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8VZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','so.delivery.pk_org_v',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,'物流组织版本','1400604020001',null,'N',0,4,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',0,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W0',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','so.delivery.vbillcode',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,5,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W1',1,-1,null,null,0,0,null,-1,'N',null,-1,'cbiztypeid',0,'N',1,'N','N',null,0,'cbiztypeid','so.delivery.cbiztypeid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,'业务流程',null,null,'N',0,6,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W2',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','Y',null,0,'ctrantypeid','so.delivery.ctrantypeid','vtrantypecode=pk_billtypecode','N',1,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,7,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W4',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','so.delivery.dbilldate',null,'N',1,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,9,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W5',1,-1,null,null,0,1,'rowcount->getrowcount("bd_psnjob","pk_psndoc" ,csendemployeeid,null,null);csenddeptid->iif(rowcount==1,getcolvalue(bd_psnjob ,pk_dept ,pk_psndoc ,csendemployeeid ),csenddeptid);csenddeptvid->iif(rowcount==1,getcolvalue(org_dept ,pk_vid , pk_dept , csenddeptid),csenddeptvid);',-1,'N',null,-1,'csendemployeeid',0,'N',1,'N','Y',null,0,'csendemployeeid','so.delivery.csendemployeeid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,10,'delivery','delivery',0,'2013-06-18 16:29:05','N',null,null,null,1,0,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W7',1,-1,null,null,0,1,null,-1,'N',null,-1,'csenddeptvid',0,'N',1,'N','Y',null,0,'csenddeptvid','so.delivery.csenddeptvid','csenddeptid=pk_dept','N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,12,'delivery','delivery',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8W8',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctransporttypeid',0,'N',1,'N','Y',null,0,'ctransporttypeid','so.delivery.ctransporttypeid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,13,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WA',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctransportrouteid',0,'N',1,'N','Y',null,0,'ctransportrouteid','so.delivery.ctransportrouteid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,15,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WB',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalastnum',0,'N',1,'N','Y',null,0,'ntotalastnum','so.delivery.ntotalastnum',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,16,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WC',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalweight',0,'N',1,'N','Y',null,0,'ntotalweight','so.delivery.ntotalweight',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,17,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WD',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalvolume',0,'N',1,'N','Y',null,0,'ntotalvolume','so.delivery.ntotalvolume',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,18,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WE',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalpiece',0,'N',1,'N','Y',null,0,'ntotalpiece','so.delivery.ntotalpiece',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,19,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WF',1,-1,null,'1',0,0,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','Y',null,0,'fstatusflag','so.delivery.fstatusflag',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,20,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8WG',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.delivery.vnote',null,'N',0,null,'1002Z81000000001C8VV','@@@@',0,null,null,null,'N',1,21,'delivery','发货单主表',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8X4',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.delivery_b.pk_org',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'物流组织,code=N',null,null,'N',0,3,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',0,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8X6',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.delivery_b.crowno',null,'N',0,'<root><tab code="send" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,0,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8X7',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cordercustid',0,'N',1,'Y','Y',null,0,'cordercustid','so.delivery_b.cordercustid',null,'N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'客户档案,dpc=SCMDefault',null,null,'N',1,1,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8X8',1,-1,null,null,0,0,null,-1,'N','cordercustid',-1,'cordercustid.name',0,'N',1,'N','Y',null,0,'name','uap.customer.name',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,2,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8X9',1,-1,null,null,0,0,null,-1,'N',null,-1,'cfreecustid',0,'N',1,'N','N',null,0,'cfreecustid','so.delivery_b.cfreecustid',null,'N',0,'<root><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'散户,code=N',null,null,'N',0,9,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XA',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cinvoicecustid',0,'N',1,'Y','N',null,0,'cinvoicecustid','so.delivery_b.cinvoicecustid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'客户档案,code=N',null,null,'N',0,9,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XC',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cmaterialvid',0,'N',1,'Y','Y',null,0,'cmaterialvid','so.delivery_b.cmaterialvid','cmaterialid=pk_source,cunitid=pk_measdoc,nweight=unitweight,nvolume=unitvolume,cprodlineid=pk_prodline','N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'物料（多版本）',null,null,'N',1,5,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XD',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,6,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XE',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,7,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XF',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,8,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XG',1,-1,null,null,0,0,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','so.delivery_b.cvendorid',null,'N',0,'<root><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'供应商档案,code=N',null,null,'N',0,15,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XH',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','so.delivery_b.cprojectid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'项目,code=N',null,null,'N',0,16,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'corigcountryid',0,'N',1,'N','N',null,0,'corigcountryid','so.delivery_b.corigcountryid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'国家地区,code=N',null,null,'N',0,19,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XK',1,-1,null,null,0,1,null,-1,'N',null,-1,'corigareaid',0,'N',1,'N','N',null,0,'corigareaid','so.delivery_b.corigareaid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'行政区划,code=N',null,null,'N',0,20,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XL',1,-1,null,null,0,0,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','so.delivery_b.cproductorid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,26,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XM',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','so.delivery_b.castunitid',null,'N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'计量单位,code=N',null,null,'N',1,8,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XN',1,-1,null,null,0,1,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','so.delivery_b.nastnum',null,'N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,10,'cdeliverybid','物料信息',1,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XO',1,-1,null,null,0,1,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','so.delivery_b.cunitid',null,'N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'计量单位,code=N',null,null,'N',1,11,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XP',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',0,'N',1,'N','Y',null,0,'nnum','so.delivery_b.nnum',null,'N',1,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,12,'cdeliverybid','物料信息',1,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XR',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqtunitid',0,'N',1,'N','N',null,0,'cqtunitid','so.delivery_b.cqtunitid',null,'N',0,'<root><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'计量单位,code=N',null,null,'N',0,40,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8XZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'nweight',0,'N',1,'N','Y',null,0,'nweight','so.delivery_b.nweight',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,13,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Y0',1,-1,null,null,0,1,null,-1,'N',null,-1,'nvolume',0,'N',1,'N','Y',null,0,'nvolume','so.delivery_b.nvolume',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,14,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Y1',1,-1,null,null,0,1,null,-1,'N',null,-1,'npiece',0,'N',1,'N','Y',null,0,'npiece','so.delivery_b.npiece',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,15,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Y2',1,-1,null,null,0,1,null,-1,'N',null,-1,'blargessflag',0,'N',1,'N','Y',null,0,'blargessflag','so.delivery_b.blargessflag',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,16,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Y5',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','N',null,0,'corigcurrencyid','so.delivery_b.corigcurrencyid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'币种档案,code=N',null,null,'N',0,42,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Y7',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','so.delivery_b.ccurrencyid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'币种档案,code=N',null,null,'N',0,70,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,70)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Z1',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfirsttype',0,'N',1,'N','N',null,0,'vfirsttype','so.delivery_b.vfirsttype',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'影响因素单据类型,code=N',null,null,'N',0,72,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,72)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Z3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfirsttrantype',0,'N',1,'N','N',null,0,'vfirsttrantype','so.delivery_b.vfirsttrantype',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',0,74,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,74)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Z7',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsrctype',0,'N',1,'N','N',null,0,'vsrctype','so.delivery_b.vsrctype',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'影响因素单据类型,code=N',null,null,'N',0,78,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,78)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8Z9',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsrctrantype',0,'N',1,'N','N',null,0,'vsrctrantype','so.delivery_b.vsrctrantype',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',0,80,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,80)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZE',1,-1,null,null,0,1,null,-1,'N',null,-1,'csaleorgvid',0,'N',1,'N','N',null,0,'csaleorgvid','so.delivery_b.csaleorgvid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'销售组织版本,code=N',null,null,'N',0,85,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,85)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZG',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendstockorgvid',0,'N',1,'N','N',null,0,'csendstockorgvid','so.delivery_b.csendstockorgvid','csendstockorgid=pk_stockorg','N',1,'<root><tab code="send" showflag="Y" listshowflag="Y" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'库存组织版本,code=N',null,null,'N',0,87,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,87)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZH',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendstordocid',0,'N',1,'N','N',null,0,'csendstordocid','so.delivery_b.csendstordocid',null,'N',0,'<root><tab code="send" showflag="Y" listshowflag="Y" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'仓库,code=N',null,null,'N',0,88,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,88)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZI',1,-1,null,null,0,1,null,-1,'Y',null,-1,'creceivecustid',0,'N',1,'Y','N',null,0,'creceivecustid','so.delivery_b.creceivecustid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'客户档案,code=N',null,null,'N',0,90,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,90)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'creceiveareaid',0,'N',1,'N','N',null,0,'creceiveareaid','so.delivery_b.creceiveareaid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'地区分类,code=N',null,null,'N',0,91,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,91)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZK',1,-1,null,null,0,1,null,-1,'N',null,-1,'creceiveadddocid',0,'N',1,'N','N',null,0,'creceiveadddocid','so.delivery_b.creceiveadddocid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'地点档案,code=N',null,null,'N',0,92,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,92)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZL',1,-1,null,null,0,1,null,-1,'N',null,-1,'creceiveaddrid',0,'N',1,'N','N','formataddress(creceiveaddrid_ID)',0,'creceiveaddrid','so.delivery_b.creceiveaddrid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'地址簿,code=N',null,null,'N',0,93,'cdeliverybid','物料信息',0,'2013-06-18 16:29:05','N',null,null,null,1,1,'N',1,null,100,93)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZN',1,-1,null,null,0,1,null,-1,'N',null,-1,'cinstockorgvid',0,'N',1,'N','N',null,0,'cinstockorgvid','so.delivery_b.cinstockorgvid','cinstockorgid=pk_stockorg','N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'库存组织版本,code=N',null,null,'N',0,95,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,95)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZO',1,-1,null,null,0,1,null,-1,'N',null,-1,'cinstordocid',0,'N',1,'N','N',null,0,'cinstordocid','so.delivery_b.cinstordocid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'仓库,code=N',null,null,'N',0,96,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,96)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'creceivepersonid',0,'N',1,'N','N',null,0,'creceivepersonid','so.delivery_b.creceivepersonid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'人员,code=N',null,null,'N',0,98,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,98)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZR',1,-1,null,null,0,1,null,-1,'N',null,-1,'csupercargoid',0,'N',1,'N','N',null,0,'csupercargoid','so.delivery_b.csupercargoid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'人员,code=N',null,null,'N',0,101,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctranscustid',0,'N',1,'N','N','ctranscustid.csupplierid',0,'ctranscustid','so.delivery_b.ctranscustid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'承运商定义,code=N',null,null,'N',0,100,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZT',1,-1,null,null,0,0,null,-1,'N','ctranscustid',-1,'ctranscustid.csupplierid',0,'N',1,'N','N',null,0,'csupplierid','scmpub.dm_carrier.csupplierid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'供应商档案,code=N','1400604020052',null,'N',0,101,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',0,null,100,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZU',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvehicletypeid',0,'N',1,'N','N',null,0,'cvehicletypeid','so.delivery_b.cvehicletypeid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'车型定义,code=N',null,null,'N',0,102,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZV',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvehicleid',0,'N',1,'N','N',null,0,'cvehicleid','so.delivery_b.cvehicleid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'车辆定义,code=N',null,null,'N',0,103,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,103)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZW',1,-1,null,null,0,1,null,-1,'N',null,-1,'cchauffeurid',0,'N',1,'N','N',null,0,'cchauffeurid','so.delivery_b.cchauffeurid',null,'N',0,'<root><tab code="transport" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'司机定义,code=N',null,null,'N',0,104,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,104)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZX',1,-1,null,null,0,1,null,-1,'N',null,-1,'cspaceid',0,'N',1,'N','N',null,0,'cspaceid','so.delivery_b.cspaceid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'货位,code=N',null,null,'N',0,105,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,105)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C8ZY',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','N',null,0,'cprodlineid','so.delivery_b.cprodlineid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'产品线,code=N',null,null,'N',0,106,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,106)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C903',1,-1,null,null,0,1,null,-1,'N',null,-1,'frownote',0,'N',1,'N','Y',null,0,'frownote','so.delivery_b.frownote',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,null,null,null,'N',1,18,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C90Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendpersonid',0,'N',1,'N','N',null,0,'csendpersonid','so.delivery_b.csendpersonid',null,'N',0,'<root><tab code="send" showflag="Y" listshowflag="Y" /><tab code="transport" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'人员,code=N',null,null,'N',0,142,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,142)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C910',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendareaid',0,'N',1,'N','N',null,0,'csendareaid','so.delivery_b.csendareaid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'地区分类,code=N',null,null,'N',0,144,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,144)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C911',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendadddocid',0,'N',1,'N','N',null,0,'csendadddocid','so.delivery_b.csendadddocid',null,'N',0,'<root><tab code="send" showflag="Y" listshowflag="Y" /></root>','1002Z81000000001C8VV','@@@@',1,'地点档案,code=N',null,null,'N',0,145,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,145)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C912',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendaddrid',0,'N',1,'N','N','formataddress(csendaddrid_ID)',0,'csendaddrid','so.delivery_b.csendaddrid',null,'N',0,'<root><tab code="send" showflag="N" listshowflag="N" /></root>','1002Z81000000001C8VV','@@@@',1,'地址簿,code=N',null,null,'N',0,146,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,146)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C914',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprofitcenterid',0,'N',1,'N','N',null,0,'cprofitcenterid','so.delivery_b.cprofitcenterid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'利润中心,code=N',null,null,'N',0,148,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,148)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C915',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprofitcentervid',0,'N',1,'N','N',null,0,'cprofitcentervid','so.delivery_b.cprofitcentervid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'利润中心版本,code=N',null,null,'N',0,149,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,149)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C916',1,-1,null,null,0,1,null,-1,'N',null,-1,'carorgid',0,'N',1,'N','N',null,0,'carorgid','so.delivery_b.carorgid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'财务组织,code=N',null,null,'N',0,150,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,150)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C917',1,-1,null,null,0,1,null,-1,'N',null,-1,'carorgvid',0,'N',1,'N','N',null,0,'carorgvid','so.delivery_b.carorgvid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'财务组织版本,code=N',null,null,'N',0,151,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,151)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C918',1,-1,null,null,0,1,null,-1,'N',null,-1,'csettleorgid',0,'N',1,'N','N',null,0,'csettleorgid','so.delivery_b.csettleorgid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'财务组织,code=N',null,null,'N',0,152,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,152)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C919',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','N',null,0,'cdeptid','so.delivery_b.cdeptid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'部门,code=N',null,null,'N',0,153,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,153)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91A',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeptvid',0,'N',1,'N','N',null,0,'cdeptvid','so.delivery_b.cdeptvid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'部门版本,code=N',null,null,'N',0,154,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,154)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91B',1,-1,null,null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','N',null,0,'cemployeeid','so.delivery_b.cemployeeid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'人员,code=N',null,null,'N',0,155,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,155)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91C',1,-1,null,null,0,1,null,-1,'N',null,-1,'csettleorgvid',0,'N',1,'N','N',null,0,'csettleorgvid','so.delivery_b.csettleorgvid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'财务组织版本,code=N',null,null,'N',0,156,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,156)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91D',1,-1,null,null,0,0,null,-1,'N',null,-1,'crececountryid',0,'N',1,'N','N',null,0,'crececountryid','so.delivery_b.crececountryid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'国家地区,code=N',null,null,'N',0,157,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',1,null,100,157)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91E',1,-1,null,null,0,0,null,-1,'N',null,-1,'csendcountryid',0,'N',1,'N','N',null,0,'csendcountryid','so.delivery_b.csendcountryid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'国家地区,code=N',null,null,'N',0,158,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',1,null,100,158)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91F',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctaxcountryid',0,'N',1,'N','N',null,0,'ctaxcountryid','so.delivery_b.ctaxcountryid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'国家地区,code=N',null,null,'N',0,159,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',1,null,100,159)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91K',1,-1,null,null,0,1,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','N',null,0,'cchanneltypeid','so.delivery_b.cchanneltypeid',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'渠道类型,code=N',null,null,'N',0,164,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,164)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91U',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.delivery_b.pk_group',null,'N',0,null,'1002Z81000000001C8VV','@@@@',1,'集团,code=N',null,null,'N',0,174,'cdeliverybid','物料信息',0,'2012-12-12 15:55:59','N',null,null,null,0,1,'N',0,null,100,174)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C91W',1,-1,null,null,0,1,null,-1,'N',null,-1,'cretreasonid',0,'N',1,'N','N',null,0,'cretreasonid','so.delivery_b.cretreasonid','vreturnmode=vreturnmode','N',0,null,'1002Z81000000001C8VV','@@@@',1,'退货原因,code=N',null,null,'N',0,176,'cdeliverybid','cdeliverybid',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,100,176)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C928',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','so.delivery.creator',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,101,'delieverytail2','delieverytail2',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C929',1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','so.delivery.billmaker',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,101,'deliverytail1','deliverytail1',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,101)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92A',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','so.delivery.creationtime',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,102,'delieverytail2','delieverytail2',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92B',1,-1,null,null,0,1,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','so.delivery.dmakedate',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,102,'deliverytail1','deliverytail1',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,102)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92C',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','so.delivery.modifier',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,103,'delieverytail2','delieverytail2',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,103)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92D',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','so.delivery.approver',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,103,'deliverytail1','deliverytail1',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,103)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92E',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','so.delivery.modifiedtime',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,null,null,'N',1,104,'delieverytail2','delieverytail2',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,104)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001C92F',1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','so.delivery.taudittime',null,'N',0,null,'1002Z81000000001C8VV','@@@@',2,null,'1400603010095',null,'N',1,104,'deliverytail1','deliverytail1',0,'2012-12-12 15:55:59','N',null,null,null,1,1,'N',1,null,1,104)
go

