insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001101C',1,-1,null,null,0,0,null,-1,'N',null,-1,'cdeliveryid',null,'N',1,'N','N',null,0,'cdeliveryid','so.delivery.cdeliveryid',null,'N',0,null,'1002Z810000000010ZZ3',null,0,null,null,null,'N',0,2,'delivery','发货单主表',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI2',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.delivery.vbillcode',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,null,null,'N',1,1,'delivery','delivery',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI3',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','so.delivery.pk_org',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,null,null,'N',1,0,'delivery','delivery',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI5',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','N',null,0,'castunitid','so.delivery_b.castunitid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,'计量单位,code=N',null,null,'N',0,6,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI6',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalastnum',0,'N',1,'N','N',null,0,'ntotalastnum','so.delivery.ntotalastnum',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,null,null,'N',0,8,'delivery','delivery',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI7',1,-1,null,null,0,0,null,-1,'N',null,-1,'csendstordocid',0,'N',1,'N','Y',null,0,'csendstordocid','so.delivery_b.csendstordocid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,'仓库,code=N',null,null,'N',1,7,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI8',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','N',null,0,'nastnum','so.delivery_b.nastnum',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,null,null,'N',0,4,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OI9',1,-1,null,null,0,0,null,-1,'N',null,-1,'creceiveareaid',0,'N',1,'N','Y',null,0,'creceiveareaid','so.delivery_b.creceiveareaid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,'地区分类,code=N',null,null,'N',1,13,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIA',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctransporttypeid',0,'N',1,'N','Y',null,0,'ctransporttypeid','so.delivery.ctransporttypeid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,null,null,'N',1,4,'delivery','delivery',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIB',1,-1,null,null,0,0,null,-1,'N','cordercustid',-1,'cordercustid.name',0,'N',1,'N','N',null,0,'name','uap.customer.name',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,'1400604020059',null,'N',0,0,'body','发货单移动审批表体',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIC',1,-1,null,null,0,0,null,-1,'N',null,-1,'csendstockorgvid',0,'N',1,'N','Y',null,0,'csendstockorgvid','so.delivery_b.csendstockorgvid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,'库存组织版本,code=N',null,null,'N',1,5,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OID',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','N',null,0,'name','uap.material.name',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,null,null,'N',0,3,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIE',1,0,null,null,0,0,null,-1,'N',null,20,'digest',0,'N',1,'N','N','digest->cordercustid+cmaterialvid+disp_nastnum',0,null,null,null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,'2SCMPUB-000045',null,'N',0,0,'body','发货单移动审批表体',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIF',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','Y',null,0,'cmaterialvid','so.delivery_b.cmaterialvid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,'1400604020061',null,'N',1,2,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000011OIG',1,-1,null,null,0,0,null,-1,'N',null,-1,'csenddeptvid',0,'N',1,'N','Y',null,0,'csenddeptvid','so.delivery.csenddeptvid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,null,null,'N',1,3,'delivery','delivery',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001HSQZ',1,0,null,null,0,1,null,-1,'N',null,20,'ibodyrowcount',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,'1400604020058',null,'N',1,2,'delivery','发货单主表',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001HVTV',1,0,null,null,0,1,null,-1,'N',null,20,'disp_ntotalastnum',0,'N',1,'N','Y','disp_ntotalastnum->setthmark(tostring(ntotalastnum))',0,null,null,null,'N',0,null,'1002Z810000000010ZZ3','@@@@',0,null,'1400604020042',null,'N',1,5,'delivery','发货单主表',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001HVTW',1,0,null,null,0,0,null,-1,'N',null,20,'disp_nastnum',0,'N',1,'N','Y','disp_nastnum->setthmark(tostring(nastnum))+tostring(castunitid.name)',0,null,null,null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,'1400604020060',null,'N',1,4,'body','发货单移动审批表体',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001IWW9',1,-1,null,null,0,1,null,-1,'N',null,-1,'cordercustid',0,'N',1,'N','Y',null,0,'cordercustid','so.delivery_b.cordercustid',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,'客户档案,code=N,dpc=SCMDefault','1400604020059',null,'N',1,1,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001IWWA',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.code',0,'N',1,'N','Y',null,0,'code','uap.material.code',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,null,null,'N',1,3,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001KGFJ',1,-1,null,null,0,0,null,-1,'N','castunitid',-1,'castunitid.name',0,'N',1,'N','N',null,0,'name','uap.measdoc.name',null,'N',0,null,'1002Z810000000010ZZ3','@@@@',1,null,null,null,'N',0,6,'body','body',0,'2012-08-10 13:26:38','N',null,null,null,1,1,'N',1,null,100,null)
go

