/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m30trantype.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 销售订单交易类型VO </b>
 * 
 * 创建日期:2010-01-25 18:42:55
 * 
 * @author 刘志伟
 * @version 6.0
 */
@SuppressWarnings("serial")
public class M30TranTypeVO extends SuperVO {

  // 只能安排一次发货
  public static final String BARRANGEINV = "barrangeinv";

  // 只能安排一次出库
  public static final String BARRANGEOUT = "barrangeout";

  // 退货入库之后才能换货出库
  public static final String BCANCHANGEOUT = "bcanchangeout";

  // 赠品行价格保持不变
  public static final String BLARGESSPRICENO = "blargesspriceno";

  // 询到价格是否可改
  public static final String BMODIFYASKEDQT = "bmodifyaskedqt";

  // 允许修改折扣
  public static final String BMODIFYDISCOUNT = "bmodifydiscount";

  // 未询到价格是否可改
  public static final String BMODIFYUNASKEDQT = "bmodifyunaskedqt";

  // 同一货物可否列多行
  public static final String BMOREROWS = "bmorerows";

  // 未询到价格是否提示
  public static final String BNOFINDPRICEHIT = "bnofindpricehit";

  // 红字订单支持订单收款
  public static final String BREDORDERPAY = "bredorderpay";

  // 修订询价
  public static final String BREVISEPRICE = "breviseprice";

  // 询价规则
  public static final String FASKQTRULE = "faskqtrule";

  // 直运类型标记
  public static final String FDIRECTTYPE = "fdirecttype";

  // 赠品价格分摊方式
  public static final String FLARGESSDISTYPE = "flargessdistype";

  // 赠品取价规则
  public static final String FLARGESSGETQTRULE = "flargessgetqtrule";

  // 调整金额影响折扣还是单价
  public static final String FMODIFYMNY = "fmodifymny";

  // 销售模式
  public static final String FSALEMODE = "fsalemode";

  // 集团
  public static final String PK_GROUP = "pk_group";

  // 销售订单交易类型
  public static final String PK_TRANTYPE = "pk_trantype";

  // 时间戳
  public static final String TS = "ts";

  // 交易类型编码
  public static final String VTRANTYPECODE = "vtrantypecode";

  // 交易类型
  public static final String CTRANTYPEID = "ctrantypeid";

  // 途损补货
  public static final String BLOSSRENEW = "blossrenew";

  // 赠品兑付
  public static final String BLRGCASHFLAG = "blrgcashflag";
  
  // 复制询价
  public static final String BCOPYISEPRICE = "bcopyiseprice";

  /**
   * 主记账单价取价规则
   */
  public static final String NACCPRICERULE = "naccpricerule";

  /**
   * 按照默认方式创建构造子.
   * 
   * 创建日期:2010-01-25 18:42:55
   */
  public M30TranTypeVO() {
    super();
  }

	/**
	 * 获取复制是否询价
	 * 
	 * @return
	 */
	public UFBoolean getBcopyiseprice() {
		return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BCOPYISEPRICE);
	}

	/**
	 * 设置复制是否询价的值
	 * 
	 * @param bmodifydiscount
	 */
	public void setBcopyieeprice(UFBoolean bcopyiseprice) {
		this.setAttributeValue(M30TranTypeVO.BCOPYISEPRICE, bcopyiseprice);
	}
  
  public UFBoolean getBlossrenew() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BLOSSRENEW);
  }

  public UFBoolean getBarrangeinv() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BARRANGEINV);
  }

  public UFBoolean getBarrangeout() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BARRANGEOUT);
  }

  public UFBoolean getBcanchangeout() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BCANCHANGEOUT);
  }

  public UFBoolean getBlargesspriceno() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BLARGESSPRICENO);
  }

  public UFBoolean getBmodifyaskedqt() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BMODIFYASKEDQT);
  }

  public UFBoolean getBmodifydiscount() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BMODIFYDISCOUNT);
  }

  public UFBoolean getBmodifyunaskedqt() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BMODIFYUNASKEDQT);
  }

  public UFBoolean getBmorerows() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BMOREROWS);
  }

  public UFBoolean getBnofindpricehit() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BNOFINDPRICEHIT);
  }

  public UFBoolean getBredorderpay() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BREDORDERPAY);
  }

  public UFBoolean getBreviseprice() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BREVISEPRICE);
  }

  public Integer getFaskqtrule() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FASKQTRULE);
  }

  public Integer getFdirecttype() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FDIRECTTYPE);
  }

  public Integer getFlargessdistype() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FLARGESSDISTYPE);
  }

  public Integer getFlargessgetqtrule() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FLARGESSGETQTRULE);
  }

  public Integer getFmodifymny() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FMODIFYMNY);
  }

  public Integer getFsalemode() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.FSALEMODE);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("so.m30trantype");
    return meta;
  }

  public String getPk_group() {
    return (String) this.getAttributeValue(M30TranTypeVO.PK_GROUP);
  }

  public String getPk_trantype() {
    return (String) this.getAttributeValue(M30TranTypeVO.PK_TRANTYPE);
  }

  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(M30TranTypeVO.TS);
  }

  public String getVtrantypecode() {
    return (String) this.getAttributeValue(M30TranTypeVO.VTRANTYPECODE);
  }

  public String getCtrantypeid() {
    return (String) this.getAttributeValue(M30TranTypeVO.CTRANTYPEID);
  }

  public Integer getNaccpricerule() {
    return (Integer) this.getAttributeValue(M30TranTypeVO.NACCPRICERULE);
  }

  public UFBoolean getBlrgcashflag() {
    return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BLRGCASHFLAG);
  }

  public void setBlossrenew(UFBoolean blossrenew) {
    this.setAttributeValue(M30TranTypeVO.BLOSSRENEW, blossrenew);
  }

  public void setBarrangeinv(UFBoolean barrangeinv) {
    this.setAttributeValue(M30TranTypeVO.BARRANGEINV, barrangeinv);
  }

  public void setBarrangeout(UFBoolean barrangeout) {
    this.setAttributeValue(M30TranTypeVO.BARRANGEOUT, barrangeout);
  }

  public void setBcanchangeout(UFBoolean bcanchangeout) {
    this.setAttributeValue(M30TranTypeVO.BCANCHANGEOUT, bcanchangeout);
  }

  public void setBlargesspriceno(UFBoolean blargesspriceno) {
    this.setAttributeValue(M30TranTypeVO.BLARGESSPRICENO, blargesspriceno);
  }

  public void setBmodifyaskedqt(UFBoolean bmodifyaskedqt) {
    this.setAttributeValue(M30TranTypeVO.BMODIFYASKEDQT, bmodifyaskedqt);
  }

  public void setBmodifydiscount(UFBoolean bmodifydiscount) {
    this.setAttributeValue(M30TranTypeVO.BMODIFYDISCOUNT, bmodifydiscount);
  }

  public void setBmodifyunaskedqt(UFBoolean bmodifyunaskedqt) {
    this.setAttributeValue(M30TranTypeVO.BMODIFYUNASKEDQT, bmodifyunaskedqt);
  }

  public void setBmorerows(UFBoolean bmorerows) {
    this.setAttributeValue(M30TranTypeVO.BMOREROWS, bmorerows);
  }

  public void setBnofindpricehit(UFBoolean bnofindpricehit) {
    this.setAttributeValue(M30TranTypeVO.BNOFINDPRICEHIT, bnofindpricehit);
  }

  public void setBredorderpay(UFBoolean bredorderpay) {
    this.setAttributeValue(M30TranTypeVO.BREDORDERPAY, bredorderpay);
  }

  public void setBreviseprice(UFBoolean breviseprice) {
    this.setAttributeValue(M30TranTypeVO.BREVISEPRICE, breviseprice);
  }

  public void setFaskqtrule(Integer faskqtrule) {
    this.setAttributeValue(M30TranTypeVO.FASKQTRULE, faskqtrule);
  }

  public void setFdirecttype(Integer fdirecttype) {
    this.setAttributeValue(M30TranTypeVO.FDIRECTTYPE, fdirecttype);
  }

  public void setFlargessdistype(Integer flargessdistype) {
    this.setAttributeValue(M30TranTypeVO.FLARGESSDISTYPE, flargessdistype);
  }

  public void setFlargessgetqtrule(Integer flargessgetqtrule) {
    this.setAttributeValue(M30TranTypeVO.FLARGESSGETQTRULE, flargessgetqtrule);
  }

  public void setFmodifymny(Integer fmodifymny) {
    this.setAttributeValue(M30TranTypeVO.FMODIFYMNY, fmodifymny);
  }

  public void setFsalemode(Integer fsalemode) {
    this.setAttributeValue(M30TranTypeVO.FSALEMODE, fsalemode);
  }

  public void setPk_group(String pk_group) {
    this.setAttributeValue(M30TranTypeVO.PK_GROUP, pk_group);
  }

  public void setPk_trantype(String pk_trantype) {
    this.setAttributeValue(M30TranTypeVO.PK_TRANTYPE, pk_trantype);
  }

  public void setTs(UFDateTime ts) {
    this.setAttributeValue(M30TranTypeVO.TS, ts);
  }

  public void setVtrantypecode(String vtrantypecode) {
    this.setAttributeValue(M30TranTypeVO.VTRANTYPECODE, vtrantypecode);
  }

  public void setCtrantypeid(String ctrantypeid) {
    this.setAttributeValue(M30TranTypeVO.CTRANTYPEID, ctrantypeid);
  }

  public void setBlrgcashflag(UFBoolean blrgcashflag) {
    this.setAttributeValue(M30TranTypeVO.BLRGCASHFLAG, blrgcashflag);
  }

  public void setnNaccpricerule(Integer naccpricerule) {
    this.setAttributeValue(M30TranTypeVO.NACCPRICERULE, naccpricerule);
  }

}
