insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000009PKZ',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bcopyiseprice',0,'N',1,'N','Y',null,0,'bcopyiseprice','so.m30trantype.bcopyiseprice',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,7,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000066A',1,-1,null,'4',0,1,null,-1,'N',null,-1,'naccpricerule',0,'N',1,'N','Y',null,0,'naccpricerule','so.m30trantype.naccpricerule',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,4,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUP',1,-1,null,'true',0,1,null,-1,'N',null,-1,'breviseprice',0,'N',1,'N','Y',null,0,'breviseprice','so.m30trantype.breviseprice',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,5,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUQ',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fmodifymny',0,'N',1,'N','Y',null,0,'fmodifymny','so.m30trantype.fmodifymny',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,6,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUR',1,-1,null,'false',0,1,null,-1,'N',null,-1,'barrangeout',0,'N',1,'N','Y',null,0,'barrangeout','so.m30trantype.barrangeout',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,1,'logistics_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUS',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bnofindpricehit',0,'N',1,'N','Y',null,0,'bnofindpricehit','so.m30trantype.bnofindpricehit',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,3,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUT',1,-1,null,'true',0,1,null,-1,'N',null,-1,'blargesspriceno',0,'N',1,'N','Y',null,0,'blargesspriceno','so.m30trantype.blargesspriceno',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,8,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUU',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bredorderpay',0,'N',1,'N','Y',null,0,'bredorderpay','so.m30trantype.bredorderpay',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,6,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUV',1,-1,null,'false',0,1,null,-1,'N',null,-1,'barrangeinv',0,'N',1,'N','Y',null,0,'barrangeinv','so.m30trantype.barrangeinv',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,0,'logistics_attr','物流属性',0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000002TUW',1,-1,null,'0',0,1,null,-1,'N',null,-1,'flargessdistype',0,'N',1,'N','Y',null,0,'flargessdistype','so.m30trantype.flargessdistype',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,7,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003E3M',1,-1,null,'false',0,1,null,-1,'N',null,-1,'blrgcashflag',0,'N',1,'N','Y',null,0,'blrgcashflag','so.m30trantype.blrgcashflag',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,3,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000027JZ5',1,0,'price_attr',null,0,0,null,-1,'N',null,20,'price_attr',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,'1400603010188',null,'N',0,9,'price_attr','价格属性',0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000027JZ6',1,0,'logistics_attr',null,0,0,null,-1,'N',null,20,'logistics_attr',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,'1400603010189',null,'N',0,3,'logistics_attr','物流属性',0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000002R9IQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.m30trantype.vtrantypecode',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',0,12,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,0,0,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000002R9IR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.m30trantype.pk_group',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',0,11,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,0,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001BKA',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmodifyaskedqt',0,'N',1,'N','Y',null,0,'bmodifyaskedqt','so.m30trantype.bmodifyaskedqt',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,1,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001BKB',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.m30trantype.ts',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',0,10,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001BKC',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmorerows',0,'N',1,'N','Y',null,0,'bmorerows','so.m30trantype.bmorerows',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,5,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001BKD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_trantype',0,'N',1,'N','N',null,0,'pk_trantype','so.m30trantype.pk_trantype',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',0,9,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK2',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bcanchangeout',0,'N',1,'N','Y',null,0,'bcanchangeout','so.m30trantype.bcanchangeout',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,2,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK3',1,-1,null,'true',0,1,null,-1,'N',null,-1,'bmodifydiscount',0,'N',1,'N','Y',null,0,'bmodifydiscount','so.m30trantype.bmodifydiscount',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,8,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK4',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fdirecttype',0,'N',1,'N','Y',null,0,'fdirecttype','so.m30trantype.fdirecttype',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,0,'base_attr','基本属性',0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK5',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmodifyunaskedqt',0,'N',1,'N','Y',null,0,'bmodifyunaskedqt','so.m30trantype.bmodifyunaskedqt',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,2,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK6',1,-1,null,'1',0,1,null,-1,'N',null,-1,'flargessgetqtrule',0,'N',1,'N','Y',null,0,'flargessgetqtrule','so.m30trantype.flargessgetqtrule',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,4,'price_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK7',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fsalemode',0,'N',1,'N','Y',null,0,'fsalemode','so.m30trantype.fsalemode',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,1,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK8',1,-1,null,'2',0,1,null,-1,'N',null,-1,'faskqtrule',0,'N',1,'N','Y',null,0,'faskqtrule','so.m30trantype.faskqtrule',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,0,'price_attr','价格属性',0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001OYH',1,-1,null,'true',0,1,null,-1,'N',null,-1,'blossrenew',0,'N',1,'N','Y',null,0,'blossrenew','so.m30trantype.blossrenew',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',1,2,'logistics_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001IK9',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','N',null,0,'ctrantypeid','so.m30trantype.ctrantypeid',null,'N',0,null,'1002Z810000000001JK1','@@@@',0,null,null,null,'N',0,13,'base_attr',null,0,'2015-04-02 09:51:07','N',null,null,null,1,1,'N',1,null,1,14)
go

