insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000079KR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','so.returnreason.pk_org',null,'N',0,null,'1002Z810000000003JBR',null,1,'销售组织,code=N,type=0','140060801010001',null,'N',0,1,'returnreason','returnreason',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vreasonname',0,'N',1,'N','Y',null,0,'vreasonname','so.returnreason.vreasonname',null,'N',1,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',1,5,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBT',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_returnreason',0,'N',1,'N','N',null,0,'pk_returnreason','so.returnreason.pk_returnreason',null,'N',0,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',0,3,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBU',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.returnreason.ts',null,'N',0,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',0,9,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBV',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','Y',null,0,'pk_group','so.returnreason.pk_group',null,'N',0,null,'1002Z810000000003JBR','@@@@',1,'集团,code=N,type=0',null,null,'N',1,2,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBW',1,-1,null,null,0,1,null,-1,'N',null,30,'vreasoncode',0,'N',1,'N','Y',null,0,'vreasoncode','so.returnreason.vreasoncode',null,'N',1,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',1,4,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBX',1,-1,null,null,0,1,null,-1,'N',null,-1,'freasontype',0,'N',1,'N','Y',null,0,'freasontype','so.returnreason.freasontype',null,'N',1,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',1,6,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBY',1,-1,null,null,0,1,null,-1,'N',null,200,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.returnreason.vnote',null,'N',0,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',1,8,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000003JBZ',1,-1,null,null,0,1,null,-1,'N',null,100,'vreturnmode',0,'N',1,'N','Y',null,0,'vreturnmode','so.returnreason.vreturnmode',null,'N',1,null,'1002Z810000000003JBR','@@@@',1,null,null,null,'N',1,7,'returnreason','退货原因',0,'2011-07-28 19:49:41','N',null,null,null,1,1,'N',1,null,100,null)
go

