/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m4310trantype.entity;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:${vmObject.createdDate}
 * 
 * @author
 * @version NCPrj ??
 */
public class HisSalequoPriceSource extends MDEnum {
  /**
   * 平均价
   */
  public static final HisSalequoPriceSource AVERAGE_PRICE = MDEnum.valueOf(
      HisSalequoPriceSource.class, Integer.valueOf(2));

  /**
   * 最新价
   */
  public static final HisSalequoPriceSource LASEST_PRICE = MDEnum.valueOf(
      HisSalequoPriceSource.class, Integer.valueOf(1));

  public HisSalequoPriceSource(IEnumValue enumvalue) {
    super(enumvalue);
  }

}
