/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.so.m4310trantype.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.data.ValueUtils;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
import nc.vo.so.m30trantype.entity.M30TranTypeVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-07-13 15:09:52
 * 
 * @author
 * @version NCPrj ??
 */
public class M4310TranTypeVO extends SuperVO {

	public static final String BAREAMATRULE = "bareamatrule";

	public static final String BAUTOCLOSEFLAG = "bautocloseflag";

	public static final String BBALATYPEMATRULE = "bbalatypematrule";

	public static final String BCHANMATRULE = "bchanmatrule";

	public static final String BCURRTYPEMATRULE = "bcurrtypematrule";

	public static final String BCUSTMATRULE = "bcustmatrule";

	public static final String BDEPTMATRULE = "bdeptmatrule";

	public static final String BDISCOUNTEDITABLE = "bdiscounteditable";

	public static final String BEMPMATRULE = "bempmatrule";

	public static final String BFAILQTEDITABLE = "bfailqteditable";

	public static final String BPAYTERMMATRULE = "bpaytermmatrule";

	public static final String BQUALLEVELMATRULE = "bquallevelmatrule";

	public static final String BQUOTYPEMATRULE = "bquotypematrule";

	public static final String BSAVEPRICEDETAILFLAG = "bsavepricedetailflag";

	public static final String BSENDTYPEMATRULE = "bsendtypematrule";

	public static final String BSUCCQTEDITABLE = "bsuccqteditable";

	public static final String BUNITMATRULE = "bunitmatrule";

	public static final String CTRANTYPEID = "ctrantypeid";

	public static final String FHISTORYFLAG = "fhistoryflag";

	public static final String FMODIFYMNY = "fmodifymny";

	public static final String FSOURCEFLAG = "fsourceflag";

	public static final String IAVGMONTH = "iavgmonth";

	public static final String PK_GROUP = "pk_group";

	public static final String PK_TRANTYPE = "pk_trantype";

	public static final String VMATCHRULE = "vmatchrule";

	public static final String VTRANTYPE = "vtrantype";

	// 同一货物可否列多行
	public static final String BMOREROWS = "bmorerows";

	/**
   * 
   */
	private static final long serialVersionUID = 6458724264074538213L;

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2010-07-13 15:09:52
	 */
	public M4310TranTypeVO() {
		super();
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "so_salequotationtype";
	}

	/**
	 * 属性bareamatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBareamatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BAREAMATRULE);
	}

	/**
	 * 属性bautocloseflag的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBautocloseflag() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BAUTOCLOSEFLAG);
	}

	/**
	 * 属性bbalatypematrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBbalatypematrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BBALATYPEMATRULE);
	}

	/**
	 * 属性bchanmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBchanmatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BCHANMATRULE);
	}

	/**
	 * 属性bcurrtypematrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBcurrtypematrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BCURRTYPEMATRULE);
	}

	/**
	 * 属性bcustmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBcustmatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BCUSTMATRULE);
	}

	/**
	 * 属性bdeptmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBdeptmatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BDEPTMATRULE);
	}

	/**
	 * 属性bdiscounteditable的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBdiscounteditable() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BDISCOUNTEDITABLE);
	}

	/**
	 * 属性bempmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBempmatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BEMPMATRULE);
	}

	/**
	 * 属性bfailqteditable的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBfailqteditable() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BFAILQTEDITABLE);
	}

	/**
	 * 属性bpaytermmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBpaytermmatrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BPAYTERMMATRULE);
	}

	/**
	 * 属性bquallevelmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBquallevelmatrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BQUALLEVELMATRULE);
	}

	// /**
	// * 属性bsavepricedetailflag的Getter方法. 创建日期:2010-07-13 15:09:52
	// *
	// * @return nc.vo.pub.lang.UFBoolean
	// */
	// public nc.vo.pub.lang.UFBoolean getBsavepricedetailflag() {
	// return (UFBoolean) getAttributeValue(BSAVEPRICEDETAILFLAG);
	// }
	//
	// /**
	// * 属性bsavepricedetailflag的Setter方法. 创建日期:2010-07-13 15:09:52
	// *
	// * @param newBsavepricedetailflag
	// * nc.vo.pub.lang.UFBoolean
	// */
	// public void setBsavepricedetailflag(
	// nc.vo.pub.lang.UFBoolean newBsavepricedetailflag) {
	// setAttributeValue(BSAVEPRICEDETAILFLAG, newBsavepricedetailflag);
	// }

	/**
	 * 属性bquotypematrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBquotypematrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BQUOTYPEMATRULE);
	}

	/**
	 * 属性bsendtypematrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBsendtypematrule() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BSENDTYPEMATRULE);
	}

	/**
	 * 属性bsuccqteditable的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBsuccqteditable() {
		return (UFBoolean) this
				.getAttributeValue(M4310TranTypeVO.BSUCCQTEDITABLE);
	}

	/**
	 * 属性bunitmatrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBunitmatrule() {
		return (UFBoolean) this.getAttributeValue(M4310TranTypeVO.BUNITMATRULE);
	}

	public String getCtrantypeid() {
		return (String) this.getAttributeValue(M4310TranTypeVO.CTRANTYPEID);
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return (Integer) this.getAttributeValue("dr");
	}

	/**
	 * 属性fhistoryflag的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.Integer getFhistoryflag() {
		return (Integer) this.getAttributeValue(M4310TranTypeVO.FHISTORYFLAG);
	}

	public String getFmodifymny() {
		return ValueUtils.getString(this
				.getAttributeValue(M4310TranTypeVO.FMODIFYMNY));
	}

	/**
	 * 属性fsourceflag的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public Integer getFsourceflag() {
		return (Integer) this.getAttributeValue(M4310TranTypeVO.FSOURCEFLAG);
	}

	/**
	 * 属性iavgmonth的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIavgmonth() {
		return (Integer) this.getAttributeValue(M4310TranTypeVO.IAVGMONTH);
	}

	@Override
	public IVOMeta getMetaData() {
		// TODO Auto-generated method stub
		IVOMeta meta = VOMetaFactory.getInstance()
				.getVOMeta("so.m4310trantype");
		return meta;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * 属性pk_group的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return (String) this.getAttributeValue(M4310TranTypeVO.PK_GROUP);
	}

	/**
	 * 属性pk_trantype的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_trantype() {
		return (String) this.getAttributeValue(M4310TranTypeVO.PK_TRANTYPE);
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "pk_trantype";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "so_salequotationtype";
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return (UFDateTime) this.getAttributeValue("ts");
	}

	/**
	 * 属性vmatchrule的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVmatchrule() {
		return (String) this.getAttributeValue(M4310TranTypeVO.VMATCHRULE);
	}

	/**
	 * 属性vtrantype的Getter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVtrantype() {
		return (String) this.getAttributeValue(M4310TranTypeVO.VTRANTYPE);
	}

	public UFBoolean getBmorerows() {
		return (UFBoolean) this.getAttributeValue(M30TranTypeVO.BMOREROWS);
	}

	/**
	 * 属性bareamatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBareamatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBareamatrule(nc.vo.pub.lang.UFBoolean newBareamatrule) {
		this.setAttributeValue(M4310TranTypeVO.BAREAMATRULE, newBareamatrule);
	}

	/**
	 * 属性bautocloseflag的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBautocloseflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBautocloseflag(nc.vo.pub.lang.UFBoolean newBautocloseflag) {
		this.setAttributeValue(M4310TranTypeVO.BAUTOCLOSEFLAG,
				newBautocloseflag);
	}

	/**
	 * 属性bbalatypematrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBbalatypematrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBbalatypematrule(nc.vo.pub.lang.UFBoolean newBbalatypematrule) {
		this.setAttributeValue(M4310TranTypeVO.BBALATYPEMATRULE,
				newBbalatypematrule);
	}

	/**
	 * 属性bchanmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBchanmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBchanmatrule(nc.vo.pub.lang.UFBoolean newBchanmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BCHANMATRULE, newBchanmatrule);
	}

	/**
	 * 属性bcurrtypematrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBcurrtypematrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBcurrtypematrule(nc.vo.pub.lang.UFBoolean newBcurrtypematrule) {
		this.setAttributeValue(M4310TranTypeVO.BCURRTYPEMATRULE,
				newBcurrtypematrule);
	}

	/**
	 * 属性bcustmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBcustmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBcustmatrule(nc.vo.pub.lang.UFBoolean newBcustmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BCUSTMATRULE, newBcustmatrule);
	}

	/**
	 * 属性bdeptmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBsavepricedetailflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBdeptmatrule(nc.vo.pub.lang.UFBoolean newBdeptmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BDEPTMATRULE, newBdeptmatrule);
	}

	/**
	 * 属性bdiscounteditable的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBdiscounteditable
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBdiscounteditable(
			nc.vo.pub.lang.UFBoolean newBdiscounteditable) {
		this.setAttributeValue(M4310TranTypeVO.BDISCOUNTEDITABLE,
				newBdiscounteditable);
	}

	/**
	 * 属性bempmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBempmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBempmatrule(nc.vo.pub.lang.UFBoolean newBempmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BEMPMATRULE, newBempmatrule);
	}

	/**
	 * 属性bfailqteditable的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBfailqteditable
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBfailqteditable(nc.vo.pub.lang.UFBoolean newBfailqteditable) {
		this.setAttributeValue(M4310TranTypeVO.BFAILQTEDITABLE,
				newBfailqteditable);
	}

	/**
	 * 属性bpaytermmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBpaytermmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBpaytermmatrule(nc.vo.pub.lang.UFBoolean newBpaytermmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BPAYTERMMATRULE,
				newBpaytermmatrule);
	}

	/**
	 * 属性bquallevelmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBquallevelmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBquallevelmatrule(
			nc.vo.pub.lang.UFBoolean newBquallevelmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BQUALLEVELMATRULE,
				newBquallevelmatrule);
	}

	/**
	 * 属性bquotypematrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBquotypematrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBquotypematrule(nc.vo.pub.lang.UFBoolean newBquotypematrule) {
		this.setAttributeValue(M4310TranTypeVO.BQUOTYPEMATRULE,
				newBquotypematrule);
	}

	/**
	 * 属性bsendtypematrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBsendtypematrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBsendtypematrule(nc.vo.pub.lang.UFBoolean newBsendtypematrule) {
		this.setAttributeValue(M4310TranTypeVO.BSENDTYPEMATRULE,
				newBsendtypematrule);
	}

	/**
	 * 属性bsuccqteditable的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBsuccqteditable
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBsuccqteditable(nc.vo.pub.lang.UFBoolean newBsuccqteditable) {
		this.setAttributeValue(M4310TranTypeVO.BSUCCQTEDITABLE,
				newBsuccqteditable);
	}

	/**
	 * 属性bunitmatrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newBunitmatrule
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBunitmatrule(nc.vo.pub.lang.UFBoolean newBunitmatrule) {
		this.setAttributeValue(M4310TranTypeVO.BUNITMATRULE, newBunitmatrule);
	}

	public void setCtrantypeid(String ctrantypeid) {
		this.setAttributeValue(M4310TranTypeVO.CTRANTYPEID, ctrantypeid);
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.setAttributeValue("dr", newDr);
	}

	/**
	 * 属性fhistoryflag的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newFhistoryflag
	 *            java.lang.String
	 */
	public void setFhistoryflag(java.lang.Integer newFhistoryflag) {
		this.setAttributeValue(M4310TranTypeVO.FHISTORYFLAG, newFhistoryflag);
	}

	public void setFmodifymny(String fmodifymny) {
		this.setAttributeValue(M4310TranTypeVO.FMODIFYMNY, fmodifymny);
	}

	/**
	 * 属性fsourceflag的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newFsourceflag
	 *            java.lang.String
	 */
	public void setFsourceflag(java.lang.Integer newFsourceflag) {
		this.setAttributeValue(M4310TranTypeVO.FSOURCEFLAG, newFsourceflag);
	}

	/**
	 * 属性iavgmonth的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newIavgmonth
	 *            java.lang.Integer
	 */
	public void setIavgmonth(java.lang.Integer newIavgmonth) {
		this.setAttributeValue(M4310TranTypeVO.IAVGMONTH, newIavgmonth);
	}

	/**
	 * 属性pk_group的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.setAttributeValue(M4310TranTypeVO.PK_GROUP, newPk_group);
	}

	/**
	 * 属性pk_trantype的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newPk_trantype
	 *            java.lang.String
	 */
	public void setPk_trantype(java.lang.String newPk_trantype) {
		this.setAttributeValue(M4310TranTypeVO.PK_TRANTYPE, newPk_trantype);
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.setAttributeValue("ts", newTs);
	}

	/**
	 * 属性vmatchrule的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newVmatchrule
	 *            java.lang.String
	 */
	public void setVmatchrule(java.lang.String newVmatchrule) {
		this.setAttributeValue(M4310TranTypeVO.VMATCHRULE, newVmatchrule);
	}

	/**
	 * 属性vtrantype的Setter方法. 创建日期:2010-07-13 15:09:52
	 * 
	 * @param newVtrantype
	 *            java.lang.String
	 */
	public void setVtrantype(java.lang.String newVtrantype) {
		this.setAttributeValue(M4310TranTypeVO.VTRANTYPE, newVtrantype);
	}

	public void setBmorerows(UFBoolean bmorerows) {
		this.setAttributeValue(M30TranTypeVO.BMOREROWS, bmorerows);
	}

}
