insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000001V4P',1,-1,null,'1',0,1,null,-1,'N',null,-1,'fmodifymny',null,'N',1,'N','Y',null,0,'fmodifymny','so.m38trantype.fmodifymny',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,9,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055YV',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','so.m38trantype.ts',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',0,11,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055YW',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmodifyaskedqt',null,'N',1,'N','Y',null,0,'bmodifyaskedqt','so.m38trantype.bmodifyaskedqt',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,4,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055YX',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmodifydiscount',null,'N',1,'N','Y',null,0,'bmodifydiscount','so.m38trantype.bmodifydiscount',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,8,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055YY',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_trantype',null,'N',1,'N','N',null,0,'pk_trantype','so.m38trantype.pk_trantype',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',0,1,'38trantype','预订单交易类型',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055YZ',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmodifyunaskedqt',null,'N',1,'N','Y',null,0,'bmodifyunaskedqt','so.m38trantype.bmodifyunaskedqt',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,5,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055Z0',1,-1,null,'1',0,1,null,-1,'N',null,-1,'faskqtrule',null,'N',1,'N','Y',null,0,'faskqtrule','so.m38trantype.faskqtrule',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,3,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055Z1',1,-1,null,'false',0,1,null,-1,'N',null,-1,'barrange',null,'N',1,'N','Y',null,0,'barrange','so.m38trantype.barrange',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,10,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055Z2',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bmorerows',null,'N',1,'N','Y',null,0,'bmorerows','so.m38trantype.bmorerows',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',1,2,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000055Z5',1,-1,null,'1',0,1,null,-1,'N',null,-1,'flargessgetqtrule',null,'N',1,'N','N',null,0,'flargessgetqtrule','so.m38trantype.flargessgetqtrule',null,'N',0,null,'1001Z8100000000055YU',null,0,null,null,null,'N',0,7,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000G8VT',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bnofindpricehit',0,'N',1,'N','Y',null,0,'bnofindpricehit','so.m38trantype.bnofindpricehit',null,'N',0,null,'1001Z8100000000055YU','@@@@',0,null,null,null,'N',1,6,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000KBHG',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','so.m38trantype.vtrantypecode',null,'N',0,null,'1001Z8100000000055YU','@@@@',0,null,null,null,'N',0,13,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000KBHH',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.m38trantype.pk_group',null,'N',0,null,'1001Z8100000000055YU','@@@@',0,null,null,null,'N',0,12,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000001ACQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','N',null,0,'ctrantypeid','so.m38trantype.ctrantypeid',null,'N',0,null,'1001Z8100000000055YU','@@@@',0,null,null,null,'N',0,14,'38trantype','38trantype',0,'2013-04-10 16:54:41','N',null,null,null,1,1,'N',1,null,1,null)
go

