insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKA',1,-1,null,null,0,1,null,-1,'N',null,-1,'carsubbid',0,'N',1,'N','Y',null,0,'carsubbid','so.arsub_b.carsubbid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,49,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef3',0,'N',1,'N','N',null,0,'vbdef3','so.arsub_b.vbdef3',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,60,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,60)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef9',0,'N',1,'N','N',null,0,'vbdef9','so.arsub_b.vbdef9',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,66,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,66)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKD',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprodlineid',0,'N',1,'N','Y',null,0,'cprodlineid','so.arsub_b.cprodlineid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'产品线,code=N',null,null,'N',1,51,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKE',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','so.arsub.modifiedtime',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,24,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKF',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef18',0,'N',1,'N','N',null,0,'vdef18','so.arsub.vdef18',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,45,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKG',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef8',0,'N',1,'N','N',null,0,'vdef8','so.arsub.vdef8',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,35,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKH',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef1',0,'N',1,'N','N',null,0,'vbdef1','so.arsub_b.vbdef1',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,58,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKI',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','so.arsub_b.crowno',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,50,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','Y',null,0,'corigcurrencyid','so.arsub.corigcurrencyid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'币种档案,code=N',null,null,'N',1,16,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef11',0,'N',1,'N','N',null,0,'vbdef11','so.arsub_b.vbdef11',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,68,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,68)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKL',1,-1,null,null,0,1,null,-1,'N',null,-1,'csaleorgvid',0,'N',1,'N','Y',null,0,'csaleorgvid','so.arsub.csaleorgvid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'销售组织版本,code=N',null,null,'N',1,9,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef4',0,'N',1,'N','N',null,0,'vdef4','so.arsub.vdef4',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,31,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKN',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef5',0,'N',1,'N','N',null,0,'vbdef5','so.arsub_b.vbdef5',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,62,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,62)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef6',0,'N',1,'N','N',null,0,'vdef6','so.arsub.vdef6',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,33,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef10',0,'N',1,'N','N',null,0,'vdef10','so.arsub.vdef10',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,37,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef14',0,'N',1,'N','N',null,0,'vdef14','so.arsub.vdef14',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,41,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKR',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef12',0,'N',1,'N','N',null,0,'vdef12','so.arsub.vdef12',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,39,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef13',0,'N',1,'N','N',null,0,'vdef13','so.arsub.vdef13',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,40,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',null,0,'vnote','so.arsub.vnote',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,19,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKU',1,-1,null,null,0,1,null,-1,'N',null,-1,'csaleorgid',0,'N',1,'N','Y',null,0,'csaleorgid','so.arsub.csaleorgid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'销售组织,code=N',null,null,'N',1,8,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKV',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef15',0,'N',1,'N','N',null,0,'vbdef15','so.arsub_b.vbdef15',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,72,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,72)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef20',0,'N',1,'N','N',null,0,'vbdef20','so.arsub_b.vbdef20',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,77,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,77)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKY',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','so.arsub.pk_org_v',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'财务组织版本(所有),code=N',null,null,'N',1,4,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',0,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EKZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'norigarsubmny',0,'N',1,'N','Y',null,0,'norigarsubmny','so.arsub_b.norigarsubmny',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,53,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef8',0,'N',1,'N','N',null,0,'vbdef8','so.arsub_b.vbdef8',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,65,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,65)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL1',1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','so.arsub.taudittime',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,26,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL2',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef14',0,'N',1,'N','N',null,0,'vbdef14','so.arsub_b.vbdef14',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,71,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL3',1,-1,null,null,0,1,null,-1,'N',null,-1,'iprintcount',0,'N',1,'N','N',null,0,'iprintcount','so.arsub.iprintcount',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,27,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef19',0,'N',1,'N','N',null,0,'vbdef19','so.arsub_b.vbdef19',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,76,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,76)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL5',1,-1,null,null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','so.arsub.cemployeeid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'人员,code=N',null,null,'N',1,12,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef16',0,'N',1,'N','N',null,0,'vdef16','so.arsub.vdef16',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,43,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL7',1,-1,null,null,0,1,null,-1,'N',null,-1,'carsubid',0,'N',1,'N','Y',null,0,'carsubid','so.arsub.carsubid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,1,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL8',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeptid',0,'N',1,'N','Y',null,0,'cdeptid','so.arsub.cdeptid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'部门,code=N',null,null,'N',1,13,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EL9',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef10',0,'N',1,'N','N',null,0,'vbdef10','so.arsub_b.vbdef10',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,67,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELA',1,-1,null,null,0,1,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','Y',null,0,'fstatusflag','so.arsub.fstatusflag',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,18,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','Y',null,0,'vtrantypecode','so.arsub.vtrantypecode',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,6,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef18',0,'N',1,'N','N',null,0,'vbdef18','so.arsub_b.vbdef18',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,75,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,75)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELD',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef5',0,'N',1,'N','N',null,0,'vdef5','so.arsub.vdef5',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,32,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELE',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','so.arsub.creator',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'用户,code=N',null,null,'N',1,20,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELF',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef20',0,'N',1,'N','N',null,0,'vdef20','so.arsub.vdef20',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,47,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELG',1,-1,null,null,0,1,null,-1,'N',null,-1,'cinvoicecustid',0,'N',1,'N','Y',null,0,'cinvoicecustid','so.arsub.cinvoicecustid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'客户档案,code=N',null,null,'N',1,15,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELH',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','so.arsub.ts',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,48,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','so.arsub.pk_group',null,'N',0,null,'1001Z81000000000593F','@@@@',1,',code=N',null,null,'N',0,2,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,0,1,'N',0,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELK',1,-1,null,null,0,1,null,-1,'N',null,-1,'cchanneltypeid',0,'N',1,'N','Y',null,0,'cchanneltypeid','so.arsub.cchanneltypeid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'渠道类型,code=N',null,null,'N',1,11,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef6',0,'N',1,'N','N',null,0,'vbdef6','so.arsub_b.vbdef6',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,63,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,63)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef2',0,'N',1,'N','N',null,0,'vdef2','so.arsub.vdef2',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,29,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELN',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef19',0,'N',1,'N','N',null,0,'vdef19','so.arsub.vdef19',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,46,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef17',0,'N',1,'N','N',null,0,'vdef17','so.arsub.vdef17',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,44,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef2',0,'N',1,'N','N',null,0,'vbdef2','so.arsub_b.vbdef2',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,59,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,59)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','N',null,0,'dbilldate','so.arsub.dbilldate',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,7,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,0,1,'N',0,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELR',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef16',0,'N',1,'N','N',null,0,'vbdef16','so.arsub_b.vbdef16',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,73,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,73)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef1',0,'N',1,'N','N',null,0,'vdef1','so.arsub.vdef1',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,28,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELT',1,-1,null,null,0,1,null,-1,'N',null,-1,'nremainmny',0,'N',1,'N','Y',null,0,'nremainmny','so.arsub_b.nremainmny',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,57,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,57)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELU',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef15',0,'N',1,'N','N',null,0,'vdef15','so.arsub.vdef15',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,42,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELV',1,-1,null,null,0,1,null,-1,'N',null,-1,'frownote',0,'N',1,'N','Y',null,0,'frownote','so.arsub_b.frownote',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,56,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,56)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef12',0,'N',1,'N','N',null,0,'vbdef12','so.arsub_b.vbdef12',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,69,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,69)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELX',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','so.arsub.pk_org',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'财务组织,code=N',null,null,'N',1,3,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',0,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005ELZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef9',0,'N',1,'N','N',null,0,'vdef9','so.arsub.vdef9',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,36,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM1',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef3',0,'N',1,'N','N',null,0,'vdef3','so.arsub.vdef3',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,30,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM2',1,-1,null,null,0,1,null,-1,'N',null,-1,'bsubfinshflag',0,'N',1,'N','Y',null,0,'bsubfinshflag','so.arsub_b.bsubfinshflag',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,55,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,55)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM3',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdeptvid',0,'N',1,'N','Y',null,0,'cdeptvid','so.arsub.cdeptvid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'部门版本,code=N',null,null,'N',1,14,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM4',1,-1,null,null,0,1,null,-1,'N',null,-1,'noriginvoicemny',0,'N',1,'N','Y',null,0,'noriginvoicemny','so.arsub_b.noriginvoicemny',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,78,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,78)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM5',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef13',0,'N',1,'N','N',null,0,'vbdef13','so.arsub_b.vbdef13',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,70,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,70)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM6',1,-1,null,null,0,1,null,-1,'N',null,-1,'cordercustid',0,'N',1,'N','Y',null,0,'cordercustid','so.arsub.cordercustid',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'客户档案,code=N,dpc=SCMDefault',null,null,'N',1,10,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM7',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef17',0,'N',1,'N','N',null,0,'vbdef17','so.arsub_b.vbdef17',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,74,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,74)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM8',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef4',0,'N',1,'N','N',null,0,'vbdef4','so.arsub_b.vbdef4',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,61,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,61)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EM9',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','so.arsub.approver',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'用户,code=N',null,null,'N',1,25,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMA',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','so.arsub.creationtime',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,22,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef7',0,'N',1,'N','N',null,0,'vbdef7','so.arsub_b.vbdef7',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,64,'view','view',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,64)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef7',0,'N',1,'N','N',null,0,'vdef7','so.arsub.vdef7',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,34,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMD',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','so.arsub.modifier',null,'N',0,null,'1001Z81000000000593F','@@@@',1,'用户,code=N',null,null,'N',1,23,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EME',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef11',0,'N',1,'N','N',null,0,'vdef11','so.arsub.vdef11',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',0,38,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000005EMF',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','so.arsub.vbillcode',null,'N',0,null,'1001Z81000000000593F','@@@@',1,null,null,null,'N',1,5,'view','冲应收单',0,'2015-07-07 22:56:04','N',null,null,null,1,1,'N',1,null,100,5)
go

