insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCR',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',null,'N',1,'N','N',null,0,'cunitid','so.OutRushExeInfoVO.cunitid',null,'N',0,null,'0001Z81000000001FOCQ',null,1,'计量单位,code=N',null,null,'N',0,12,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCS',1,-1,null,null,0,0,null,-1,'N',null,-1,'vrushbillcode',null,'N',1,'N','Y',null,0,'vrushbillcode','so.OutRushExeInfoVO.vrushbillcode',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,3,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCT',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',null,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,8,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCU',1,-1,null,null,0,0,null,-1,'N',null,-1,'crushbillrowno',null,'N',1,'N','Y',null,0,'crushbillrowno','so.OutRushExeInfoVO.crushbillrowno',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,4,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCV',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',null,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,7,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCW',1,-1,null,null,0,0,null,-1,'N',null,-1,'csquarebillbid',null,'N',1,'N','N',null,0,'csquarebillbid','so.OutRushExeInfoVO.csquarebillbid',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',0,1,'csquarebillbid','销售出库单子实体',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCX',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialvid',null,'N',1,'N','N',null,0,'cmaterialvid','so.OutRushExeInfoVO.cmaterialvid',null,'N',0,null,'0001Z81000000001FOCQ',null,1,'物料（多版本）,code=N',null,null,'N',0,5,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCY',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.code',null,'N',1,'N','Y',null,0,'code','uap.material.code',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,6,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOCZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',null,'N',1,'N','Y',null,0,'crowno','so.OutRushExeInfoVO.crowno',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,2,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOD0',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',null,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,9,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOD1',1,-1,null,null,0,0,null,-1,'N',null,-1,'noutrushnum',null,'N',1,'N','Y',null,0,'noutrushnum','so.OutRushExeInfoVO.noutrushnum',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,11,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001FOD2',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnum',null,'N',1,'N','Y',null,0,'nnum','so.OutRushExeInfoVO.nnum',null,'N',0,null,'0001Z81000000001FOCQ',null,1,null,null,null,'N',1,10,'csquarebillbid','csquarebillbid',0,'2011-08-31 12:11:12','N',null,null,null,1,1,'N',1,null,100,null)
go

